### ISSUE TITLE
Updating from v2

### ISSUE THREAD

**Issue by markladage** [vmstan/gravity-sync#102]
Hello,

i'm currently running v2 and wan't to upgrade to v3. Should i follow the installation instruction or just run the update command?

Gr. Mark

**Comment by vmstan** [comment]
If everything is working fine in v2, you can just update to v3 using the update function. The installer is just to make things smoother for new folks.

**Comment by markladage** [comment]
Hello Michael,

thanks for your answer, but what about the Master Pi. With version 2 it didn't need any preparation though?

⁣Verzonden door BlueMail ​

Op 9 okt. 2020 15:18, om 15:18, Michael Stanclift <notifications@github.com> schreef:

**Comment by vmstan** [comment]
If you run the installer on the primary, all it really changes is adding a config file to your sudoers.d folder that makes sure the account you're using has passwordless sudo available. If your install is already working, you don't need to run it. If you want to run it to make sure your install is "future proofed" than go ahead. You can also run `./gravity-sync.sh sudo` on your secondary to make sure the file exists there too.

**Comment by markladage** [comment]
Ok thanks

⁣Verzonden door BlueMail ​

Op 9 okt. 2020 17:23, om 17:23, Michael Stanclift <notifications@github.com> schreef:

**Comment by jostrasser** [comment]
> If everything is working fine in v2, you can just update to v3 using the update function. The installer is just to make things smoother for new folks.

@vmstan 

Hi! 
Can you explain how I can update a running installation to the newest release? I cannot find any about it in the documentation. 

Thanks!

**Comment by vmstan** [comment]
https://github.com/vmstan/gravity-sync/wiki/Updating

**Comment by jostrasser** [comment]
> https://github.com/vmstan/gravity-sync/wiki/Updating

Oh dear, I missed that. ;)
Many thanks!

**Comment by vmstan** [comment]
No worries. It used to be part of the one large README but it was becoming a giant wall of text that no one was reading.
