### ISSUE TITLE
Unclear how to configure Secondary if Primary machine gravity.db and pihole-FTL.db databases have been moved to a non-standard location

### ISSUE THREAD

**Issue by StevenAJC** [vmstan/gravity-sync#107]
**Describe the Issue**
On primary machine the gravity.db and pihole-FTL.db databases have been moved to a mounted usb drive (/mnt/usbdrive/etc/pihole)

On the Primary, /etc/pihole/pihole-FTL.conf has been updated so that PiHole uses this new location:
DBFILE=/mnt/usbdrive/etc/pihole/pihole-FTL.db
GRAVITYDB=/mnt/usbdrive/etc/pihole/gravity.db

Primary PiHole is succesfully using and updating those .db files.

On the Secondary the .db files are in the standard /etc/pihole

On the Secondary it is not clear how to configure for the alternative Primary .db location. 

The gravity-sync.conf includes the following options but it is not clear if they relate to the Primary, the Secondary, or indeed if they are combined configurations that assumed both Primary and Secondary have the .db files in the same directory structure. (Or indeed if they are entirely the wrong settings.)
Have a very good reason to change these!
PIHOLE_DIR=''
PIHOLE_BIN=''
RIHOLE_BIN=''
Unfortunately even creating a symbolic link on the Primary (192.168.1.200) from /etc/pihole/gravity.db to /mnt/usbdrive/etc/pihole/gravity.db does not work yielding an error message - see screenshot.

**Screenshot:**
![image](https://user-images.githubusercontent.com/64986937/96339382-4a1fdc80-108c-11eb-8e84-f8c89c57b19c.png)

**Configuration:**
Both "Raspbian GNU/Linux 10 (buster)"
Primary Raspberry Pi 4b, Secondary Raspberry Pi Zero
Gravity Sync Version: 3.0.0
Pi-hole Versions: both 5.1.2

**Additional Context**
Is it possible to specify an alternative Primary .db location? Can that be different to the Secondary location?  Alternatively is there a workaround.

Thank you!

**Comment by vmstan** [comment]
The short answer is this is currently not supported.

However, is this will be in 3.1 because it's needed for proper Docker container support, which I'm hoping to have done this week.
