### ISSUE TITLE
v.3.1.0 aborts with Insufficent User Rights

### ISSUE THREAD

**Issue by tjharman** [vmstan/gravity-sync#108]
**Describe the Issue**
After upgrade to 3.1.0 I am unable to run gravity-sync anymore, it complains about Insufficient User Rights.

**Screenshots**

The following is output from running gravity-sync.sh on my backup pihole.
This is a brand new, fresh install, which I did because after the upgrade it was erroring (same problem) so I wanted to start fresh to check.

```
pi@piihole:~/gravity-sync$ ./gravity-sync.sh
[i] Gravity Sync 3.1.0 Executing
[✓] Importing gravity-sync.conf Settings
[✗] Evaluating Arguments ROOT
[!] Insufficent User Rights
[i] Gravity Sync ROOT Aborting (0 seconds)
pi@piihole:~/gravity-sync$ sudo bash
root@piihole:/home/pi/gravity-sync# whoami
root
```

**Configuration:**
 - OS for Primary/Secondary: Both are Debian 10.6
 - Platform for Primary/Secondary: Both are running a OpenVZ Container (Proxmox)
 - SSH Server/Client: OpenSSH
 - SSH Authentication: Keypair
 - Gravity Sync Version: 3.1.0
 - Pi-hole Versions: Pi-hole v5.1.2 Web Interface v5.1.1 FTL v5.2 

**Additional Context**
This has worked just fine prior to this version.
Both hosts have working sudo with no password as shown in the output above.

```
root@piihole:/home/pi/gravity-sync# cat gravity-sync.conf | grep -v \#

REMOTE_HOST='pi.hole'
REMOTE_USER='pi'
```

**Comment by vmstan** [comment]
What is the output of `groups pi` on that system?

**Comment by tjharman** [comment]
```
root@piihole:~# groups pi
pi : pi
```

```
root@piihole:~# cat /etc/sudoers | grep pi
pi      ALL=(ALL:ALL) NOPASSWD:ALL
```

**Comment by vmstan** [comment]
Can you add the pi user to the sudo group?

`usermod -aG sudo pi`

**Comment by tjharman** [comment]
Thanks, that's fixed it.

Bad sysadmining on my part?

**Comment by vmstan** [comment]
Who knows 🤷‍♂️ Honestly, it seems every Linux distribution and admin does things a little differently. I have a check in there to see if it's a member of the `sudo` or `wheel` group to make sure it has a reasonable chance to success, but it appears some systems work without being in those groups. I either need to rethink how I do that check, or see if it causes issues for more folks.

**Comment by tjharman** [comment]
I can only imagine - everyone does stuff differently.
Appreciate the prompt assistance, thank you, and thanks for this great project.

**Comment by Panja0** [comment]
> Can you add the pi user to the sudo group?
> 
> `usermod -aG sudo pi`

Fixed it for me as well!
3x Debian 10.6 VM's
