### ISSUE TITLE
Getting "the input device is not a TTY" error message when running in 2 containerized instances

### ISSUE THREAD

**Issue by Cartache** [vmstan/gravity-sync#109]
Getting "the input device is not a TTY" when executing script on two containerized instances.

Solution suggested:
Replace RH_EXEC="${ROCKER_BIN} exec -it ${DOCKER_CON} pihole" 
With     RH_EXEC="${ROCKER_BIN} exec ${DOCKER_CON} pihole"
in gs-core.sh file.

**Comment by DelusionalAI** [comment]
I had the same issue, with the solution suggested working to fix it.

**Comment by vmstan** [comment]
Yep, dang it. Will have 3.1.1 out shortly to address it.
