### ISSUE TITLE
'Folder gravity-sync already exists' when running installer

### ISSUE THREAD

**Issue by vmstan** [vmstan/gravity-sync#111]
I've had this question come up a couple times, so I'm creating this as a pinned Issue. 

![16466f2b5b038c35e1b200bdb15a53ac5fda8d46](https://user-images.githubusercontent.com/3002053/96733953-a41bed00-137f-11eb-9edb-fb89d7408dec.png)

If you're getting this message, it's because the Gravity Sync folder already exists where you're attempting to run the installer. If you have a deployment already, the path to upgrading is to run `./gravity-sync.sh update` from within the existing Gravity Sync folder.

![CleanShot 2020-10-21 at 09 29 09@2x](https://user-images.githubusercontent.com/3002053/96734195-e5ac9800-137f-11eb-970f-b0d5b39229d6.png)

The installer is meant for new Gravity Sync instances only.

Please feel free to comment below on this if you have any questions, even though the issue is closed.

**Comment by CrazyAngelFir3** [comment]
i have updated this from within the gravity-sync folder and the back to re-execute and it just prompts the same issue
