### ISSUE TITLE
Critical error running EXPORT command and commands from the home directory result in a error

### ISSUE THREAD

**Issue by markladage** [vmstan/gravity-sync#113]
Hello Michael,

first of all thanks for the nice work,
i'm running the 3.1 version of your script and i have two questions:

1. as you can see in the picture running the Export command on my secondary pi results in 1 critical issue. I can only guess it's referring to the fact that the folder gravity-sync already exists. If that's true i think it's not a critical issue and there is nothing to correct. If it's not referring to the folder then what else?

2. running a command from the home directory results in a error: -bash ... no such file or directory. I thought that from version 3.1 we could run the script from anywhere.

![StandbyPi](https://user-images.githubusercontent.com/57064262/96735040-6dfc5e80-13bb-11eb-8670-f6532efb026f.jpg)

Thanks.

Gr. Mark

**Comment by vmstan** [comment]
Hi Mark,

Please see #111 

You can only run `./gravity-sync.sh` commands from within the folder, but the folder can exist in other places if you're installing it with the root user.
