### ISSUE TITLE
Use incron instead of cron

### ISSUE THREAD

**Issue by mlanner** [vmstan/gravity-sync#115]
**Is your feature request related to a problem? Please describe.**
Instead of waiting on a particular time to occur, as configured through cron on a schedule, it would be nice to be able to sync changes based on events.

**Describe the solution you'd like**
Incron can act on events rather than on a schedule, like how cron works.

**Describe alternatives you've considered**
There are possibly other "sync" solutions, like Syncthing and others, but I think it would be more overhead than incron and other solutions may also not be available in upstream OS repos. 

**Additional context**
N/A

**Comment by vmstan** [comment]
The problem I see with this is generating a replication job based on any change to the database might end up generating a ton of replication events. Say you go into the interface and add a new adlist, and do a gravity update. That's a replication event. You go create a client group, that's a replication, you update the description, another replication. Each time it's putting more load on the systems. I'm not saying there isn't a use case for that, but is it necessary for Pi-hole to be that up to date where a 15 minute cycle wouldn't cover you? (Or where you couldn't manually run the replication job if it needed to happen sooner?)
