### ISSUE TITLE
service: command not found

### ISSUE THREAD

**Issue by plittlefield** [vmstan/gravity-sync#117]
The installer works fine.

The compare works fine.

The 'smart' works nearly perfect but ends with an error "service: command not found."

```
root@pihole2:~# ./gravity-sync/gravity-sync.sh smart
[i] Gravity Sync 3.1.1 Executing
[✓] Importing gravity-sync.conf Settings
[✓] Evaluating Arguments: SMART Requested
[i] Targeting root@pihole1
[✓] Validating SSH Client on pihole2 (OpenSSH)
[✓] Validating RSYNC Installed on pihole2
[✓] Validating Gravity Sync Folders on pihole2
[✓] Validating Pi-hole Configuration
[✓] Validating SQLITE Installed on pihole2
[✓] Validating Connection to pihole1
[i] Starting SMART Analysis
[✓] Analyzing gravity.db on pihole1
[✓] Analyzing gravity.db on pihole2
[!] Differenced gravity.db Detected
[✓] Analyzing custom.list on pihole1
[✓] Analyzing custom.list on pihole2
[!] Differenced custom.list Detected
[!] Replication Required
[!] Both gravity.db Have Changed
[!] Primary gravity.db Last Changed
[✓] Performing Backup of Local gravity.db
[✓] Performing Backup of Remote gravity.db
[✓] Pulling gravity.db from pihole1
[✓] Replacing gravity.db on pihole2
[✓] Validating Settings of gravity.db
[!] Both custom.list Have Changed
[!] Secondary custom.list Last Changed
[✓] Performing Backup of Remote custom.list
[✓] Performing Backup Up Local custom.list
[✓] Copying custom.list from pihole1
[✓] Pushing custom.list to pihole1
[✓] Setting Permissions on custom.list
[✓] Setting Ownership on custom.list
[i] Isolating Regeneration Pathways
[✓] Updating FTLDNS Configuration
[✓] Reloading FTLDNS Services
[i] Inverting Tachyon Pulses
[✓] Updating Remote FTLDNS Configuration
[e] Reloading Remote FTLDNS Services  [✗] /usr/local/bin/pihole: line 127: service: command not found
[✗] Reloading Remote FTLDNS Services

root@pihole2:~# which service
/usr/sbin/service
```

What have I done wrong?

Thanks,

Paully

Both pi-holes: Pi-hole v5.2 Web Interface v5.2 FTL v5.3.1

**Comment by plittlefield** [comment]
OK, I've figured out my problem and have fudged a fix... naughty but works for now.

pihole1 runs dietpi with the default ssh server of 'dropbear'.
pihole2 runs dietpi with the changed ssh server of 'ssh'.

Dropbear has extra security with shell environment variables (I think) so pihole2 is not ssh'ing in with a full environment.

To get round this issue (because you know, I can't change SSH server when I'm logged in via SSH!) on both piholes I have added a symlink to both pihole and service in /usr/sbin/

```
ln -s /usr/sbin/service /usr/bin/service
ln -s /usr/local/bin/pihole /usr/bin/pihole
```

It now runs 'gravity-sync smart' perfectly.

:-)

Paully

**Comment by plittlefield** [comment]
Ah, spoke a little too soon  :-(

It appears to complete the sync but the DNS service on pihole1 stopped.

To fix it, I just went to Settings page on the web gui and restarted the system on pihole1.

So close and yet, so far.

Paully

**Comment by vmstan** [comment]
You can specify the Pihole binary directories in your `gravity-sync.conf` if they're different from what it's looking in the defaults.

https://github.com/vmstan/gravity-sync/wiki/Hidden-Figures#pihole_bin-and-rihole_bin

**Comment by plittlefield** [comment]
Thanks. I'll try that and report back.
