### ISSUE TITLE
sync failing from password/sudo issue?

### ISSUE THREAD

**Issue by nebakanezzer** [vmstan/gravity-sync#118]
I've had pihole 1 setup for a long time. setup pihole 2 last night, added unbound, went to add gravity-sync.

everything goes well all the way until the end, and then I get this error when running ./gravity-sync.sh:

Performing Backup of Remote gravity.dbsudo: no tty present and no askpass program specified
[✗] Performing Backup of Remote gravity.db

it appears it is trying to access the primary pihole to backup the db but the sudo command is failing due to not having a password, and not being able to ask for one via tty, askpass, etc.

all the gravity install processes were ran with sudo. was this not supposed to be the case?

I am able to ssh to the primary pihole via the test command

edit

the script does not like sudo. luckily I took snapshots of both VMs. rolled back, reran without sudo, all is good now. this should probably be prominantly displayed in the install guide so other people avoid my dumb mistake

**Comment by vmstan** [comment]
https://github.com/vmstan/gravity-sync/wiki/System-Requirements
