### ISSUE TITLE
secondary lists overwrite primary

### ISSUE THREAD

**Issue by nebakanezzer** [vmstan/gravity-sync#119]
**Describe the Issue**
followed install guide step by step. ran script from secondary dns server. by design, the configuration takes place on the secondary server. when it finds differences, it copies them from the secondary to the primary. in most instances, this doesn't matter. in mine, my primary had blocklists and local dns. this was all wiped. 

only way I can see to remedy this is to start over and run the primary script on the secondary server, and secondary on primary. if this is is the only way to fix this, and the secondary will take priority when replacing lists, the naming of 'primary' and 'secondary' in the scripts should be swapped

**Screenshots**

**Configuration:**
 - OS for Primary/Secondary: debian buster
 - Platform for Primary/Secondary: debian buster
 - SSH Server/Client: mtputty
 - SSH Authentication: password
 - Gravity Sync Version: today
 - Pi-hole Versions: 5.2.1

edit

reverted the VMs and tried in reverse. it looks like script uses the file that the webui creates to backup dns entries, and does not backup cnames at all. so anything in the /etc/dnsmasq.d/05-custom.conf or /etc/dnsmasq.d/05-pihole-custom-cname.conf files are not transfered to each other. only 01-pi-hole.conf

the addiditonal blocklists also did not replicate. only the 2 defaults

**Comment by vmstan** [comment]
Correct, support for the CNAME replication is coming soon, but not in the current version.
