### ISSUE TITLE
Unable to detect Pihole is installed

### ISSUE THREAD

**Issue by mvaldes14** [vmstan/gravity-sync#121]
**Describe the Issue**
Got my primary Pihole running on top of Dietpi with openssh. The primary setup (running the script) seems to be working fine. It generates the sudoers.d/pihole file.

My secondary Pihole is running on Manjaro and while i know it's not the official supported client list it has an AUR package that is working as inteded. Now while running the secondary script everything was setup right as i can ssh from one node to the other but for some reason the `compare` is failing as it does not detect the installation over in primary.

**Secondary**
```
❯ ./gravity-sync.sh compare
[i] Gravity Sync 3.1.1 Executing
[✓] Importing gravity-sync.conf Settings
[✓] Evaluating Arguments: COMPARE Requested
[i] Targeting pi@pi
[✓] Validating SSH Client on server (OpenSSH)
[✓] Validating RSYNC Installed on server
[✓] Validating Gravity Sync Folders on server
[✗] Unable to Validate that Pi-Hole is Installed
[i] Gravity Sync COMPARE Aborting (0 seconds)
```

Checked the script and it's pointing for the binary in `/usr/local/bin/pihole` which i do have.
```
PIHOLE_BIN='/usr/local/bin/pihole'  # default Pi-hole binary directory (local)
RIHOLE_BIN='/usr/local/bin/pihole'  # default Pi-hole binary directory (remote)
```

** Primary **
```
➜  ~ ls -l /usr/local/bin/pihole
-rwxr-xr-x 1 root root 15977 Dec 12 14:38 /usr/local/bin/pihole
```

**Configuration:**
 - OS for Primary/Secondary: DietPi/Manjaro
 - Platform for Primary/Secondary: Raspberry Pi 3/Dell Mini PC
 - SSH Server/Client: OpenSSH
 - SSH Authentication: Keys
 - Gravity Sync Version: 3.1.1
 - Pi-hole Versions: 5.2.1

**Comment by vmstan** [comment]
Which server is Gravity Sync running on, the DietPi or the Manjaro?

**Comment by mvaldes14** [comment]
on my secondary manjaro machine, which in theory should be able to locate the pihole designated as primary on my dietpi and pull from there if i understood it correctly.

**Comment by vmstan** [comment]
That check is looking for the Pi-hole configuration directory, which by default is in /etc/pihole and is only really concerned with the local (secondary) machine.

Can you validate this is where it's located on the Manjaro system?

**Comment by mvaldes14** [comment]
confirmed - the aur package installs it in that location.

`ls -l /etc/pihole | wc -l
51`

**Comment by mvaldes14** [comment]
Switched the order, made the manjaro machine primary and the raspberry pi as secondary and what do you know....it works.
so i'm guessing somehow the installer on arch linux is not being detected properly.
