### ISSUE TITLE
Minor Bug

### ISSUE THREAD

**Issue by rogersa2k** [vmstan/gravity-sync#122]
**Describe the Issue**
Did the following:
`export GS_INSTALL=secondary && curl -sSL https://gravity.vmstan.com | bash`

And saw this error/warning:
`gs-config.sh: line 209: [: !=: unary operator expected`

I think you just forgot to double-quote the variable:
`if [ $SKIP_PIHOLE_DIR != "1" ]`

**Comment by vmstan** [comment]
I see that. Will fix in the next release.
