### ISSUE TITLE
sync says "No Replication Needed" but block lists not in sync

### ISSUE THREAD

**Issue by unarj** [vmstan/gravity-sync#123]
**Describe the Issue**
2 piholes, currently primary has 970,388 domains in blocklist and secondary has 970,376.  running 'gravity-sync smart' or 'gravity-sync pull' will return No Replication Required.  I noticed this before the last pihole release but not sure when it started, just noticed they were out of sync when I went to apply the update.

**Screenshots**
can be provided if it helps.

**Configuration:**
 - OS for Primary/Secondary: Raspbian GNU/Linux 10 (buster)
 - Platform for Primary/Secondary: raspi3b
 - SSH Server/Client: OpenBSD SSH
 - SSH Authentication: pwd
 - Gravity Sync Version: Gravity Sync 3.1.1
 - Pi-hole Versions: 5.2.1

**Additional Context**
Add any other context about the problem here. If you have any advanced flags set in your `gravity-sync.conf` please list them here.

```
pi@pihole2:~/gravity-sync $ ./gravity-sync.sh logs
[i] Gravity Sync> 3.1.1 Executing
[✓] Importing gravity-sync.conf Settings
[✓] Evaluating Arguments: LOGS Requested
[i] Tailing /home/pi/gravity-sync/gravity-sync.log
========================================================
Recent Complete SMART Executions
Sun 6 Dec 04:31:37 EST 2020 [SMART]
Sun 13 Dec 03:31:53 EST 2020 [SMART]
Sun 13 Dec 04:31:50 EST 2020 [SMART]
Wed 16 Dec 18:01:41 EST 2020 [SMART]
Thu 17 Dec 15:01:00 EST 2020 [SMART]
Sun 20 Dec 04:01:08 EST 2020 [SMART]
Sun 20 Dec 04:31:27 EST 2020 [SMART]
Recent Complete PULL Executions
Recent Complete PUSH Executions
Recent Complete BACKUP Executions
Recent Complete RESTORE Executions
========================================================
[i] Gravity Sync LOGS Aborting (0 seconds)
```

**Comment by unarj** [comment]
refreshed the the adlist sources (src 'https://v.firebog.net/hosts/lists.php?type=nocross') and ran 'pihole -g' on the primary, this triggered a sync.  not sure yet what causes the sync to fail but perhaps the adlist changing.

**Comment by vmstan** [comment]
Yeah not sure what would have happened there, it's literally just looking for any differential in a hash of the databases to decide if it needs to replicate.

**Comment by unarj** [comment]
this wasn't the first time it happened, figured after 4-5 times I should report it.

I occasionally get an email from cron saying that the database was locked, assuming this kept the sync from happening.  is it possible that the the sync was marked as completed even though the DB lock?

**Comment by vmstan** [comment]
Possible. Can you update to the latest version and see if that helps? I made a few changes to the syncing engine, not sure if will help specifically but gives me a common place to troubleshoot.
