### ISSUE TITLE
Backup size above 10GB

### ISSUE THREAD

**Issue by soonic6** [vmstan/gravity-sync#124]
**Describe the Issue**
The Backup folder increases above 10GB on secondary pihole

**Screenshots**
https://pasteboard.co/JHrSGkF.png

**Configuration:**
 - OS for Primary/Secondary: Raspbian Linux 10/Raspbian Linux 10
 - Platform for Primary/Secondary: Raspberry Pi 3b / Raspberry Zero W
 - SSH Server/Client: SSH/SSH
 - SSH Authentication: password
 - Gravity Sync Version: 3.1.1
 - Pi-hole Versions: 5.2.2

**Additional Context**
My Pi Zero got out of space. Does gravity-sync delete old backups on its own? Depend on size, or age?

**Comment by vmstan** [comment]
https://github.com/vmstan/gravity-sync/wiki/Backup-&-Restore#backup-function

How often are you making changes to the primary? It looks awfully busy.

**Comment by vmstan** [comment]
Try this.
- Delete the `gravity-sync.md5` file in the main directory of the script.
- Delete all of the files in the `backup` folder.
- Run `./gravity-sync.sh pull` to force a new sync from the primary to the secondary.

**Comment by soonic6** [comment]
i am new to pihole, so i do some changes per day. i will decrease the days till the backups get deleted and delete the old backups by hand. I never thought that the backup files get so "big".
thank you and a happy new year.
