### ISSUE TITLE
Wrong variable used in gs-core.sh

### ISSUE THREAD

**Issue by Shuasha511** [vmstan/gravity-sync#125]
**Describe the Issue**
gs-core.sh, line 62 is supposed to be for the remote docker, but uses the docker location variable for the local docker.  Simple one letter fix.

    elif [ "$RH_IN_TYPE" == "docker" ]
    then
        RH_EXEC="${ROCKER_BIN} exec ${**DOCKER_CON**} pihole"
    fi

**Comment by vmstan** [comment]
Thanks, will fix in 3.2.
