### ISSUE TITLE
Add support for Docker on Synology

### ISSUE THREAD

**Issue by Shuasha511** [vmstan/gravity-sync#126]
I spent some time making it work with Synology DSM 6.2.3 Update 3 and can send the changes I had to make for it to work as the primary with gravity-sync running from an Ubuntu secondary.  

Main differences:
Synology doesn't have an installation package for Git or crontab, although it does have it's own cron.  Git can be installed as an unofficial package, but as a primary it's not really needed.  I modified the install script to bypass cron, but i'm not really sure it needs to be run on Synology, a few manual steps would likely work to get SSH working with a private key.

rsync can't run sudo as a command on Synology, however their customized version of rsync has a flag "--syno-pseudo-root" that can be added to the RSYNC_REPATH variable.  This negates the need for the NOPASSWORD config in sudoers.d.

**Comment by vmstan** [comment]
The automated installer script is really designed to work on the most common or easily supportable platforms. While Synology will works, it would be a lot of effort to get all the edges off, especially when I don't have one to personally test with. That's what I have the manual install instructions up. But like you said, the git requirements, etc are not really necessary for primary, so I could easily exempt the primary from those. 

I could probably work in a custom variable for the additional rsync command flag.

**Comment by Shuasha511** [comment]
The only other changes from my diffs are:
Synology wants the file owners to be 999:999 and ROCKER_BIN to be /usr/local/bin/docker.  Sudo is required for any commands around the docker executable.  The NOPASSWORD stuff would be required in that case.

If you decide to add this, I would be happy to test.

**Comment by nh-mike** [comment]
Hi @Shuasha511 

I have created a Docker image for my own use on Ubuntu Server 20.04, and this may suit your requirements. Feel free to have a go and see whether it would suit.

Take note that it is a separate project in a configuration unsupported by @vmstan but hopefully it will help get this project out on to even more machines.

Instructions on how to install from Docker Hub are included however do not cover Synology, but I would be quite happy to work with you on getting this working there.

https://github.com/nh-mike/gravity-sync-docker

**Comment by vmstan** [comment]
![](https://media.giphy.com/media/U4RBc8AOCaDxPPExaH/giphy.gif)
