### ISSUE TITLE
No Such File or Directory

### ISSUE THREAD

**Issue by chris0200** [vmstan/gravity-sync#131]
Probably not a bug, but help required please.

Running the Latest Version of Pihole and installation of Gravity Sync seemed to work fine without errors on both primary and secondary PI's

Trying to run .gravity-sync.sh compare and receive 'No 
such file or directory'.

Any ideas appreciated.

**Comment by vmstan** [comment]
Can you include a screenshot of what is running, and also the output of `./gravity-sync.sh info`

**Comment by chris0200** [comment]
Thanks for getting back to me Michael.

pi@raspberrypi:~ $ ./gravity-sync.sh info
-bash: ./gravity-sync.sh: No such file or directory

This pi is only running Pihole and Unifi Controller nothing else at this time.

Chris

**Comment by vmstan** [comment]
Are you in the Gravity Sync folder when executing ./gravity-sync.sh?

**Comment by vmstan** [comment]
`sudo: docker: command not found`

Are you running Pi-hole in a Docker container?

**Comment by chris0200** [comment]
Not in docker.

**Comment by vmstan** [comment]
Now that we're running in the right folder, can you paste the output of `./gravity-sync info` here so I can see how your configuration file is setup?

**Comment by chris0200** [comment]
Apologies but I will not be able to try and resolve this at the moment, been called away. Thanks for your support to date.
