### ISSUE TITLE
cannot open "~/docker/etc-pihole/gravity.db.backup"

### ISSUE THREAD

**Issue by daviesap** [vmstan/gravity-sync#134]
[gravity-sync-info.txt](https://github.com/vmstan/gravity-sync/files/5825980/gravity-sync-info.txt)

[gravity-sync-conf.txt](https://github.com/vmstan/gravity-sync/files/5825985/gravity-sync-conf.txt)

_Unless you are unable to update, please make sure you're running the latest versions of Pi-hole and Gravity Sync before filing a ticket. Also please include the output of `./gravity-sync.sh info` in your report, as a text-file or screenshot attachment._

**Issue Description**
Hello - thanks for all your work on this!

Running ./gravity-sync.sh smart gives the following output - and fails with Error: cannot open "~/docker/etc-pihole/gravity.db.backup"

[∞] Gravity Sync 3.2.4 Executing
[✓] Importing gravity-sync.conf Settings
[✓] Evaluating Arguments: SMART Requested
[i] Targeting pi@10.0.15.107. 
[✓] Validating SSH Client on flair-pi-sa (OpenSSH)
[✓] Validating RSYNC Installed on flair-pi-sa
[✓] Validating Gravity Sync Folders on flair-pi-sa
[✓] Validating Pi-hole Configuration
[✓] Validating DNSMASQ Configuration
[✓] Validating SQLITE Installed on flair-pi-sa
[e] Validating Connection to 10.0.15.107bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[✓] Validating Connection to 10.0.15.107
[i] Starting SMART Analysis
[e] Analyzing gravity.db on 10.0.15.107bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[✓] Analyzing gravity.db on 10.0.15.107
[✓] Analyzing gravity.db on flair-pi-sa
[!] Differenced gravity.db Detected
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[e] Analyzing custom.list on 10.0.15.107bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[✓] Analyzing custom.list on 10.0.15.107
[✓] Analyzing custom.list on flair-pi-sa
[!] Differenced custom.list Detected
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[i] No 05-pihole-custom-cname.conf Detected on flair-pi-sa
[!] Replication Required
[!] Both gravity.db Have Changed
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[!] Secondary gravity.db Last Changed
[e] Performing Backup of Remote gravity.dbbash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Error: cannot open "~/docker/etc-pihole/gravity.db.backup"
[✗] Performing Backup of Remote gravity.db

SSH'ing from the backup PI Hole server into the main / remote Pi Hole server, I can see the ~/docker/etc-pihole folder, but gravity.db.backup file does not exist.  See below:

pi@flair-pi-sa:~/gravity-sync $ ssh pi@10.0.15.107
Linux flair-pi-gb 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l
pi@flair-pi-gb:~ $ cd ~/docker/etc-pihole/                 
pi@flair-pi-gb:~/docker/etc-pihole $ ls
GitHubVersions  adlists.list  custom.list  dns-servers.conf  gravity.db  list.1.raw.githubusercontent.com.domains  local.list  localbranches  localversions  migration_backup  pihole-FTL.conf  pihole-FTL.db  setupVars.conf  setupVars.conf.update.bak
pi@flair-pi-gb:~/docker/etc-pihole $ 

**Configuration Details**

Flair-pi-gb.lan - Main Pi Hole - 10.0.15.107 - In Docker Container
Flair-pi-sa.lan  - Backup Pi Hole - 10.0.15.153 - NOT in docker container

Running gravity-sync.sh on Flair-pi-sa.lan

I changed the Locale to Europe/London on the docker install (backup) of Pi Hole when installing it - can't see where Locale is set on main install of Pi Hole.  Not sure if that could be the issue?

**Comment by vmstan** [comment]
Instead of using ~ in the config can you include the full path to the folders in your config file?

**Comment by daviesap** [comment]
Will do - though I have tried that and got the same result.

It seems as if gravity.db.backup does not exist?  Will let you know once I have tried the full path

Thanks,
Andrew

**Comment by daviesap** [comment]
That fixed it!  Removing the ~ and putting the full path.  Apologies, I thought I had tried that.

Thanks again
Andrew
