### ISSUE TITLE
Possibility to have user-defined path for cron log file in conf file

### ISSUE THREAD

**Issue by xorguy** [vmstan/gravity-sync#15]
For people that do not require persistent log file across reboots and/or to prevent writes to SD cards it can be useful to have redirected to a user-defined location.

**Comment by vmstan** [comment]
![SS-2020-05-27-287](https://user-images.githubusercontent.com/3002053/83045515-4ae7a180-a00b-11ea-9d9d-def02e3a7498.png)

Coming in 1.4.1 😉

**Comment by vmstan** [comment]
![CleanShot 2020-05-27 at 11 22 23@2x](https://user-images.githubusercontent.com/3002053/83046240-5a1b1f00-a00c-11ea-9fad-ff6edb3baebc.png)

**Comment by vmstan** [comment]
[https://github.com/vmstan/gravity-sync/releases/tag/v1.4.1](https://github.com/vmstan/gravity-sync/releases/tag/v1.4.1)

The .example file should have the new options ready to drop into your existing configuration.

```
# LOG_PATH=''
# SYNCING_LOG=''
# CRONJOB_LOG=''
```

If you're changing the name of the sync or cron log files I would suggest also assigning a new path outside of the gravity-sync folder to make upgrading easier later, as if you're updating with the built in updater other file names will be overwritten.
