### ISSUE TITLE
"Use Advanced Installation Options" answer is inverted

### ISSUE THREAD

**Issue by thoerup** [vmstan/gravity-sync#163]
**Issue Description**
When configuring Gravity Sync the prompt "Use Advanced Installation Options?" reacts opposite as expected.
If I type "Y" I get basic installation and if I type "N" I get Advanced Configuration

**Configuration Details**

**Comment by vmstan** [comment]
🤦 thanks

**Comment by thoerup** [comment]
Thought I was loosing my mind for a while there 😀
Awesome project!
