### ISSUE TITLE
gs-validate too restrictive on docker check

### ISSUE THREAD

**Issue by thesnowdog** [vmstan/gravity-sync#168]
**Issue Description**
I am running the docker image cbcrowe/pihole-unbound and my container name is pihole. When validating that pihole runs in docker, gs-validate.sh seems to only look for “pihole/pihole” in the docker ps output. When I manually change that part of the script to “cbcrowe/pihole-unbound”, then sync works. Consider looking only for “pihole” when grepping the docker ps output.

**Comment by vmstan** [comment]
So currently I have only been supporting the official Pi-hole container image. When I initially released it I didn't want to get bogged down with troubleshooting more than that. I still don't think I want this to be something I fully support yet, but I have added a variable called `CONTAIMAGE` which can be added in your `gravity-sync.conf` file.

`CONTAIMAGE='cbcrowe/pihole-unbound'`

Let me know if this works.

**Comment by thesnowdog** [comment]
Works! Thanks!
