### ISSUE TITLE
"Database disk image is malformed"

### ISSUE THREAD

**Issue by vmstan** [vmstan/gravity-sync#172]
I seem to be having the same problem on my Pi's. As far as I can tell it seems to be related to the Whitelist in my case. I've tried starting with a new database on both. Syncs runs fine including any Whitelist entries when there's a Gravity update. If I then make a change to the whitelist on the primary Pi the change isn't detected until the next time there's a Gravity update. Gravity-sync then does it's thing and the Whitelist on my second Pi stops showing (just sits at Loading) and I get "Database disk image is malformed".

_Originally posted by @Yaff1e in https://github.com/vmstan/gravity-sync/issues/96#issuecomment-783760245_

**Comment by vmstan** [comment]
What version of Gravity Sync is running @yaff1e?

**Comment by Yaff1e** [comment]
3.3.2. I can try and grab some logs if it's any help but it probably won't be for a couple of days.

**Comment by kormoan** [comment]
Same Problem here.

Fresh install, new SD Card

After gravitysync smart a defect gravitysync.db

`$query = $db->query('SELECT * FROM `domainlist'.$limit);`

```
pihole-ftl.log
[2021-03-13 13:13:01.922 2276M] Blocking status is enabled
[2021-03-13 13:13:02.070 2276/T2280] SQLite3 message: database corruption at line 66907 of [a26b6597e3] (11)
[2021-03-13 13:13:02.070 2276/T2280] SQLite3 message: statement aborts at 6: [SELECT COUNT(DISTINCT domain) FROM vw_regex_blacklist] database disk image is malformed (11)
[2021-03-13 13:13:02.070 2276/T2280] gravityDB_count(SELECT COUNT(DISTINCT domain) FROM vw_regex_blacklist) - SQL error step database disk image is malformed
[2021-03-13 13:13:02.070 2276/T2280] WARN: Database query failed, assuming there are no blacklist regex entries
[2021-03-13 13:13:02.073 2276/T2280] SQLite3 message: database corruption at line 66907 of [a26b6597e3] (11)
[2021-03-13 13:13:02.073 2276/T2280] SQLite3 message: statement aborts at 6: [SELECT COUNT(DISTINCT domain) FROM vw_regex_whitelist] database disk image is malformed (11)
[2021-03-13 13:13:02.073 2276/T2280] gravityDB_count(SELECT COUNT(DISTINCT domain) FROM vw_regex_whitelist) - SQL error step database disk image is malformed
[2021-03-13 13:13:02.073 2276/T2280] WARN: Database query failed, assuming there are no whitelist regex entries
[2021-03-13 13:13:02.073 2276/T2280] Compiled 0 whitelist and 0 blacklist regex filters for 2 clients in 4.1 msec
[2021-03-13 16:59:00.111 2276/T2280] Notice: Database size is 119.29 MB, deleted 1 rows

```

```
lighttpd error.log
2021-03-13 13:16:17: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Warning:  SQLite3::query(): Unable to execute statement: database disk image is malformed in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 465
2021-03-13 13:16:27: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Warning:  SQLite3::query(): Unable to execute statement: database disk image is malformed in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 465
2021-03-13 13:17:19: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Warning:  SQLite3::query(): Unable to execute statement: database disk image is malformed in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 465
2021-03-13 13:19:35: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Warning:  SQLite3::query(): Unable to execute statement: database disk image is malformed in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 465
2021-03-13 13:20:43: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Warning:  SQLite3::query(): Unable to execute statement: database disk image is malformed in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 465
2021-03-13 17:03:35: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Warning:  SQLite3::query(): Unable to execute statement: database disk image is malformed in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 465
```
`

**Comment by z3razerviper** [comment]
I just started having this issue and I noticed my sdcard was full. Once I cleared out the gravity sync backup folder the issue went away....

**Comment by z3razerviper** [comment]
This is happening to me as well I thought it was due to the backups filling the disk up and that does not seem to be the case

**Comment by vmstan** [comment]
@z3razerviper what does the disk hardware look like? Are you running off a Raspberry Pi off SD cards by chance?

I'm starting to wonder if there is a relationship to the media type with this issue.

**Comment by z3razerviper** [comment]
Yes I am.

**Comment by vmstan** [comment]
Here's my theory at the moment. The original GS script worked as such (for pulls):

1. Tell the primary to make a copy of the running database using the filesystem `cp` command.
2. Rsync the copy to a temporary directory on the secondary.
3. Overwrite the running copy with the version from the temporary directory.

Starting in 2.1.5, because there was some concern that this would corrupt the primary database, I changed it:

1. Tell the primary copy to create a SQLITE3 backup of the running database.
2. Rsync the copy to the backup to a temporary directory on the secondary.
3. Overwrite the running copy with the backup from the temporary directory.

I'm wondering if the SQLITE3 backup operation on the SD cards is what is failing.

**Comment by Yaff1e** [comment]
> @z3razerviper what does the disk hardware look like? Are you running off a Raspberry Pi off SD cards by chance?
> 
> I'm starting to wonder if there is a relationship to the media type with this issue.

My primary is a Pi1 with SD and my secondary is a Pi2 with SD

**Comment by z3razerviper** [comment]
My primary pi is a Pi4 4GB and my secondary is a 3B+ also note I do not sync i have the secondary do a pull.

**Comment by vmstan** [comment]
The actual process is still the same. Sync just decides to pull or push each part. Pull just pulls.

**Comment by z3razerviper** [comment]
Hello vmstan what I can I do to assist in finding the issue?

**Comment by bakerboy448** [comment]
[This post ](https://github.com/vmstan/gravity-sync/issues/172#issuecomment-798612418)seems to have the most troubleshooting

Given the size difference, it seems like the database is incomplete...either it's being grabbed with transactions being incomplete and not committed or the backup is taking longer than the timeout and only a partial backup is being used. 

Unlikely to be the SD Card as there'd be a lot more issues and noise for SQLlite on an sd card.

Anyway several different angles to test and figure out.

**Comment by kormoan** [comment]
Some more Testing.

An SSD per USB to Sata Adapter runs very good.

Sqlite3 backup finished in nearly 1 minute.

Another idea is to overclock the sc card reader.

dtoverlay=sdhost,overclock_50=100 in boot.txt speeds up the card reader. But you need a fast sc card.

SanDisk Extreme or Samsung Evo+

Maybe a hash from backup database compared to the original database is also possible.

**Comment by z3razerviper** [comment]
Ok after days of watching it I think i found a pattern. I set my primary pihole to update every morning at around 5am. After that update when the secondary pulls I run into this problem However if I manually update the primary or make a change  that would prompt another pull on the secondary everthing pulls correctly and the malformed db issue goes away.....

**Comment by kormoan** [comment]
Some more testing.

Rsync of of database works now with SSD on primary pihole. File size and hash are the same on both piholes. BUT Blacklist and whitelist seem to be empty. The pihole page says "reloading". Stoping pihole-ftl on secondary pihole and manually copy the gravity.db from primary works. Every list gets shown.

**Comment by kormoan** [comment]
Next Test.

Increasing the timeout in gs_backup.sh from 60 to 120 did it for me...

**Comment by vmstan** [comment]
This actually makes a lot of sense, in a weird way. I think I will make this user adjustable in the config instead of hard coding to 60. It was much lower and got raised for other reasons previously.

**Comment by vmstan** [comment]
3.4.1 has been published with this change.

Documented at https://github.com/vmstan/gravity-sync/wiki/Troubleshooting

**Comment by kormoan** [comment]
I think the backup time and therefor the timeout depends on how tall the garvity.db is. Mine is nearly 1,5 GB ;-). The avarage database size should be much smaller.

Which size has the database you tested with your script?

**Comment by vmstan** [comment]
Yeah mine is nowhere near that big.

**Comment by vmstan** [comment]
> Why is the md5_recheck ok althought the file sizes are different?

The check is against the backup copy of the database, not the original. I had to come up with a way to make sure it wasn't triggering resync every time but the md5 of the backup will be different than the md5 of the original, but when it's restored to the secondary it'll be the same as the backup.

I guess I need a better way to identify on the replicated copy if it's healthy once it's been replicated. It would help if I had a malformed copy to play with.

**Comment by z3razerviper** [comment]
I installed the update last night and my auto update this morning still caused the issue. So its not fixed.

**Comment by vmstan** [comment]
> I installed the update last night and my auto update this morning still caused the issue. So its not fixed.

Did you raise your `BACKUP_TIMEOUT` value?

**Comment by vmstan** [comment]
I have added a database integrity check to the backup step that will ship in 3.4.2.

![CleanShot 2021-04-06 at 12 43 02@2x](https://user-images.githubusercontent.com/3002053/113755333-d1621a80-96d5-11eb-9c85-659aee07cacd.png)

**Comment by vmstan** [comment]
3.4.2 is live.

**Comment by kormoan** [comment]
Here you can test...

https://drive.google.com/file/d/1k1Bh5MVdxdNQgSnQxwb3nhEer_OWzpx7/view?usp=sharing

**Comment by vmstan** [comment]
How do you even get a database this big? Do you subscribe to every blocklist on the planet?

And this file does fail my integrity check during replication, so it would at least stop the replication (after 3.4.2) from happening in the event the backup doesn't complete.

**Comment by vmstan** [comment]
https://github.com/vmstan/gravity-sync/wiki/System-Requirements#storage-performance

I outlined some further storage requirements on the system requirements page.

**Comment by z3razerviper** [comment]
After raising the BACKUP_TIMEOUT to 200 I have had two days of no issues.

**Comment by bakerboy448** [comment]
would it be prudent to detect the size of the database and extend the timeout with a case in addition to a user configurable value?

**Comment by vmstan** [comment]
It's not strictly related to size though, the CPU and storage are going to play a big part.

**Comment by kormoan** [comment]
@vmstan  hunter and gatherer...

I use the all list from here:

 https://v.firebog.net/hosts/lists.php

and a bunch from here:

https://discourse.pi-hole.net/t/blocklisten-wer-hat-mehr/42498

**Comment by z3razerviper** [comment]
Ok after 2 days of testing the i can say that raising the BACKUP_TIMEOUT seems to have worked.
