### ISSUE TITLE
Doesnt detect docker install

### ISSUE THREAD

**Issue by PartTimeJS** [vmstan/gravity-sync#176]
**Issue Description**

When following the instructions, the script does not detect the docker install. The instructions aren't very clear on if there is anything additional to do for installing when running pihole in docker and may be missing a few details?

**Configuration Details**

**Comment by nh-mike** [comment]
Hi PartTimeJS,

I have been running it with docker for quite some time with no problems.

Please supply the commands you've run, the output you get when running these commands, and any answers you've given during the interactive setup, otherwise troubleshooting will be impossible.

Cheers.

**Comment by pochacho99** [comment]
I am having the same problem, secondary Pihole is a docker container in Synology. I enter "export GS_INSTALL=secondary && curl -sSL https://gravity.vmstan.com | bash" via SSH into the Synology and the reply is:

Gravity Sync by @vmstan
https://github.com/vmstan/gravity-sync
========================================================
[✓] Checking Short Range Sensors
[i] Validating System Authorization
[✓] Sudo Utility Detected
Password:
[✓] Current User (abc123) Has SUDO Powers
[i] Scanning for Required Components
[✓] OpenSSH Binaries Detected
[✓] RSYNC Binaries Detected
[✓] SUDO Binaries Detected
[✗] CRONTAB Binaries Not Installed
[✓] SQLITE3 Binaries Detected
[✗] GIT Binaries Not Installed
[i] Performing Warp Core Diagnostics
[!] No Local Pi-hole Install Detected
[✓] Docker Binaries Detected

**Comment by nh-mike** [comment]
Hi @pochacho99 
Can you please start a new thread in Discussions?
without knowing anything about your setup I cannot say what the problem may be, but it would be worth addressing as it's own problem.

Can you also please provide some details on your operating environment (i.e. is your 2nd pihole a local install or a docker image? If a docker image, are you using the official pihole/pihole or something else?)

Look forward to helping in a discussions thread.

**Comment by pochacho99** [comment]
I think i found the cause, i am not using the official docker image, so that's probably why the script can't detect the pihole docker install. I am using the cbcrowe/pihole-unbound image.

**Comment by vmstan** [comment]
That is correct. The installer validates you're using the official image.

**Comment by PartTimeJS** [comment]
> 
> 
> That is correct. The installer validates you're using the official image.

I am using the official image.

**Comment by vmstan** [comment]
I would suggest using the alternative install method if you're sure you meet all the install requirements.

```
git clone https://github.com/vmstan/gravity-sync.git
```

**Comment by talondnb** [comment]
> I think i found the cause, i am not using the official docker image, so that's probably why the script can't detect the pihole docker install. I am using the cbcrowe/pihole-unbound image.

Have you done anything to overcome this? I'm using the same unbound image, would prefer not to have to reconfigure everything..

**Comment by pochacho99** [comment]
I gave up, I just copy the gravity.db manually from the primary to the secondary whenever I make any changes and run pihole restart dns on the secondary

**Comment by talondnb** [comment]
I managed to get it all going this morning after I posted the last reply. Pretty straight forward, if you're still interested.

**Comment by pochacho99** [comment]
Yep definitely interested if you wouldn't mind sharing. My primary pihole is a docker and my secondary is a physical.

**Comment by talondnb** [comment]
Ok i'll try break it down simply but i'm using both docker installs so your milage may vary slightly with your physical host..

- obviously make sure you have all the required packages installed first
- set your intended users on each host to allow sudo with no password ('sudo visudo' and add username     ALL=(ALL) NOPASSWD:ALL to the end of the file
- run 'git clone https://github.com/vmstan/gravity-sync.git' installer to your **Secondary** pihole, cd to the folder and run through the wizard to generate the gravity-sync.conf file into the settings/ folder (ensure your folder paths are spot on; ~/pihole/etc-pihole doesn't work, you have to use full path)
- after the script has run, modify settings/gravity-sync.conf and uncomment/update the CONTAIMAGE line to say CONTAIMAGE='cbcrowe/pihole-unbound' (make sure you remove trailing comment)
- try to run ./gravity-sync.sh compare and determine if the setup is working as expected
- if all is OK, run ./gravity-sync.sh automate to add a cron job onto your secondary host, verify with crontab -l after this has run
- final check is to make a change onto your primary pihole UI (e.g. add a test DNS record) and verify the sync occurs after your timeframe configured in the prior step

**Comment by pochacho99** [comment]
Thanks for the instructions, I'll try it out!
