### ISSUE TITLE
Failed automated sync corrupts gravity db on primary host, corruption later replicates to the secondary host

### ISSUE THREAD

**Issue by rinchik** [vmstan/gravity-sync#191]
**Issue Description**

1. Pi-hole stops blocking (gravity db/table with domains doesn't exits)

2. When trying to run `phihole -g` on primary host getting this error:

```bash

  [i] Neutrino emissions detected...
  [✗] Pulling blocklist source list into range
  [i] No source list found, or it is empty

  [i] Building tree...
  [✗] Unable to build gravity tree in /etc/pihole/gravity_temp.db
  Error: no such table: main.gravity
Error: database disk image is malformed
Error: database disk image is malformed
  [i] Number of gravity domains:  ( unique domains)
Error: near ")": syntax error
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 1
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled

```

`./gravity-sync.sh cron` logs:

```bash
[✓] Validating Pi-hole Configuration
[✓] Validating SQLITE Installed on pi-hole--secondary
[✓] Validating Connection to x.x.0.x
[i] Starting SMART Analysis
[✓] Analyzing gravity.db on x.x.0.x
[✓] Analyzing gravity.db on pi-hole--secondary
[!] Differenced gravity.db Detected
[✓] Analyzing custom.list on x.x.0.x
[✓] Analyzing custom.list on pi-hole--secondary
[!] Replication Required
[✓] Performing Backup of Local gravity.db
[✓] Performing Backup of Remote gravity.db
[✗] Pulling gravity.db from x.x.0.x
========================================================
[∞] Gravity Sync CRON Aborting (0 seconds)
```

**Configuration Details**

+ Sync version: 3.3.2

+ pi-hole version is the same on 2 hosts: Pi-hole v5.2.4 Web Interface v5.4 FTL v5.7

+ 2 raspberry-pis (one primary, one secondary)

+  on the same local network

+ gravity db size: 326M

**Comment by rinchik** [comment]
Temporary workaround (fix): run `pihole -g -r` on primary host (do NOT touch secondary), remove cron job on secondary and run syncs manually when needed

**Comment by vmstan** [comment]
Hi @rinchik, can you update to the latest code and let me know if the issue persists?

https://github.com/vmstan/gravity-sync/wiki/Updating

**Comment by rinchik** [comment]
@vmstan will do! Looks like you changed/added timeouts? 🤞 it will help. I was thinking it might be a race condition of sort (sync/backup and happens on locked table/db?). 

Also maybe related, from sync automation docs:  `Select the frequency per hour`, I imagine, given relatively large gravity db size, hourly sync will stress pi's system/SD card a lot causing side-effects, shortening SD life. I will make it daily for now and will keep an eye on it

**Comment by vmstan** [comment]
Yeah when I started out the script was simple enough and low impact enough that running it all the time didn't seem like a big deal. The more checks and verifications that get put in place to prevent people from breaking things, the more impactful it becomes.

I personally make maybe one or two changes to my Pi-hole settings a week, sometimes not at all (minus testing of the actual script) -- and when I make any huge changes like adding a new adlist I end up running it manually just to make sure there wasn't an issue.

**Comment by rinchik** [comment]
Somewhat related proposal, wouldn't it be better for the sync to be initiated on primary and not on secondary? Meaning if there were something similar to "push" then there wouldn't be a need for `cron` job.

e.g:

on primary there can be a background "job" that checks for modified gravity.db, can be as simple as `while(true) {find . -mtime -1 {check if it's gravity db, initiate sync if true} sleep(1m)}`, this way system will become smarter and will be producing an output (sync) based on the input, and only when needed which will eliminate unnecessary pi's system stress
