### ISSUE TITLE
Enable it to work with DHCP enabled

### ISSUE THREAD

**Issue by staticdev** [vmstan/gravity-sync#194]
I would really like to use this project, but my router does not allow me to specify a DNS server. The workaround it to disable DHCP and use it on Pi-Hole. I saw on the documentation that one limitation is to sync DHCP, but could it somehow work with Pi-Hole as DHCP server? It would be great!

**Comment by vmstan** [comment]
You can still use it with Pi-hole as the DHCP server, it's just that the settings don't replicate.

**Comment by staticdev** [comment]
Sorry for that @vmstan.. I've seen a [video](https://www.youtube.com/watch?v=IFVYe3riDRA) that tells you can't.
