### ISSUE TITLE
Fails at  Performing Backup of Remote gravity.db

### ISSUE THREAD

**Issue by rahuldas14** [vmstan/gravity-sync#195]
I have two pi-holes. The secondary pi-hole has never been able to sync itself with the primary one. When I try to sync it, I get the following

`
pi@raspberrypi:~ $  /home/pi/gravity-sync/gravity-sync.sh smart

[∞] Gravity Sync 3.3.2 Executing
[✓] Importing gravity-sync.conf Settings
[✓] Evaluating Arguments: SMART Requested
[i] Targeting pi@x.x.x.x
[✓] Validating SSH Client on raspberrypi (OpenSSH)
[✓] Validating RSYNC Installed on raspberrypi
[✓] Validating Gravity Sync Folders on raspberrypi
[✓] Validating Pi-hole Configuration
[✓] Validating SQLITE Installed on raspberrypi
[✓] Validating Connection to x.x.x.x
[i] Starting SMART Analysis
[✓] Analyzing gravity.db on x.x.x.x
[✓] Analyzing gravity.db on raspberrypi
[!] Differenced gravity.db Detected
[✓] Analyzing custom.list on x.x.x.x
[✓] Analyzing custom.list on raspberrypi
[!] Differenced custom.list Detected
[!] Replication Required
[!] Both gravity.db Have Changed
[!] Primary gravity.db Last Changed
[✓] Performing Backup of Local gravity.db
[✗] Performing Backup of Remote gravity.db
`

It always fails at this point.

**Comment by Keridos** [comment]
For me it fails at the point after that which would be the integrity check.

**Comment by vmstan** [comment]
Hi @rahuldas14, sorry for the lack of reply, is this still an issue? Have you been able to upgrade to 3.4.4 and see if the issue persists?

**Comment by spacewrangler** [comment]
I have the same issue and am running version 3.4.4. However, manually running `ssh -p 22 -i /home/pi/.ssh/id_rsa -o StrictHostKeyChecking=no pi@<x.x.x.x> 'sudo sqlite3 "/etc/pihole/gravity.db" ".backup /etc/pihole/gravity-backup-foo.db"'` from the secondary pihole succeeds.

**Comment by spacewrangler** [comment]
Debugging a bit more this was a timeout issue. So I increased `BACKUP_TIMEOUT` to `360` in `settings/gravity-sync.conf` and it succeeded.

**Comment by rahuldas14** [comment]
I increased the BACKUP_TIMEOUT to 600 in  gravity-sync.conf. This resolved the issue.
