### ISSUE TITLE
[✗] Reloading secondary FTLDNS services

### ISSUE THREAD

**Issue by nini57** [vmstan/gravity-sync#196]
**Issue Description**
hello,
when I want restore a backup or sync my pihole I've this error [✗] Reloading secondary FTLDNS services

**Configuration Details**
primary pi-hole:
Pi 4 4GO. just pi-hole installed
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8 (Latest: v5.8)

secondary pi-hole:
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  Current FTL version is v5.8.
VM Debian pi-hole, apache and zoneminder is installed

**Comment by nh-mike** [comment]
Hi @nini57 ,

I am currently working through the same issue in [another issue](https://github.com/vmstan/gravity-sync/issues/193). If you'd like to look through that (at my most recent comment), it may be of value to you.

**Comment by nini57** [comment]
> Hi @nini57 ,
> 
> I am currently working through the same issue in [another issue](https://github.com/vmstan/gravity-sync/issues/193). If you'd like to look through that (at my most recent comment), it may be of value to you.

Thank's a lot
