### ISSUE TITLE
Care less about folder location

### ISSUE THREAD

**Issue by vmstan** [vmstan/gravity-sync#2]
Undo any links that require the script to be executed from a specific location

**Comment by vmstan** [comment]
- 1.4 added ability to customize SSH key file
- 1.4.1 added ability to customize log folder location

**Comment by Mbarmem** [comment]
SSH key file 'SSH_PKIF' is not being used in the script?

`${SSHPASSWORD} rsync -e "ssh -p ${SSH_PORT}" ${REMOTE_USER}@${REMOTE_HOST}:${PIHOLE_DIR}/${GRAVITY_FI} $HOME/${LOCAL_FOLDR}/${BACKUP_FOLD}/${GRAVITY_FI}.pull >/dev/null 2>&1`

**Comment by vmstan** [comment]
It is, in the generation of the key, didn't make it all the way to adding it into the actual SSH commands. Hold tight...

**Comment by vmstan** [comment]
[https://github.com/vmstan/gravity-sync/releases/tag/v1.4.3](https://github.com/vmstan/gravity-sync/releases/tag/v1.4.3)

Should be properly utilized now.
