### ISSUE TITLE
Add timestamps to logs

### ISSUE THREAD

**Issue by xorguy** [vmstan/gravity-sync#20]
It can be useful to add timestamps for each line on logs so user can know exactly when the process have run.

Regards.

**Comment by vmstan** [comment]
How would you ideally want to see that output?

- [EXEC] (Time) $MESSAGE
- [EXEC:Time] $MESSAGE
- Something else?

Would you want to see elapsed time since the script started or real time?

Or am I misunderstanding the ask here?

I might also want to make this an optional feature enabled in the .conf 🤔

**Comment by xorguy** [comment]
You didn't misunderstand, maybe I didn't explain enough.

I had in mind a real time timestamp, maybe something like:
[2020-05-28 19:46:54] [EXEC] $MESSAGE

I think it will better if it can be added as an option to .conf, so it can be enabled/disabled.

**Comment by vmstan** [comment]
Yeah, I like the way that looks.

**Comment by vmstan** [comment]
I've been putting off rewriting the bits that actually output each line into their own functions, but this is the excuse I've been waiting for to make that happen. Should make it easier to apply this consistently.

**Comment by SecurityWho** [comment]
+1 vote 👍 
I was looked into creating an monitoring script (Nagios / CheckMK) for the sync. But I currently find it hard to get relevant timestamps to monitor this. Would be really great to get some timestamps - at least one at start.

**Comment by reevesjeremy** [comment]
> It can be useful to add timestamps for each line on logs so user can know exactly when the process have run.

I [forked](https://github.com/reevesjeremy/gravity-sync/) and added timestamps to the logs (need to enable in the config). Although, the logs appear to only retain for the last runtime.

- if the script is running on a cron schedule at the default 15 minute cycle and
- the script is running / operating correctly

the log timestamps should be within the last 15 minutes with no history prior to that time.  Unless there is another aggregate log file that I have yet to find.

I thought I submitted a merge request but either it didnt work or it didnt get accepted. Not sure exactly how that works. :)

**Comment by vmstan** [comment]
3.7.0 has been released which removes cron and replaces it with systemd, where timestamps can before viewed of past replication jobs via `journalctl` and as such I have decided not to add this feature into the core code.
https://github.com/vmstan/gravity-sync/wiki/Changelog#37---the-daemon-release
