### ISSUE TITLE
find command in gs-backup.sh throws uncaught error

### ISSUE THREAD

**Issue by stetner** [vmstan/gravity-sync#203]
**Issue Description**

If there are no current backups in the gravity-sync/backup/  directory, the find command in the gs-backup.sh script throws an error.

find: ‘/home/stetner/gravity-sync/backup/*.backup’: No such file or directory

**Configuration Details**

Your branch is up to date with 'origin/master'.

Please apply this diff

stetner 79 $ diff gravity-sync/includes/gs-backup.sh gs-backup.sh
106c106
<     find ${LOCAL_FOLDR}/${BACKUP_FOLD}/*.backup -mtime +${BACKUP_RETAIN} -type f -delete
---
>     find ${LOCAL_FOLDR}/${BACKUP_FOLD}/  -name \*.backup -mtime +${BACKUP_RETAIN} -type f -delete

**Comment by Greg2dot0** [comment]
I am also having this issue.

**Comment by vmstan** [comment]
The backup cleanup component shouldn't run unless there has been a backup ran in the same job. I've added logic in 3.4.6 to  let all backups be deleted as well. Please test on that version once it has been published and let me know.

**Comment by stetner** [comment]
Although I cannot be sure of the chain that led to the initial error, my testing after installing 3.4.6 shows no issues, so I assume it is fixed.

Thanks!
Doug
