### ISSUE TITLE
Pause before integrity check

### ISSUE THREAD

**Issue by kormoan** [vmstan/gravity-sync#208]
There are some people where the integrity check of the primary database failed. Mine too. After some  testing I found that integrity check failed because of a locked database. The script runs the integrity check but the backup is not ready yet. We have to wait for the gravity-journal.db created during the backup disappeared. A sleep of 60 before the intregrity check will do so...
It may also be very useful to print out the reason why the integrity check failed.

**Comment by vmstan** [comment]
I have added a variable to 3.4.6 that will let you control this. By default it will be set to 5 seconds because I don't think this will impact most people.
