### ISSUE TITLE
Option for configurable Identity Files

### ISSUE THREAD

**Issue by Vertiwell** [vmstan/gravity-sync#215]
When using SSH to sync, would it be possible to allow different Identity Files instead of only .ssh/id_rsa in the .conf?
I use certs for system accounts, which require for example:
ssh -i banana.pub -i apple.key user@PrimaryRPi
I get around this atm by using ~/.ssh/config
Host *
	IdentityFile banana.pub
	IdentityFile apple.key

But that fix is not scalable.

**Comment by HunterZ** [comment]
The installer lets you specify a custom name to use for the key pair, but it errored out on me when I tried to use something other than the default.

**Comment by vmstan** [comment]
You can manually specify the ID file.
https://github.com/vmstan/gravity-sync/wiki/Hidden-Figures#ssh_pkif

If the installer isn't working there, can you screenshot the error you're seeing?

**Comment by vmstan** [comment]
Closed based on lack of reply.
