### ISSUE TITLE
script searches for ssh key in /root

### ISSUE THREAD

**Issue by Flashbin** [vmstan/gravity-sync#218]
In the wiki, the command to install gravity-sync to the secondary pi-hole is executed without root. The ssh key will be placed in the home directory of the user i'm logged in with.

After installation, the gravity-sync.sh script wants to be run with root (sudo) right, else it exits. This means it checks for the ssh key in the home folder of root (/root/.ssh/id_rsa), where it won't be available, since the installation was not run by root.

I've tried to install it as root, but "export GS_INSTALL=secondary && curl -sSL https://gravity.vmstan.com | sudo bash" won't install and exits after the checks.

My workaround was just copying id_rsa from my home folder to /root/.ssh.

I can post more infos and screenshots tomorrow, if required.

Edit: System was Debian 10.10

**Comment by vmstan** [comment]
On Debian, you should be able to install it as the root user (no sudo required.)
