### ISSUE TITLE
Performing backup of primary Domain Database sudo: sqlite3: command not found

### ISSUE THREAD

**Issue by theis82** [vmstan/gravity-sync#219]
I use gravity-sync with Pi (secondary) and Docker on Qnap (primary). 
I've installed SQLITE3 on my Qnap.

At every sync i get this error:

Validating OpenSSH client                                                   
[e] Validating RSYNC client                                                     
[e] Validating Gravity Sync folders on raspberrypi                              
[e] Validating configuration of Pi-hole                                         
[e] Validating configuration of DNSMASQ                                         
[e] Validating configuration of SQLITE3                                         
[✓] Connecting to 192.168.0.7
[i] Starting SMART Analysis
[✓] Hashing the primary Domain Database
[✓] Comparing to the secondary Domain Database
[!] Differences detected in the Domain Database
[✓] Hashing the primary Local DNS Records
[✓] Comparing to the secondary Local DNS Records
[!] Differences detected in the Local DNS Records
[i] Local DNS CNAMEs not detected on the secondary host
[!] Replication of Pi-hole settings is required
[!] Both gravity.db Have Changed
[!] Primary gravity.db Last Changed
[✓] Performing backup of secondary Domain Database
[e] Performing backup of primary Domain Databasesudo: sqlite3: command not found
[✗] Performing backup of primary Domain Database

**Comment by HunterZ** [comment]
I'm getting the same error. I think the double-quotes need to be escaped on this line of `gs-backup.sh`:
```
sqlite3 ${PIHOLE_DIR}/${GRAVITY_FI} ".backup '${LOCAL_FOLDR}/${BACKUP_FOLD}/${BACKUPTIMESTAMP}-${GRAVITY_FI}.backup'"
```

**Comment by HunterZ** [comment]
I'm not sure why, but adding `sudo` to the inline SSH command in `backup_remote_gravity_integrity()` works for me:
```sh
function backup_remote_gravity_integrity() {
    MESSAGE="${UI_BACKUP_INTEGRITY}"
    echo_stat

    primaryIntegrity=$(${SSHPASSWORD} ${SSH_CMD} -p ${SSH_PORT} -i "$HOME/${SSH_PKIF}" ${REMOTE_USER}@${REMOTE_HOST} "sudo sqlite3 ${RIHOLE_DIR}/${GRAVITY_FI}.backup 'PRAGMA integrity_check;'" | sed 's/\s.*$//')
    error_validate

    if [ "$primaryIntegrity" != 'ok' ]
    then
        MESSAGE="${UI_BACKUP_INTEGRITY_FAILED} ${UI_GRAVITY_NAME}"
        echo_fail

        MESSAGE="{UI_BACKUP_INTEGRITY_DELETE} ${UI_GRAVITY_NAME}"
        echo_stat

        CMD_TIMEOUT='15'
        CMD_REQUESTED="sudo rm ${RIHOLE_DIR}/${GRAVITY_FI}.backup"
        create_sshcmd

        exit_nochange
    fi
}
```

This is mystifying, as I was able to login to the remote host with the exact SSH parameters and run sqlite3 without sudo, without getting the error. Seems weird to use sudo to create the backup but not to verify its integrity anyway, though.

**Comment by csawall** [comment]
I'm having a similar issue as theis82; no SQLITE3 error, but it will not pull the backup of the primary...  I tried HunterZ's workaround, but that did not do anything for me.  I've been Googling for days.  Main pihole is on an rPi in my house.  Secondary is in the cloud. Thanks!

[i] Starting SMART Analysis
[e] Hashing the primary Domain Databasebash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[✓] Hashing the primary Domain Database
[✓] Comparing to the secondary Domain Database
[!] Differences detected in the Domain Database
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[e] Hashing the primary Local DNS Recordsbash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[✓] Hashing the primary Local DNS Records
[✓] Comparing to the secondary Local DNS Records
[!] Differences detected in the Local DNS Records
[!] Replication of Pi-hole settings is required
[!] Both gravity.db Have Changed
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[!] Secondary gravity.db Last Changed
[e] Performing backup of primary Domain Databasebash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[✓] Performing backup of primary Domain Database
[✓] Performing backup of secondary Domain Database
[✓] Checking Domain Database backup integrity
[✗] Pulling backup of primary Domain Database

**Comment by vmstan** [comment]
It's likely that the permissions of the user on the remote Pi-hole (QNAP) doesn't have permission to write to the folder it's attempting to backup into.
