### ISSUE TITLE
Explicitly support pihole container with different IP than Docker host

### ISSUE THREAD

**Issue by HunterZ** [vmstan/gravity-sync#236]
The install script asks for "Primary/Remote Pi-hole Address (IP or DNS)" followed immediately by SSH credentials. This is confusing, because I'm running my primary pihole container on 192.168.1.200 via macvlan, on a Docker host with IP 192.168.1.176, and pihole container's don't allow you to connect via SSH.

Does this mean my use case is not supported, or is it just using confusing wording, such that I should enter the container host IP instead of the container instance IP?

**Comment by HunterZ** [comment]
Update: I was ultimately able to get it working by entering the primary pihole's *host* IP instead of the container's IP, so I think this issue can be resolved simply by clarifying the text prompt.

**Comment by vmstan** [comment]
How would you write it compared to what is there now?

**Comment by HunterZ** [comment]
Maybe at least put the word "host" in there, like "Primary/Remote Pi-hole Host Address (IP or DNS)"

**Comment by devlinandrew** [comment]
@HunterZ did you do this on Unraid, or another vanilla docker install?  I'm trying to connect to my Pihole docker on Unraid and have the same challenge as you (Different IP than host).  I updated the host IP to be my docker host (not the container) in gravity-sync settings, but now I can't SSH in without a password.  Did you just save a PW in the settings file?  Thanks!

**Comment by HunterZ** [comment]
> @HunterZ did you do this on Unraid, or another vanilla docker install? I'm trying to connect to my Pihole docker on Unraid and have the same challenge as you (Different IP than host). I updated the host IP to be my docker host (not the container) in gravity-sync settings, but now I can't SSH in without a password. Did you just save a PW in the settings file? Thanks!
I have no idea what Unraid is. I have my primary pihole running on a Linux NAS in a Docker container, and my secondary running on a spare Linux nettop in another Docker container - both deployed and managed by Portainer running on the NAS. Each pihole container has its own IP separate from its host via a macvlan Docker network.

Unfortunately I don't remember SSH details because I set it all up 4 months ago... Maybe I set up an SSH key for passwordless login? Not sure.

**Comment by nh-mike** [comment]
Hi @devlinandrew 
I am unfarmiliar with Unraid, however the basic premise is that you must create a user which can be logged into with SSH keys. Definitely never create a passwordless user.

Check out the link below, under Manual SSH Configuration.
https://github.com/vmstan/gravity-sync/wiki/Under-The-Covers#manual-ssh-configuration

Also, the user will need sudo access. How to do this depends on the operating system, however on Debian based hosts, you can do this by adding a file for the appropriate user under /etc/sudoers, as can be seen on line 17 in gs-root.sh
https://github.com/vmstan/gravity-sync/blob/d97f92ccea426a876aca6c2094ee5f48bfed07e4/includes/gs-root.sh#L17

I hope this helps.
