### ISSUE TITLE
Integrity check failed

### ISSUE THREAD

**Issue by Ansichtsritter** [vmstan/gravity-sync#238]
Hello,

i have the following error message

```
Checking Domain Database backup integrityError: database is locked
[✓] Checking Domain Database backup integrity
[✗] Integrity check has failed for the primary Domain Database
✓] {UI_BACKUP_INTEGRITY_DELETE} Domain Database
[∞] Gravity Sync SMART aborted after 0 seconds
```

I currently have about 8.4 million domains on the blocklist, if I have only 2 million the sync works without problems.

Primary Pi is a 3B+ with dietpie, and the secondary is a Zero WH with dietpie too.

Greetings from Germany, 

Ansichtsritter

**Comment by johnynfulleffect** [comment]
Same issue.  Many items on the block list, seeing "database is locked"

**Comment by kormoan** [comment]
Have a look on issue 208. I worked out why it happens and a possible solution.

**Comment by Ansichtsritter** [comment]
> 
> 
> Have a look on issue 208. I worked out why it happens and a possible solution.

In which of the scripts or in which line did you write the timer ?

**Comment by vmstan** [comment]
See #208
