### ISSUE TITLE
Allow ability to disable all backups

### ISSUE THREAD

**Issue by Landshark77** [vmstan/gravity-sync#240]
Would like to have the ability to set the BACKUP_RETAIN setting to 0 to disable backups completely.  Even running 3.4.5, backups will consume the entire drive and are never removed.  I don't have a need for backups so would be nice to disable them completely.

**Comment by seangreen2** [comment]
Plus one to this. I run my secondary PiHole on a tiny VM. It becomes useless once all the space is used up. It would be trivial to spin another one up in the event of an error if there's wasn't a backup.

**Comment by podkilla** [comment]
Struggling with the same problem. Please implement a way to disable the backup completely.

**Comment by vmstan** [comment]
How many copies are you retaining?

**Comment by podkilla** [comment]
> How many copies are you retaining?

1

**Comment by Landshark77** [comment]
> How many copies are you retaining?

I have BACKUP_RETAIN set to 1.  I've also setup a cron job that runs every 30min to remove *.backup and *.pull from the backup folder as a workaround.  Each backup file is about 500MB and each pull file is the same size.

**Comment by vmstan** [comment]
Do you either of you see any difference with what the automated job through cron does vs running the sync manually does in terms of deleting the files?

**Comment by tapufd** [comment]
See my comment at: https://github.com/vmstan/gravity-sync/issues/220#issuecomment-914077592

**Comment by tapufd** [comment]
And I would also like the ability to completely disable the backups.
