### ISSUE TITLE
CNAMES not syncing on 5.4

### ISSUE THREAD

**Issue by timothystewart6** [vmstan/gravity-sync#254]
Hi!  I've been using this script for a while, but it seems like CNAMES might not be syncing after 5.4?

`Pi-hole v5.4 Web Interface v5.6 FTL v5.9`

I added a new CNAME to my primary, then ran a pull

```
[✓] Validating configuration of OpenSSH
[✓] Validating configuration of RSYNC
[✓] Validating Gravity Sync folders on *****
[✓] Validating configuration of Pi-hole
[✓] Validating configuration of SQLITE3
[✓] Connecting to ******
[✓] Hashing the primary Domain Database
[✓] Comparing to the secondary Domain Database
[✓] Hashing the primary Local DNS Records
[✓] Comparing to the secondary Local DNS Records
[i] No replication is required at this time
[✓] Purging redundant backups on secondary Pi-hole instance
[i] 3 days of backups remain (5.4M)
[∞] Gravity Sync PULL aborted after 11 seconds
```

**Comment by hansenc0705** [comment]
Tested and unable to duplicate.

Do you have CNAME syncing enabled? You can check this by looking at the gravity-sync.conf file.

Look for INCLUDE_CNAME='1' without a # in front of it.

**Comment by vmstan** [comment]
Indeed, it doesn't look like it's configured to check right now.

**Comment by timothystewart6** [comment]
Will check, I didn't think this was something that needed to be configured on a new install with default settings, at least not in the past.  I just created a new machine to replace my secondary.

**Comment by vmstan** [comment]
Honestly the setup questions about it are kind of confusing, because by default that file doesn't exist in Pi-hole, like the other two. So you specifically have to say you want them and then make sure the file exists on the primary (by having some data populated in the interface) for it to work.

**Comment by timothystewart6** [comment]
Thank you.  After settings `INCLUDE_CNAME='1'` in `settings/gravity-sync.conf` it now works.  I walked through the setup twice and did the quick/default setup (non advanced) and it didn't set this, I guess this is a choice.  Sorry about opening an issue.  I thought this was set automatically, but after looking at my previous config I see:

```
# ME
INCLUDE_CNAME='1'
```

`/facepalm`

Thanks again!

**Comment by hansenc0705** [comment]
Good deal. When I rebuilt my install and resetup everything the same thing happened to me. I assumed it was enabled by default on a clean install.

**Comment by aceawd** [comment]
`/etc/gravity-sync/gravity-sync.conf` has no line for `INCLUDE_CNAME='1'` and adding it in manually does nothing. Was this feature removed, or how would I go about including this?
