### ISSUE TITLE
Sync failure during "Pulling backup of primary Domain Database"

### ISSUE THREAD

**Issue by mpreissner** [vmstan/gravity-sync#263]
Primary Pi-Hole is the official docker container on a Synology NAS.  Secondary is a RasPi4 w/ Homebridge.  Able to get through the config fine, but gravity sync fails when trying to pull the backup of the primary db.

[∞] Initalizing Gravity Sync (3.4.7)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: SMART
[i] Primary Pi-hole: admin@10.100.0.3
[✓] Validating configuration of OpenSSH
[✓] Validating configuration of RSYNC
[✓] Validating Gravity Sync folders on homebridge
[✓] Validating configuration of Pi-hole
[✓] Validating configuration of DNSMASQ
[✓] Validating configuration of SQLITE3
[✓] Connecting to 10.100.0.3
[i] Starting SMART Analysis
[✓] Hashing the primary Domain Database
[✓] Comparing to the secondary Domain Database
[!] Differences detected in the Domain Database
[✓] Hashing the primary Local DNS Records
[✓] Comparing to the secondary Local DNS Records
[!] Differences detected in the Local DNS Records
[✓] Hashing the primary Local DNS CNAMEs
[✓] Comparing to the secondary Local DNS CNAMEs
[!] Differences detected in the Local DNS CNAMEs
[!] Replication of Pi-hole settings is required
[!] Both gravity.db Have Changed
[!] Secondary gravity.db Last Changed
[✓] Performing backup of primary Domain Database
[✓] Performing backup of secondary Domain Database
[✓] Checking Domain Database backup integrity
[✗] Pulling backup of primary Domain Database

Not sure where to go from here.  ./gravity-sync.sh info here:

[∞] Initalizing Gravity Sync (3.4.7)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: INFO
========================================================
Local Software Versions
Gravity Sync 3.4.7
Pi-hole
  Pi-hole version is v5.5 (Latest: v5.5)
  AdminLTE version is v5.7 (Latest: v5.7)
  FTL version is v5.10.2 (Latest: v5.10.2)
Linux 5.10.63-v7l+ armv7l
bash 5.0.3(1)-release
OpenSSH_7.9p1 Raspbian-10+deb10u2+rpt1, OpenSSL 1.1.1d  10 Sep 2019
rsync  version 3.1.3  protocol version 31
sqlite3 3.27.2 2019-02-25 16:06:06 bd49a8271d650fa89e446b42e513b595a717b9212c91dd384aab871fc1d0alt1
Sudo version 1.8.27
git version 2.20.1

Local/Secondary Instance Settings
Local Hostname: homebridge
Local Pi-hole Type: default
Local Pi-hole Config Directory: /etc/pihole
Local DNSMASQ Config Directory: /etc/dnsmasq.d
Local Gravity Sync Directory: /etc/pihole/gravity-sync
Local Pi-hole Binary Directory: /usr/local/bin/pihole
Local File Owner Settings: pihole:pihole
DNS Replication: Enabled (default)
CNAME Replication: Enabled (custom)
Verify Operations: Disabled (custom)
Ping Test: Enabled (default)
Backup Retention: 3 days (custom)
Backup Folder Size: 968K

Remote/Primary Instance Settings
Remote Hostname/IP: 10.100.0.3
Remote Username: admin
Remote Pi-hole Type: docker
Remote Pi-hole Config Directory: /volume1/docker/pihole/pihole
Remote DNSMASQ Config Directory: /volume1/docker/pihole/dnsmasq
Remote Pi-hole Container Name: pihole-pihole2
Remote Docker Binary Directory: /usr/bin/docker
Remote File Owner Settings: 999:999
========================================================
[∞] Gravity Sync INFO aborted after 0 seconds

**Comment by eskiiom** [comment]
Hello,
Just installed 2 fresh instance of pihole in order to migrate from the single existing one, and I have the exact same issue  with 2 debian 11 proxmox containers

`[∞] Initalizing Gravity Sync (3.4.7)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: INFO
========================================================
Local Software Versions
Gravity Sync 3.4.7
Pi-hole
  Pi-hole version is v5.6 (Latest: v5.6)
  AdminLTE version is v5.8 (Latest: v5.8)
  FTL version is v5.11 (Latest: v5.11)
Linux 5.11.22-5-pve x86_64
bash 5.1.4(1)-release
OpenSSH_8.4p1 Debian-5, OpenSSL 1.1.1k  25 Mar 2021
rsync  version 3.2.3  protocol version 31
sqlite3 3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ealt1
Sudo version 1.9.5p2
git version 2.30.2

Local/Secondary Instance Settings
Local Hostname: piholeLXCslave
Local Pi-hole Type: default
Local Pi-hole Config Directory: /etc/pihole
Local DNSMASQ Config Directory: /etc/dnsmasq.d
Local Gravity Sync Directory: /root/gravity-sync
Local Pi-hole Binary Directory: /usr/local/bin/pihole
Local File Owner Settings: pihole:pihole
DNS Replication: Enabled (default)
CNAME Replication: Enabled (custom)
Verify Operations: Disabled (custom)
Ping Test: Enabled (default)
Backup Retention: 3 days (custom)
Backup Folder Size: 1.1G

Remote/Primary Instance Settings
Remote Hostname/IP: 192.168.0.100
Remote Username: gravitysync
Remote Pi-hole Type: default
Remote Pi-hole Config Directory: /etc/pihole
Remote DNSMASQ Config Directory: /etc/dnsmasq.d
Remote Pi-hole Binary Directory: /usr/local/bin/pihole
Remote File Owner Settings: pihole:pihole
========================================================
[∞] Gravity Sync INFO aborted after 1 seconds
`

**Comment by Cmoi20** [comment]
please, try to modify file in includes/ from "CMD_TIMEOUT='15'" to "CMD_TIMEOUT='30'"

if needed, try to increase from 30 to 60

**Comment by mpreissner** [comment]
Set all instances of CMD_TIMEOUT to 60 in all files, still fails at Pulling backup of Primary Domain Database.  The fail is immediate once hitting that step...adjusting the timeout value had no effect on how quickly the process exited.

**Comment by Cmoi20** [comment]
can you try ssh connexion manually with same users. using same keys ?

**Comment by mpreissner** [comment]
No problem doing ssh using key.  Logs right into the Syno NAS.

**Comment by Cmoi20** [comment]
ok, using Syno NAS. that's probably a right or folder issue. maybe you can test to force information about all folder in conf file.

**Comment by mpreissner** [comment]
That's what I'm thinking.  I have found a few differences that I needed to account for in the conf file...like Synology keeps docker in /usr/local/bin instead of /usr/bin.  What can I do with the conf file to debug this further?

**Comment by eskiiom** [comment]
> please, try to modify file in includes/ from "CMD_TIMEOUT='15'" to "CMD_TIMEOUT='30'"
> 
> if needed, try to increase from 30 to 60

Hello,
i've changed all references to 60 seconds directly, and eveything seems to work just fine.
Thanks a lot !

root@piholeLXCslave:~/gravity-sync# ./gravity-sync.sh
[∞] Initalizing Gravity Sync (3.4.7)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: SMART
[i] Primary Pi-hole: gravitysync@192.168.0.100
[✓] Validating configuration of OpenSSH
[✓] Validating configuration of RSYNC
[✓] Validating Gravity Sync folders on piholeLXCslave
[✓] Validating configuration of Pi-hole
[✓] Validating configuration of DNSMASQ
[✓] Validating configuration of SQLITE3
[✓] Connecting to 192.168.0.100
[i] Starting SMART Analysis
[✓] Hashing the primary Domain Database
[✓] Comparing to the secondary Domain Database
[!] Differences detected in the Domain Database
[✓] Hashing the primary Local DNS Records
[✓] Comparing to the secondary Local DNS Records
[!] Differences detected in the Local DNS Records
[i] Local DNS CNAMEs not detected on the secondary host
[!] Replication of Pi-hole settings is required
[!] Both gravity.db Have Changed
[!] Secondary gravity.db Last Changed
[✓] Performing backup of primary Domain Database
[✓] Performing backup of secondary Domain Database
[✓] Checking Domain Database backup integrity
[✓] Pulling backup of primary Domain Database
[✓] Pushing the secondary Domain Database
[✓] Setting file ownership on Domain Database
[✓] Setting file permissions on Domain Database
[!] Both custom.list Have Changed
[!] Primary custom.list Last Changed
[✓] Performing backup of secondary Local DNS Records
[✓] Performing backup of primary Local DNS Records
[✓] Pulling the primary Local DNS Records
[✓] Replacing the secondary Local DNS Records
[✓] Validating file ownership on Local DNS Records
[✓] Validating file permissions on Local DNS Records
[i] Isolating regeneration pathways
[✓] Updating secondary FTLDNS configuration
[✓] Reloading secondary FTLDNS services
[i] Inverting tachyon pulses
[✓] Updating primary FTLDNS configuration
[✓] Reloading primary FTLDNS services
[i] Performing replicator diagnostics
[✓] Rehashing the primary Domain Database
[✓] Recomparing to the secondary Domain Database
[✓] Rehashing the primary Local DNS Records
[✓] Recomparing to the secondary Local DNS Records
[i] Local DNS CNAMEs not detected on the secondary host
[✓] Purging redundant backups on secondary Pi-hole instance
[i] 3 days of backups remain (524M)
[✓] Saving the updated hashes from this replication
[✓] Logging successful SMART
[∞] Gravity Sync SMART completed after 562 seconds

**Comment by OhhHellooow** [comment]
> please, **try to modify file** in includes/ from "CMD_TIMEOUT='15'" to "CMD_TIMEOUT='30'"
> 
> if needed, try to increase from 30 to 60

What is the Name of the file you are referencing?

**Comment by eskiiom** [comment]
Hi @OhhHellooow
In fact there are quite a few to edit.
I think the best is to open them one by one and look for the string CMD_TIMEOUT='15'

**Comment by kingdomgardens** [comment]
I think I'm having this same problem.  I also tried setting the CMD_TIMEOUT='15' instances to CMD_TIMEOUT='15' for all the files in the /includes folder.  No change. I'm also using primary pihole in a docker container on synology nas.

**Comment by FDisk80** [comment]
Same issue [✗] Pulling backup of primary Domain Database.

**Comment by wavezcs** [comment]
> Same issue [✗] Pulling backup of primary Domain Database.

Make sure you have enabled rsync in the Synology control panel (Control Panel > File Services > rsync)

I had the same error and debugging showed that the rsync command was throwing the error "permission denied, please try again".  This isn't a file permissions issue, but rsync not enabled.

**Comment by kingdomgardens** [comment]
Thanks, but rsync is already enabled for me.
