### ISSUE TITLE
compare fails to connect to primary server

### ISSUE THREAD

**Issue by kingdomgardens** [vmstan/gravity-sync#273]
Hi.  I followed a guide to setting up gravity sync and it all appears to have installed.  I have my primary pihole in a docker container on a synology ds920+ running dsm7, and my secondary pihole on a raspberry pi zero.  When I do ./gravity-sync.sh compare it returns:
[∞] Initalizing Gravity Sync (3.4.7)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: COMPARE
[i] Primary Pi-hole: xxxxx@192.168.2.49
[✓] Validating configuration of OpenSSH
[✓] Validating configuration of RSYNC
[✓] Validating Gravity Sync folders on raspberrypihole
[✓] Validating configuration of Pi-hole
[✓] Validating configuration of DNSMASQ
[✗] Connecting to 192.168.2.49
--it seems to do fine on all the steps except the last--it doesn't connect.  I can use ssh to connect from the raspberry pi terminal to the nas manually.  What might I be missing? 
I'm not very experienced with linux, though I can usually follow instructions!  Please go easy on me.

**Comment by vmstan** [comment]
It's likely a issue with your Synology not persisting the SSH key that gets established during setup. The home profile on the Synology doesn't have SSH setup to do this by default.

**Comment by kingdomgardens** [comment]
Thank you. With a little research, I got that working. Now when I do ./gravity-sync.sh pull, everything works except the last line again. It says differences are detected, replication required, but the last line fails.
[X] Pulling the primary Domain Database

Bruce
________________________________

**Comment by kingdomgardens** [comment]
One more thing.  When I run ./gravity-sync.sh logs.  It says no log files are found.  I don't remember turning off logging, but I can't figure out how to turn it on either.  I'm sure there's something simple I'm missing.

**Comment by darkcloud784** [comment]
@kingdomgardens  how did you get this resolved?

**Comment by kingdomgardens** [comment]
Thanks for asking.  No.  I have not.  The logs are still missing and the script still fails at "Pulling the Primary Domain Database."  I wondered if the pull failure might be a permissions issue as my primary pihole is in a docker container on my synology nas, but I have not been able to find any clear reason for the failure, and the logging issue is present on my secondary pihole which is on a dedicated raspberry pi zero.

Would love to get this working.
