### ISSUE TITLE
piHole Sync (pull) won't work (I use cloud flared as upstream dns)

### ISSUE THREAD

**Issue by tardar** [vmstan/gravity-sync#274]
Hi guys,

i set up gravity-sync after watching the video from TechnoTim.
Great stuff, but it isn't working for me :(

I've setup both pinholes with a cloud flared dns with a custom upstream dns.
Maybe this is a problem?

Here are some infos: (logs aren't generated)

The export of the pull is like this:
[∞] Initalizing Gravity Sync (3.4.7)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: PULL
[i] Primary Pi-hole: root@192.***.***.***
[✓] Validating configuration of OpenSSH
[✓] Validating configuration of RSYNC
[✓] Validating Gravity Sync folders on dnsMirror
[✓] Validating configuration of Pi-hole
[✓] Validating configuration of DNSMASQ
[✓] Validating configuration of SQLITE3
[✓] Connecting to 192.***.***.***
[✓] Hashing the primary Domain Database
[✓] Comparing to the secondary Domain Database
[!] Differences detected in the Domain Database
[✓] Hashing the primary Local DNS Records
[✓] Comparing to the secondary Local DNS Records
[!] Differences detected in the Local DNS Records
[i] Local DNS CNAMEs not detected on the secondary host
[!] Replication of Pi-hole settings is required
[✓] Performing backup of secondary Domain Database
[✓] Performing backup of primary Domain Database
[✓] Checking Domain Database backup integrity
[✓] Pulling the primary Domain Database
[✓] Replacing the secondary Domain Database
[✓] Validating file ownership on Domain Database
[✓] Validating file permissions on of Domain Database
[✓] Performing backup of secondary Local DNS Records
[✓] Performing backup of primary Local DNS Records
[✗] Pulling the primary Local DNS Records

The info output:
`**@**:~/gravity-sync $ ./gravity-sync.sh info
[∞] Initalizing Gravity Sync (3.4.7)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: INFO
========================================================
Local Software Versions
Gravity Sync 3.4.7
Pi-hole
  Pi-hole version is v5.8 (Latest: v5.8)
  AdminLTE version is v5.10 (Latest: v5.10)
  FTL version is v5.13 (Latest: v5.13)
Linux 5.10.63-v7l+ armv7l
bash 5.1.4(1)-release
OpenSSH_8.4p1 Raspbian-5+b1, OpenSSL 1.1.1k  25 Mar 2021
rsync  version 3.2.3  protocol version 31
sqlite3 3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ealt1
Sudo version 1.9.5p2
git version 2.30.2

Local/Secondary Instance Settings
Local Hostname: dnsMirror
Local Pi-hole Type: default
Local Pi-hole Config Directory: /etc/pihole
Local DNSMASQ Config Directory: /etc/dnsmasq.d
Local Gravity Sync Directory: /home/pi/gravity-sync
Local Pi-hole Binary Directory: /usr/local/bin/pihole
Local File Owner Settings: pihole:pihole
DNS Replication: Enabled (default)
CNAME Replication: Enabled (custom)
Verify Operations: Disabled (custom)
Ping Test: Enabled (default)
Backup Retention: 7 days (default)
Backup Folder Size: 269M

Remote/Primary Instance Settings
Remote Hostname/IP: ***.***.***.***
Remote Username: ***
Remote Pi-hole Type: default
Remote Pi-hole Config Directory: /etc/pihole
Remote DNSMASQ Config Directory: /etc/dnsmasq.d
Remote Pi-hole Binary Directory: /usr/local/bin/pihole
Remote File Owner Settings: pihole:pihole
========================================================
[∞] Gravity Sync INFO aborted after 0 seconds
`

compare result:
[∞] Initalizing Gravity Sync (3.4.7)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: COMPARE
[i] Primary Pi-hole: **@***.***.***.***
[✓] Validating configuration of OpenSSH
[✓] Validating configuration of RSYNC
[✓] Validating Gravity Sync folders on dnsMirror
[✓] Validating configuration of Pi-hole
[✓] Validating configuration of DNSMASQ
[✓] Connecting to ***.***.***.***
[✓] Hashing the primary Domain Database
[✓] Comparing to the secondary Domain Database
[!] Differences detected in the Domain Database
[✓] Hashing the primary Local DNS Records
[✓] Comparing to the secondary Local DNS Records
[!] Differences detected in the Local DNS Records
[i] Local DNS CNAMEs not detected on the secondary host
[!] Replication of Pi-hole settings is required
[✓] Purging redundant backups on secondary Pi-hole instance
[i] 7 days of backups remain (269M)
[∞] Gravity Sync COMPARE completed after 102 seconds

So it isn't working for me at the moment.
Hope we can get this working, I like this project so much :)

**Comment by SecurityWho** [comment]
Please have a look at issue #220 - this should be the same issue as your problem. I don't have an solution for it, but I found an workaround that is currently working for me.

**Comment by nh-mike** [comment]
Hi @tardar 
I would suggest having a quick read of the wiki page to see if there's any steps you may have missed, especially under "Primary Pi-Hole".
https://github.com/vmstan/gravity-sync/wiki/Installing
If you believe that you have done this all correctly, check that you have rsync installed on your Primary Pi-Hole machine (That's as simple as executing `which rsync` and you'll either get a path returned, or nothing).

Cheers.

**Comment by vmstan** [comment]
Closing based on lack of OP reply.
