### ISSUE TITLE
Alpine gravtiy-sync timeout error

### ISSUE THREAD

**Issue by Lsm-CVX** [vmstan/gravity-sync#285]
HI!

Thansk for the very interesting project. 

I encounter a problem on an install using Alpine (3.14 / 3.15 shall be the same) : 

[∞] Initalizing Gravity Sync (3.4.8)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: SMART
[i] Primary Pi-hole: root@10.0.0.25
[✓] Validating configuration of OpenSSH
[✓] Validating configuration of RSYNC
[✓] Validating Gravity Sync folders on proxmrs-DNS-pihole3
[✓] Validating configuration of Pi-hole
[✓] Validating configuration of SQLITE3
[e] Connecting to 10.0.0.25timeout: unrecognized option: preserve-status
BusyBox v1.33.1 () multi-call binary.

Usage: timeout [-s SIG] SECS PROG ARGS

Run PROG. Send SIG to it if it is not gone in SECS seconds.
Default SIG: TERM.
[✗] Connecting to 10.0.0.25
proxmrs-DNS-pihole3:~/gravity-sync# bash gravity-sync.sh
[∞] Initalizing Gravity Sync (3.4.8)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: SMART
[i] Primary Pi-hole: root@10.0.0.25
[✓] Validating configuration of OpenSSH
[✓] Validating configuration of RSYNC
[✓] Validating Gravity Sync folders on proxmrs-DNS-pihole3
[✓] Validating configuration of Pi-hole
[✓] Validating configuration of SQLITE3
[e] Connecting to 10.0.0.25timeout: unrecognized option: preserve-status
BusyBox v1.33.1 () multi-call binary.

Usage: timeout [-s SIG] SECS PROG ARGS

Run PROG. Send SIG to it if it is not gone in SECS seconds.
Default SIG: TERM.
[✗] Connecting to 10.0.0.25

I trace this to the syntax of timeout command is different between bash and busibox.

BusyBox v1.33.1 () multi-call binary.

Usage: timeout [-s SIG] SECS PROG ARGS

Run PROG. Send SIG to it if it is not gone in SECS seconds.
Default SIG: TERM

whereas on bash / ubuntu : 

Usage: timeout [OPTION] DURATION COMMAND [ARG]...
  or:  timeout [OPTION]
Start COMMAND, and kill it if still running after DURATION.

Mandatory arguments to long options are mandatory for short options too.
      --preserve-status
                 exit with the same status as COMMAND, even when the
                   command times out
This function is called in the inlcude/gs-ssh

## Determine SSH Pathways
function create_sshcmd {
##    timeout --preserve-status ${CMD_TIMEOUT} ${SSH_CMD} -p ${SSH_PORT} -i $HOME/${SSH_PKIF} -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "${CMD_REQUESTED}"

Removing the timeout sort out my issue for now : 

[∞] Initalizing Gravity Sync (3.4.8)
[✓] Loading gravity-sync.conf
[✓] Evaluating arguments: SMART
[i] Primary Pi-hole: root@10.0.0.25
[✓] Validating configuration of OpenSSH
[✓] Validating configuration of RSYNC
[✓] Validating Gravity Sync folders on proxmrs-DNS-pihole3
[✓] Validating configuration of Pi-hole
[✓] Validating configuration of SQLITE3
[✓] Connecting to 10.0.0.25
[i] Starting SMART Analysis
[✓] Hashing the primary Domain Database
[✓] Comparing to the secondary Domain Database
[!] Differences detected in the Domain Database
[✓] Hashing the primary Local DNS Records
[✓] Comparing to the secondary Local DNS Records
[!] Differences detected in the Local DNS Records
[!] Replication of Pi-hole settings is required
[!] Both gravity.db Have Changed
[!] Secondary gravity.db Last Changed
[✓] Performing backup of primary Domain Database
[✓] Performing backup of secondary Domain Database
[✓] Checking Domain Database backup integrity
[✓] Pulling backup of primary Domain Database
[✓] Pushing the secondary Domain Database
[✓] Setting file ownership on Domain Database
[✓] Setting file permissions on Domain Database
[!] Both custom.list Have Changed
[!] Secondary custom.list Last Changed
[✓] Performing backup of primary Local DNS Records
[✓] Performing backup of secondary Local DNS Records
[✓] Pulling backup of primary Local DNS Records
[✓] Pushing the secondary Local DNS Records
[✓] Setting file ownership on Local DNS Records
[✓]  Local DNS Records
[i] Inverting tachyon pulses
[✓] Updating primary FTLDNS configuration
[✓] Reloading primary FTLDNS services
[i] Performing replicator diagnostics
[✓] Rehashing the primary Domain Database
[✓] Recomparing to the secondary Domain Database
[✓] Rehashing the primary Local DNS Records
[✓] Recomparing to the secondary Local DNS Records
[✓] Purging redundant backups on secondary Pi-hole instance
[i] 3 days of backups remain (5.6M)
[✓] Saving the updated hashes from this replication
[✓] Logging successful SMART
[∞] Gravity Sync SMART completed after 33 seconds

I understand that is not really a long term solution Maybe you can advise on that ? 

Thanks !!

**Comment by nh-mike** [comment]
Hi @Lsm-CVX 
Please see the below issue, you have encountered the same problem, making this a duplicate ticket. Note the line;
`[e] Connecting to 10.0.0.25timeout: unrecognized option: preserve-status` 

https://github.com/vmstan/gravity-sync/issues/135

Cheers.

**Comment by vmstan** [comment]
Close as duplicate.
