### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by darkcloud784** [vmstan/gravity-sync#288]
I'd like to be able to sync my kubernetes deployed pihole server with my raspberry pi deployed one. Since I have a multi-node deployment the current method of adding the docker host ip won't work. Might be best the script can pull from the volume via authenticated api? Or if there is an easier way please let me know. I've tried this multiple times and doesn't seem to work =(

**Comment by vmstan** [comment]
If someone else is willing to code this I'll consider it but at the moment I don't see enough need.

**Comment by namenmalkav** [comment]
the native support of k8s will be great simplifying the installation and maintenance
