### ISSUE TITLE
Support for install directly inside pihole image/container 

### ISSUE THREAD

**Issue by hppyworld** [vmstan/gravity-sync#290]
Its good idea to install gravity sync in pihole container or create a new pihole docker image with gravity sync installed to sync with other same setup. It can be more then 2 pihole instance. So basically we do not need to install gravity sync in host machine and everything works within docker containers. 

Can we add this feature? 

Thanks a lot for help.

**Comment by nh-mike** [comment]
Hi @hppyworld 

I run a docker container for GravitySync. Check it out, it may be just what you're looking for.
[nh-mike/gravity-sync-docker](https://github.com/nh-mike/gravity-sync-docker)

**Comment by hppyworld** [comment]
@nh-mike Thanks for reply and docker image.
