### ISSUE TITLE
Use systemd timers instead of cron

### ISSUE THREAD

**Issue by mustaphazorgati** [vmstan/gravity-sync#292]
_Is your feature request related to a problem? If so maybe a Bug Report is more approprate? Otherwise, please give clear and concise description of what prompted your request -- Ex. "I'm always frustrated when [...]" -- then provide a clear and concise description of what you want to happen. If you're willing to commit code changes with your suggestions the project would welcome pull requests._

Hey there!
I wanted to see the history of the created logs and found out, that the automatically configured cron overrides the previous log. I didn't like that at all.

Because of that I replaced the cron with a systemd timer. Due to that I am able to access all logs via `journalctl`. Is this a possible improvement?

If so, I am willing to help out a little bit.

**Comment by vmstan** [comment]
I'm working on incorporating this into an upcoming release.

**Comment by mustaphazorgati** [comment]
Amazing!

Here's my systemd timer configurations. Hopefully this helps ;)

File: /etc/systemd/system/gravity-sync.service
```
[Unit]
Description=Sync primary and secondary Pi-hole instances
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
Type=simple
User=<USER>
Group=<GROUP>
ExecStart=/home/<USER>/gravity-sync/gravity-sync.sh
TimeoutStartSec=infinity
```

File: /etc/systemd/system/gravity-sync.timer
```
[Unit]
Description=Minutly sync of primary and secondary Pi-hole instances

[Timer]
OnCalendar=*-*-* *:*:00
Persistent=true

[Install]
WantedBy=timers.target
```

With this configuration the timer starts every minute.

If I can help in any other way, let me know ;)

**Comment by vmstan** [comment]
Looks pretty similar to what I've cooked up, except the timing will be a little different. It's going to default to a pseudo-random 5 minute interval, but obviously you can adjust as needed.
