### ISSUE TITLE
Backups still filling up /gravity-sync/backup

### ISSUE THREAD

**Issue by nnleaf** [vmstan/gravity-sync#298]
Hi, I saw that #220 was closed, but I'm still facing that issue. 

I update gravity-sync to 3.5.0, ran `./gravity-sync.sh config`, then `./gravity-sync.sh automate` with 5 minutes as timer. It's left a cron job..

```
PATH=/bin:/usr/bin:/usr/sbin
*/5 * * * * /bin/bash /home/nn/gravity-sync/gravity-sync.sh smart > /home/nn/gravity-sync/logs/gravity-sync.cron
```

I've wiped out the `.db.backup` files in `/gravity-sync/backup` and ran the following again. 

```
./gravity-sync.sh config
./gravity-sync.sh automate
```

So for now it's clear again. Perhaps a bug, or something remained from the last version? I'll check in on it tonight to see if the backup folder has filled up. Is there anything you need from me?

**Comment by vmstan** [comment]
Once you upgrade, you need to run a successful backup for the directory to clear.

If the task that runs via cron is leaving remnants in the backup directory then the task is not completing successfully.

**Comment by vmstan** [comment]
As an alternative if you're out of space, once you upgrade to 3.5.0, you can run './gravity-sync.sh upgrade' again. It will run the upgrade script with additional cleanup commands included in 3.5.0.

**Comment by Milkysunshine** [comment]
Simply deleting the files after creating doesn't seem like the best way to handle this quick fix. That's a massive amount of disk writes for absolutely nothing. Not a very SSD friendly approach.

![gravitysync](https://user-images.githubusercontent.com/78696021/155898357-1322ad91-d71e-4871-9253-8ba2b96fdcdf.png)

Part of the issue with my recent install is, gravity sync is never actually synced. I can run a pull back to back with zero changes, and it will say unsynced, create a backup, and move the data. Every single time it runs via cron, it creates a backup. I filled up 30 gigs in 11 hours.

**Comment by vmstan** [comment]
If your install isn't pulling correctly when run manually, don't automate it.

GS doesn't make any backups or data copies if it detects no changes have been made.

**Comment by Milkysunshine** [comment]
That is understood, but, it wasn't failing? 

I did disable automation and simply plan to use pi-hole's teleporter for now. 

I have it set up as an clone in 2 different VMs, on 2 different proxmox servers. Keepalived handles the virt ip, so this manual export/import setup works for me. I just know it won't work for all. Especially those running 2 or more as primary and secondary NDS servers.

**Comment by vmstan** [comment]
It wasn’t failing prior to upgrading to 3.6.0?

**Comment by Milkysunshine** [comment]
I just installed it on Saturday.

**Comment by vmstan** [comment]
@nnleaf can you confirm if you're still having retention issues?

**Comment by vmstan** [comment]
@Milkysunshine what OS were you running inside the Proxmox VMs?

**Comment by Milkysunshine** [comment]
Fully updated Debian 11.

**Comment by vmstan** [comment]
> Fully updated Debian 11.

And they are standard Pi-hole installs within Debian, not running Docker or another container engine?

**Comment by vmstan** [comment]
@Milkysunshine can you try and run a `pihole restartdns` from your Debian 11 system, while using the same account that you were running Gravity Sync as?

On my Debian 11 test box, this results in a `/usr/local/bin/pihole: line 163: service: command not found` error. If this is the case, Gravity Sync will stop and fall on it's face. 

That line in the Pi-hole code is referencing 'service pihole-FTL restart' but the alias for the service command doesn't exist for my user.

After adding `PATH=$PATH:/usr/sbin` to my bashrc profile, it works correctly.

**Comment by Milkysunshine** [comment]
I'll definitely sit down tomorrow and spend some time with it.

**Comment by Milkysunshine** [comment]
Well, I was trying to avoid it, but I was able to get everything working as expected using a new account. I don't know what the issues were before unfortunately, as I had already deleted the user and gravity sync folder I had been using before.

**Comment by vmstan** [comment]
@Milkysunshine Glad to hear it!

**Comment by nnleaf** [comment]
I noticed it was adding files to backup so I started the install from scratch by deleting the directory.

Perhaps something went wrong during the upgrade, but I can report that a fresh install works as intended...
