### ISSUE TITLE
Won't update when using crontab

### ISSUE THREAD

**Issue by Cheesemonkey42** [vmstan/gravity-sync#3]
This may be my Linux inexperience... 

When I run the script manually it updates my secondary Pihole just fine. When it runs through crontab, I see in the script log that it was ran. I also see that in the /var/log/syslog that crontab ran it. But it does not copy of the the gravity.db file and update my secondary pihole server. Anything I am doing wrong or what to check for? Thanks

**Comment by vmstan** [comment]
If you run `./gravity-sync.sh logs` does it show pull attempt completed at that time?

What does your entry in crontab look like?

**Comment by Cheesemonkey42** [comment]
Yes, it’s does show a pull log at the same time as the crontab job

This is what my crontab looks like. I set it to every minute for testing. But it did it at the 30 minute intervals as well

![image](https://user-images.githubusercontent.com/65792136/82719313-3481c480-9c5e-11ea-9e14-f3eaedfcd017.jpeg)

**Comment by vmstan** [comment]
Interesting, mine is doing the same thing now that I look. I wonder if it's a permissions issue for the cron job not being able to overwrite the database. I changed the way it moves the files around in the v1.2.3 release. Let me dig into this a bit.

**Comment by vmstan** [comment]
Should be fixed, update the script.
If you installed via git then `./gravity-sync.sh update` should get you the latest.
If you manually installed, manually replace with v1.2.4 that was just published.

**Comment by Cheesemonkey42** [comment]
It looks like my issue is that the script is asking for a password for the account on the other pihole instance, even though I set on the SSH key and I am able to SSH into the other pihole instance without entering a password.

It wasn't doing this until I logged out and logged back in again. This makes sense that the crontab is prob running but needs a password.

Perhaps there isn't something setup correctly with the access to the other pihole instance, I did this part of the setup in your instructions:

ssh-keygen -t rsa
ssh-copy-id -i ~/.ssh/id_rsa.pub USERNAME@PRIMARYPI
(this asks for a password initially, but then doesn't afterwards)

I just enter enter for the defaults on all of the prompts. 

Again, this could be my Linux inexperience at work here.

**Comment by vmstan** [comment]
It's probably more likely there is more than one bug at play, and I only squashed one of them. If the script executes, and you're able to SSH without a password into the primary PH from the secondary, I wonder if your cron is trying to run with a different user. Are you using the user crontab or the system crontab? The system will run as root and have a different RSA key.

**Comment by vmstan** [comment]
What distro are you running?

**Comment by Cheesemonkey42** [comment]
I added "echo" lines before each command after that to find out which command was asking for a password and found that this line was asking for a password
"sudo cp -v $HOME/${LOCAL_FOLDR}/${BACKUP_FOLD}/${GRAVITY_FI}.pull ${PIHOLE_DIR}/${GRAVITY_FI}"

Also sorry I failed to mention this earlier, my secondary Pihole server (the one I am running the script on) is Ubuntu 18.04 and the the primary Pihole server is "Raspbian GNU/Linux Version 10" not sure if that could be an issue.

**Comment by Cheesemonkey42** [comment]
Regarding the cron, I am using the users crontab, not the systems

**Comment by Cheesemonkey42** [comment]
Update: I got that command to run without prompting by editing my sudoers file, but still doesn't update when the crontab runs...

**Comment by Cheesemonkey42** [comment]
I think I fixed it. I edited my sudoers file for that user to run sudo commands without being prompted for a password and it works in crontab now.

**Comment by vmstan** [comment]
Awesome! I’m working on v1.3 now which adds a ton of error checking that will let the script fail properly when something doesn’t complete as expected, so that it quits acting like it’s fine and goes to the next step. Probably will publish after the holiday weekend.

**Comment by Cheesemonkey42** [comment]
Thanks for the help and this awesome script!
