### ISSUE TITLE
Issue syncing 2 docker instances - unable to validate configuration folder for Pi-hole

### ISSUE THREAD

**Issue by totalgit74** [vmstan/gravity-sync#300]
I've setup ssh from my secondary to my primary pihole host using a ed25519 key - this works fine when using ssh.
The user name is set correctly (pi). One thing that may be causing an issue is the configuration directory when using docker.
Does the config want
1. The path within the container i.e. /etc/pihole
2. The path on the host i.e. /var/lib/docker/volumes/... as I am using volume definitions. 

From looking at the section in gs-validate.sh that issues the message
`Unable to validate configuration folder for Pi-hole`
If seems like it is looking for the folder on the host i.e. (2) above. 

If I run the script as `sudo ./gravity-sync.sh compare` then I get past the issue above but cannot connect to the primary due to the script now expecting the ssh key to be under /root.

Does the script really only work for containers where bind mounts are used that are rw by the pi user or is there something else at play?

**Comment by totalgit74** [comment]
Ok. That's interesting as Docker's [recommendation](https://docs.docker.com/storage/volumes/) is that volume mounts are used as the preferred persistence mechanism as they're managed by docker rather than being influenced by the underlying OS.
Was wondering whether, for containers, the most fail-safe mechanism for data access would be to use `docker cp` to copy data or is the sync process reliant on being able to access/update the db via querying?

**Comment by vmstan** [comment]
The requirement for file paths came out of wanting to do the least amount of work required specific to container deployments, and not building an entirely different replication path for them vs a standard Pi-hole deployment. Other than checks to guide the user to set it all up correctly, and some minor changes to the way the Pi-hole refresh commands are executed it's mostly the same. 

Yes, the script does a sqlite backup and integrity check of the database directly.
