### ISSUE TITLE
Gravity-Sync 3.6.1 version issue

### ISSUE THREAD

**Issue by jostrasser** [vmstan/gravity-sync#303]
**Issue Description**

After updating from 3.6.0 to 3.6.1 the version is missing and I am getting the following error when I run compare:

```
./gravity-sync/gravity-sync.sh version
./gravity-sync/gravity-sync.sh: line 6: VERSION: No such file or directory
∞ Initalizing Gravity Sync ()
✓ Evaluating arguments: VERSION
» Running version: 
» Update available: 3.6.1
∞ Gravity Sync VERSION exited after 0 seconds
```

```
./gravity-sync/gravity-sync.sh compare
./gravity-sync/gravity-sync.sh: line 6: VERSION: No such file or directory
∞ Initalizing Gravity Sync ()
✓ Loading gravity-sync.conf
✓ Evaluating arguments: COMPARE
» Primary Pi-hole: pi@192.168.5.101
✓ Validating configuration of OpenSSH
✓ Validating configuration of RSYNC
✓ Validating Gravity Sync folders on dns2
✓ Validating configuration of Pi-hole
✓ Connecting to 192.168.5.101
✓ Hashing the primary Domain Database
✓ Comparing to the secondary Domain Database
✓ Hashing the primary Local DNS Records
✓ Comparing to the secondary Local DNS Records
» No replication is required at this time
✓ Purging unused data files from this Pi-hole instance
∞ Gravity Sync COMPARE exited after 2 seconds

```

**Comment by vmstan** [comment]
Just to confirm, there is a `VERSION` file in your gravity-sync directory? Also what OS are you running. It seems my little trick of just pulling from that file isn't as simple as I thought.

**Comment by vmstan** [comment]
Odd. Can you do me a favor and edit line 6 in your `gravity-sync.sh` file where it says `VERSION=$(<VERSION)` to `VERSION=$(cat VERSION)` and see if it displays correctly when you run it?

**Comment by jostrasser** [comment]
done, but:

```
pi@dns2:~ $ ./gravity-sync/gravity-sync.sh version
cat: VERSION: No such file or directory
∞ Initalizing Gravity Sync ()
✓ Evaluating arguments: VERSION
» Running version: 
» Update available: 3.6.1
∞ Gravity Sync VERSION exited after 0 seconds
pi@dns2:~ $ 
```

**Comment by vmstan** [comment]
That's so odd. I guess I need to find a Debian 10 box to test on. It works fine both ways on my Ubuntu and Debian 11 setups.

**Comment by jostrasser** [comment]
hmm, will this bug preventing an update to a new version when a new version will be released?

**Comment by vmstan** [comment]
No. I'm publishing a 3.6.2 as we speak that will just revert to the previous version behavior. Anytime you run the update script it forces itself to run whatever the latest version is.

**Comment by jostrasser** [comment]
ok, great, thanks a lot Michael!
