### ISSUE TITLE
Split from #307 for @joggs

### ISSUE THREAD

**Issue by vmstan** [vmstan/gravity-sync#311]
Same problem here.
Oh, so the update command wipes the backups? 
I'll add that to cron until it's sorted out.
Would be great if you could add a setting to disable the backup feature

_Originally posted by @joggs in https://github.com/vmstan/gravity-sync/issues/307#issuecomment-1077381942_

**Comment by vmstan** [comment]
@joggs please post the output of `./gravity-sync.sh cron` and `./gravity-sync.sh info` here.

**Comment by vmstan** [comment]
Please try and update to 3.6.3 (just released) and follow the instructions about recreating your automation task.
https://github.com/vmstan/gravity-sync/wiki/Changelog#363

Make any change to your Pi-hole settings and let the automated replication run, then see if the cron task is clean and there are no backup files left behind.

**Comment by vmstan** [comment]
3.7.0 has been released which removes cron entirely, and replaces it with systemd. Please install and advise.
https://github.com/vmstan/gravity-sync/wiki/Changelog#37---the-daemon-release

**Comment by joggs** [comment]
Sorry for the late reply. I've isntalled 3.7.0 and have run the sudo ./gravity-sync.sh auto command that completed successfully.
No errors when performing a manual sync either.
The backup folder is empty, so I guess I just have to wait for a week and then check the status of the new setup.
I have not performed the config command after the update to 3.7.0 as I didn't want to wipe my current config. I suppose that is alright as I suppose there are no breaking changes?

**Comment by vmstan** [comment]
Shouldn't be any need to redo the config, no changes at all there. Let me know how it goes.

**Comment by joggs** [comment]
The backup folder is still empty so everything is good for me so far
