### ISSUE TITLE
Split from #307 for @theDoctor1309

### ISSUE THREAD

**Issue by vmstan** [vmstan/gravity-sync#312]
Seeing the same issue.

_Originally posted by @theDoctor1309 in https://github.com/vmstan/gravity-sync/issues/307#issuecomment-1079952751_

**Comment by theDoctor1309** [comment]
I wiped my server and started fresh. I turned off automate and I am doing manual sync for now. I will turn back on auto and see what happens. I did however play around with it and was able to replicate the issue fast by setting the automate at 5 minutes. My backups with that were also 1.1GB each? I'll set the automate to 15 minutes and post my results.

**Comment by vmstan** [comment]
So when you run a manual sync, there are no errors I assume?

Please post the cron output.

**Comment by theDoctor1309** [comment]
Here is the information at a 15min cron

`root@DNS41:~# gravity-sync cron
∞ Initalizing Gravity Sync (3.6.2)
✓ Loading gravity-sync.conf
✓ Evaluating arguments: CRON
✓ Displaying output of previous jobs
========================================================
Mon 28 Mar 2022 11:47:32 AM EDT
∞ Initalizing Gravity Sync (3.6.2)
✓ Loading gravity-sync.conf
✓ Evaluating arguments: SMART
» Primary Pi-hole: root@10.13.40.3
✓ Validating configuration of OpenSSH
✓ Validating configuration of RSYNC
✓ Validating Gravity Sync folders on DNS41
✓ Validating configuration of Pi-hole
✓ Validating configuration of SQLITE3
✓ Connecting to 10.13.40.3
» Starting SMART Analysis
✓ Hashing the primary Domain Database
✓ Comparing to the secondary Domain Database
! Differences detected in the Domain Database
✓ Hashing the primary Local DNS Records
✓ Comparing to the secondary Local DNS Records
! Replication of Pi-hole settings is required
! Both gravity.db Have Changed
! Primary gravity.db Last Changed
✓ Performing copy of secondary Domain Database
✓ Performing copy of primary Domain Database
✓ Checking Domain Database copy integrity
✓ Pulling the primary Domain Database
✓ Replacing the secondary Domain Database
✓ Validating file ownership on Domain Database
✓ Validating file permissions on of Domain Database
» Isolating regeneration pathways
✓ Updating secondary FTLDNS configuration
✗ Reloading secondary FTLDNS services
========================================================
∞ Gravity Sync CRON exited after 0 seconds
root@DNS41:~# gravity-sync info
∞ Initalizing Gravity Sync (3.6.2)
✓ Loading gravity-sync.conf
✓ Evaluating arguments: INFO
========================================================
Local Software Versions
Gravity Sync 3.6.2
Pi-hole
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)
Linux 5.10.0-13-amd64 x86_64
bash 5.1.4(1)-release
OpenSSH_8.4p1 Debian-5, OpenSSL 1.1.1n  15 Mar 2022
rsync  version 3.2.3  protocol version 31
sqlite3 3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ealt1
Sudo version 1.9.5p2
git version 2.30.2

Local/Secondary Instance Settings
Local Hostname: DNS41
Local Pi-hole Type: default
Local Pi-hole Config Directory: /etc/pihole
Local DNSMASQ Config Directory: /etc/dnsmasq.d
Local Gravity Sync Directory: /root/gravity-sync
Local Pi-hole Binary Directory: /usr/local/bin/pihole
Local File Owner Settings: pihole:pihole
DNS Replication: Enabled (default)
CNAME Replication: Disabled (default)
Verify Operations: Disabled (custom)
Ping Test: Enabled (default)
Backup Folder Size: 3.3G

Remote/Primary Instance Settings
Remote Hostname/IP: 10.13.40.3
Remote Username: root
Remote Pi-hole Type: default
Remote Pi-hole Config Directory: /etc/pihole
Remote DNSMASQ Config Directory: /etc/dnsmasq.d
Remote Pi-hole Binary Directory: /usr/local/bin/pihole
Remote File Owner Settings: pihole:pihole
========================================================
∞ Gravity Sync INFO exited after 0 seconds
root@DNS41:~# ls -llh gravity-sync/backup/
total 3.3G
-rw-r--r-- 1 root root 1.1G Mar 28 11:30 2022-03-28-113008-gravity.db.backup
-rw-r--r-- 1 root root 1.1G Mar 28 11:45 2022-03-28-114510-gravity.db.backup
-rw-r--r-- 1 root root  173 Mar 27 13:52 BACKUP.md
-rw-r--r-- 1 root root 1.1G Mar 28 11:47 gravity.db.pull
root@DNS41:~# 
`

**Comment by theDoctor1309** [comment]
yes I am

**Comment by vmstan** [comment]
So there is a Pi-hole issue with how Debian 11 executes the Pi-hole service restart. I think that is what is showing the failure on the cron task, which stops the script and doesn't allow the hashing file to update or the old backups to purge.

I was able to fix the error on one of my test boxes, I'm looking for the change you need to make...

**Comment by theDoctor1309** [comment]
Looks like you are on the right path. It seems if the cron task does not hiccup, it is able to clear it out. I updated to every 5 min and it self cleared the backup file on the next ryn . Now it sees no changes and is completing without issue. Just added a white list to my primary, and will let you know. Let me know if you need any more testing.

**Comment by vmstan** [comment]
What do you have for the output of `echo $PATH`

**Comment by vmstan** [comment]
Also what do you have for the output of `which service`

**Comment by theDoctor1309** [comment]
Lets see if I can post so this looks right..

```
root@DNS41:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@DNS41:~# which service
/usr/sbin/service
```

**Comment by vmstan** [comment]
Please try and update to 3.6.3 and follow the instructions about recreating your automation task.
https://github.com/vmstan/gravity-sync/wiki/Changelog#363

Make any change to your Pi-hole settings and let the automated replication run, then see if the cron task is clean and there are no backup files left behind.

**Comment by theDoctor1309** [comment]
Done, One thing I can see is a PATH is added to cron every time you change your timer 

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
*/5 * * * * /bin/bash /root/gravity-sync/gravity-sync.sh smart > /root/gravity-sync/logs/gravity-sync.cron

```

**Comment by vmstan** [comment]
Yeah I'm still thinking through a way to make that cleaner. The cron function drops the Path right in before the GS task runs, I didn't want to blindly remove a PATH command that someone else had there for another reason.

**Comment by vmstan** [comment]
How is the status of the backup folder today? Also I just published 3.7.0 which removes cron as the primary automation path in favor of systemd. Would love if you could try it out and let me know.

**Comment by theDoctor1309** [comment]
No issues with the backup folder as of yet, Thanks for that! Just updated and to 3.7 and ran auto to move over the timer.

**Comment by theDoctor1309** [comment]
No issues with backup, and sync seems to be working as needed. Just noticed the number of ./gravity-sync/.git/objects/ seems to be increasing, is that to be expected?

**Comment by vmstan** [comment]
Yeah that should just be due to the nature of Git. The folder shouldn't be more than a couple MB in size?

**Comment by theDoctor1309** [comment]
Sorry should have stated that. Yes the size is fine, just noticed an increase in file count is all. Thank you for confirming. 

```
1.6M    ./gravity-sync/.git
1.9M    ./gravity-sync

```
