### ISSUE TITLE
Issue with "Updating secondary FTLDNS configuration" when 2 docker containers with substring "pihole"

### ISSUE THREAD

**Issue by dotnetjeff** [vmstan/gravity-sync#316]
**Issue Description**
When running ./gravity-sync pull, the "Updating secondary FTLDNS configuration" fails when there are 2 containers with the string "pihole" (or whatever you have specified for ${DOCKER_CON}).

The reason for this appears to be in gs-core when constructing the ${PH_EXEC} command in a docker environment. This gets constructed as

`PH_EXEC="sudo ${DOCKER_BIN} exec $(sudo ${DOCKER_BIN} ps -qf name=${DOCKER_CON}) pihole"`

The issue is that the sub-command `sudo ${DOCKER_BIN} ps -qf name=${DOCKER_CON}` will return multiple container Ids if there are 2 containers with the substring of ${DOCKER_CON}. Unfortunately `docker ps -f` does not do an exact string match. From Docker documentation @[Link:](https://docs.docker.com/engine/reference/commandline/ps/?msclkid=61852dcbafea11ec805e1aa59547deca)

`name
The name filter matches on all **or part** of a container’s name.`

In my case, I had a container named "pihole_exporter" in addition to "pihole" which happened to have its container Id returned first in the results and gravity-sync used that container Id which of course was the wrong container to exec into.

I was able to fix this by changing the line to the following since I don't understand the need for a partial string search and my container name is exact but don't know if that's a proper fix or not.

`PH_EXEC="sudo ${DOCKER_BIN} exec ${DOCKER_CON} pihole"`

Log from failed run:

```
❯ ./gravity-sync.sh pull
∞ Initalizing Gravity Sync (3.7.0)
✓ Loading gravity-sync.conf
✓ Evaluating arguments: PULL
» Primary Pi-hole: jschultzx@192.168.1.21
✓ Validating configuration of OpenSSH
✓ Validating configuration of RSYNC
✓ Validating Gravity Sync folders on artemis
✓ Validating configuration of Pi-hole
✓ Validating configuration of SQLITE3
✓ Connecting to 192.168.1.21
✓ Hashing the primary Domain Database
✓ Comparing to the secondary Domain Database
! Differences detected in the Domain Database
! Replication of Pi-hole settings is required
✓ Performing copy of secondary Domain Database
✓ Performing copy of primary Domain Database
✓ Checking Domain Database copy integrity
✓ Pulling the primary Domain Database

✓ Replacing the secondary Domain Database
✗ Validating file ownership on Domain Database
! Attempting to compensate
✓ Setting file ownership on Domain Database
✓ Validating file permissions on of Domain Database
» Isolating regeneration pathways
✗ Updating secondary FTLDNS configuration
```

**Configuration Details**
```
❯ ./gravity-sync.sh info
∞ Initalizing Gravity Sync (3.7.0)
✓ Loading gravity-sync.conf
✓ Evaluating arguments: INFO
========================================================
Local Software Versions
Gravity Sync 3.7.0
Pi-hole
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)
Linux 5.13.0-35-generic x86_64
bash 5.1.8(1)-release
OpenSSH_8.4p1 Ubuntu-6ubuntu2.1, OpenSSL 1.1.1l  24 Aug 2021
rsync  version 3.2.3  protocol version 31
sqlite3 3.35.5 2021-04-19 18:32:05 1b256d97b553a9611efca188a3d995a2fff712759044ba480f9a0c9e98faalt1
Sudo version 1.9.5p2
git version 2.32.0
Docker version 20.10.13, build a224086

Local/Secondary Instance Settings
Local Hostname: artemis
Local Pi-hole Type: docker
Local Pi-hole Config Directory: /volume1/docker/pihole/pihole
Local DNSMASQ Config Directory: /volume1/docker/pihole/dnsmasq.d
Local Gravity Sync Directory: /home/jschultz/gravity-sync
Local Pi-hole Container Name: pihole
Local Docker Binary Directory: /usr/bin/docker
Local File Owner Settings: 999:999
DNS Replication: Disabled (custom)
CNAME Replication: Disabled (default)
Verify Operations: Disabled (custom)
Ping Test: Enabled (default)
Backup Folder Size: 472K

Remote/Primary Instance Settings
Remote Hostname/IP: 192.168.1.21
Remote Username: jschultzx
Remote Pi-hole Type: docker
Remote Pi-hole Config Directory: /volume1/docker/pihole/pihole
Remote DNSMASQ Config Directory: /volume1/docker/pihole/dnsmasq.d
Remote Pi-hole Container Name: pihole
Remote Docker Binary Directory: /usr/bin/docker
Remote File Owner Settings: 999:999
========================================================
∞ Gravity Sync INFO exited after 1 seconds
```

**Comment by vmstan** [comment]
It used to be the way you have it. As I recall, this was intentionally changed in 3.3 because some container management systems (Docker Swarm) create the container name with a string and then a random string (I think based on the container ID) so it's impossible to track what what the exact match of the container name would be across recreations/reboots.

It might be worth adding a flag to make the pattern search optional. In the meantime you could change the name of your containers to not trigger duplicates.

**Comment by dotnetjeff** [comment]
Yeah, I'm good with workarounds (either changing the container name or keeping my hack in) but just thought I'd report since it's definitely unexpected. Also, I ended up finding this because this error was causing my gravity backup files to never be deleted since it didn't make it to that step in the script. It was just weird that the introduction of a completely separate container would cause my disk to fill up.
