### ISSUE TITLE
Gravity Sync 4.0 SSH Port 

### ISSUE THREAD

**Issue by Ksdmg** [vmstan/gravity-sync#324]
**Issue Description**
The new setup wizard does not ask for a SSH port. The Hidden Figures page is also outdated:
https://github.com/vmstan/gravity-sync/wiki/Hidden-Figures#ssh_port

**Configuration Details**
So in my previous configuration I had added "SSH_PORT='SOMEPORT'" to change the port that gravity sync is using for SSH. This does no longer work. I found out after looking into the script, it is using "GS_SSH_PORT='SOMEPORT'".
You should update the docs and maybe add this config step to the wizard. 

Thanks for making this awesome utility!

**Comment by vmstan** [comment]
🤦‍♂️ I forgot to publish all the changes to that doc. Will have it updated this morning.

**Comment by bakerboy448** [comment]
Is there a way to customize the port in the config / during setup? or can a hotfix be pushed to do so?

I'd say most? many? users wouldn't be using the default SSH port

**Comment by bakerboy448** [comment]
> I'd push back on saying _most_ need this.
> 
> However, can I assume your use case is something like syncing a system outside your LAN through a firewall and using a non-standard port for NAT back to 22?

Nailed it! Though I'm sure some even change the default port on the remote pie as well, but same solution regardless.

Yeah anyone who is syncing external pi's will typically run into this.

Ditto for anyone who's not using the default ssh port locally which isn't best practice as well :)

**Comment by vmstan** [comment]
OK so I'd like you to test something for me.

Update your existing install. `gravity-sync update`
It should show in the git output as something like `HEAD is now at 4.0.0(4)`
This should get you a version that properly switches to dev mode.
Then run `gravity-sync dev` and type `origin/4.0.1` into the prompt, from the list of options.

This should get you the beta for 4.0.1 that is running on a different branch right now.

In this version you can do `gravity-sync config 12345` in which 12345 is the remote target SSH port. Rebuild your configuration file as normal. This should make the config function use the custom port and then commit the change to your `gravity-sync.conf` file.

Please let me know 🙏

**Comment by bakerboy448** [comment]
looks good to me

conf looks good

unrelated, but any idea on this one
```
pi@rasppi-home:/etc/gravity-sync$ gravity-sync compare
∞ Initializing Gravity Sync (4.0.1)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✗ Evaluating arguments ROOT
! pi has insufficient user rights for Gravity Sync
∞ Gravity Sync ROOT exited after 3 seconds
```

proof

```
pi@rasppi-home:/etc/gravity-sync$ cat gravity-sync.conf
# REQUIRED SETTINGS ##########################

REMOTE_HOST='(removed)'
REMOTE_USER='pi'

# CUSTOM VARIABLES ###########################

# Pi-hole Folder/File Customization - Only need to be customized when using containers
# LOCAL_PIHOLE_DIRECTORY=''                         # Local Pi-hole data directory
# REMOTE_PIHOLE_DIRECTORY=''                        # Remote Pi-hole data directory
# LOCAL_DNSMASQ_DIRECTORY=''                # Local DNSMASQ/FTL data directory
# REMOTE_DNSMASQ_DIRECTORY=''               # Remote DNSMASQ/FTL data directory
# LOCAL_FILE_OWNER=''                       # Local file owner for Pi-hole
# REMOTE_FILE_OWNER=''                      # Remote file owner for Pi-hole

# Pi-hole Docker/Podman container name - Docker will pattern match anything set below
# LOCAL_DOCKER_CONTAINER=''                                 # Local Pi-hole container name
# REMOTE_DOCKER_CONTAINER=''                            # Remote Pi-hole container name

# HIDDEN FIGURES #############################
# See https://github.com/vmstan/gravity-sync/wiki/Hidden-Figures
GS_SSH_PORT='24236'
```

**Comment by vmstan** [comment]
Is that running DietPi?

**Comment by vmstan** [comment]
Make sure the pi user is a member of the sudo group.

`usermod -aG sudo pi`

**Comment by vmstan** [comment]
@bakerboy448 you can run `gravity-sync dev` again to toggle yourself off the beta, and into the production build.
