### ISSUE TITLE
sudo: a terminal is required to read the password

### ISSUE THREAD

**Issue by OhjeezwhathaveIdone** [vmstan/gravity-sync#332]
**Issue Description**
After installation of gravity-sync and running the first push, the error `Performing backup of remote Gravity Databasesudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper`

**Configuration Details**
- Fresh install of Ubuntu 20.04
- Fresh install of PiHole

**Comment by MattCarothers** [comment]
That error occurs when the remote user doesn't have passwordless sudo configured.
