### ISSUE TITLE
Configure Automate option to only pull rather than smart

### ISSUE THREAD

**Issue by apainter2** [vmstan/gravity-sync#334]
Hi there,

I would prefer that my secondary pi-hole only PULL from the primary rather than the automated function's smart sync option.

It used to be possible back when gravity-sync used crontab/cronjobs, but since moving to systemd, I do not know how to modify it.

Is this possible, and if so, how?

Thanks,

**Comment by apainter2** [comment]
Solution:

Edit the `/etc/systemd/system/gravity-sync.service` file

Find:
`ExecStart=/usr/local/bin/gravity-sync`

Change to:
`ExecStart=/usr/local/bin/gravity-sync pull`

Save file and exit.

Reload the systemd gravity-sync.service configuration
`sudo systemctl daemon-reload`

Restart gravity-sync.service service:
`sudo systemctl restart gravity-sync.service`

**Comment by cvocvo** [comment]
Notably if you reconfigure with a different timer method such as `gravity-sync auto quad` or `gravity-sync auto hour` it will overwrite the `ExecStart` value and you'll need to re-edit it to include `pull`. Otherwise, this works great. Thanks!
