### ISSUE TITLE
pi has insufficient user rights for Gravity Sync

### ISSUE THREAD

**Issue by tjharman** [vmstan/gravity-sync#336]
**Issue Description**

I have installed GS on both piholes.  On my backup (secondard) pihole I can run "gravity-sync push" or pull and it works fine.  But on my primary I can't, I get this error:

pi@pihole:~$ gravity-sync pull
∞ Initializing Gravity Sync (4.0.2)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✗ Evaluating arguments ROOT
! pi has insufficient user rights for Gravity Sync
∞ Gravity Sync ROOT exited after 1 seconds

**Configuration Details**
How can I debug why I'm getting that error?  The same file exists in /etc/sudoers.d/gs-nopasswd

I can happily run any command using sudo:

pi@pihole:~$ sudo whoami
root

Is there a debug flag or something I can do to see why gs thinks it can't get root somewhere here?

Thanks

**Comment by vmstan** [comment]
Make sure the user is actually in the sudo group. Some distros like DietPi don't add them even though it has that permission.

**Comment by tjharman** [comment]
Thanks @vmstan, that was the problem.
