### ISSUE TITLE
Failed to validatie connection

### ISSUE THREAD

**Issue by wderuijter** [vmstan/gravity-sync#34]
**Describe the Issue**
When running `./gravity-sync.sh config` on the secondary pi hole installation I get past the SSH user/pass for the primary pi hole when I get the output:

```
[ INFO ] Using SSH Key-Pair Authentication
[ FAIL ] Validating Connection to 192.168.1.2

```

When running ssh 'username@ip' i can connect to the primary pi hole through SSH.

**Configuration:**
 - OS for Primary/Secondary: Both running Raspbian GNU/Linux 9 (stretch)
 - Platform for Primary/Secondary: both Raspberry Pi 3B+'s.
 - SSH Server/Client: OpenSSH_7.4p1
 - SSH Authentication: Key-Pair
 - Gravity Sync Version: 1.7.7
 - Pi-hole Versions: v5.0

**Comment by vmstan** [comment]
Did you generate an SSH key in the config script, or did you have one created already? When you manually connect does it ask for a passphrase?

**Comment by wderuijter** [comment]
> Did you generate an SSH key in the config script, or did you have one created already? When you manually connect does it ask for a passphrase?

I've created the key in the config script. I see the key in the secondary pi's /home/admin/.ssh
I see the authorized_keys file on the primary pi is modified at the same.
When I manually connect through SSH to the primary pi hole does not ask for a keyphrase but for the users password.

**Comment by wderuijter** [comment]
Great success @vmstan. Thanks :-)

**Comment by vmstan** [comment]
Great! 1.8 which was just published already has rewrites to the config portion with the goal of bypassing the prompts that were confusing about adding a passphrase to begin with. That portion should be automatic now, you'll just have to authenticate the one time to the primary when you copy your keyfile over. Hopefully to prevent this issue in the future.🤞

**Comment by wderuijter** [comment]
Just pulled the update in. Great clarification of the steps. Thanks @vmstan, this script makes my life even simpler ;-)

**Comment by wderuijter** [comment]
Although I'm running into an issue reconfiguring 1.8:
`<ity-sync$ sudo ./gravity-sync.sh config   
[ INFO ] Gravity Sync 1.8.0 Executing
[  OK  ] Evaluating Arguments: CONFIGURE Requested
[ WARN ] No Active gravity-sync.conf
[  OK  ] Validating SSH Client on raspberrypi (OpenSSH)[  OK  ] Validating RSYNC Installed on raspberrypi
[ EXEC ] Creating gravity-sync.conf from Templatecp: cannot stat '/root/gravity-sync/gravity-sync.conf.example': No such file or directory
[ FAIL ] Creating gravity-sync.conf from Template
pi@raspberrypi:/home/admin/gravity-sync$`

**Comment by vmstan** [comment]
That'

**Comment by vmstan** [comment]
Don't run the script with `sudo` it'll break all kinds of things.

**Comment by vmstan** [comment]
1.8.1 now will detect this.
