### ISSUE TITLE
Gravity Sync only working in one direction.

### ISSUE THREAD

**Issue by tomevison** [vmstan/gravity-sync#342]
**Issue Description**
gravity-sync only seems to be working in one direction:

**[not working]** Commands executed from PI01 to PI02:

`b@PIH01:~$ gravity-sync push
∞ Initializing Gravity Sync (4.0.3)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PUSH
» Remote target brian@10.40.40.14
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
∞ Hashing the remote Gravity Databasemd5sum: /etc/pihole/gravity.db: No such file or directory
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
! DNS Records not detected on the remote Pi-hole
! DNS CNAMEs not detected on the local Pi-hole
! Replication of Pi-hole settings is required
✓ Performing backup of remote Gravity Database
✓ Performing backup of local Gravity Database
✓ Checking Gravity Database copy integrity
✗ Pushing the local Gravity Database

b@PIH01:~$ gravity-sync pull
∞ Initializing Gravity Sync (4.0.3)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PULL
» Remote target brian@10.40.40.14
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
∞ Hashing the remote Gravity Databasemd5sum: /etc/pihole/gravity.db: No such file or directory
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
! DNS Records not detected on the remote Pi-hole
! DNS CNAMEs not detected on the local Pi-hole
! Replication of Pi-hole settings is required
✓ Performing backup of local Gravity Database
✓ Performing backup of remote Gravity Database
✓ Checking Gravity Database copy integrity
✗ Pulling the remote Gravity Database`

**[working]** Commands executed from PI02 to PI01:
`b@PIH02:~$ gravity-sync push
∞ Initializing Gravity Sync (4.0.3)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PUSH
» Remote target brian@10.40.40.13
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
✓ Hashing the remote DNS Records
✓ Comparing to the local DNS Records
! DNS CNAMEs not detected on the local Pi-hole
! No replication is required at this time
∞ Gravity Sync PUSH exited after 18 seconds

b@PIH02:~$ gravity-sync pull
∞ Initializing Gravity Sync (4.0.3)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PULL
» Remote target brian@10.40.40.13
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
✓ Hashing the remote DNS Records
✓ Comparing to the local DNS Records
! DNS CNAMEs not detected on the local Pi-hole
! No replication is required at this time
∞ Gravity Sync PULL exited after 13 seconds`

**Configuration Details**
Same on Both hosts:
- Raspberry Pi 3B
- Ubuntu 22.04 LTS
- Gravity Sync (4.0.3)
- PiHole v5.10 (Running on Docker 20.10.14)

**Comment by ringhidb** [comment]
@tomevison I believe I had this issue too when I first updated to GS4, and consequently installed GS on my primary node (as before it was only on the backup and only did compare/pull via cron).

Are you able to SSH from Pi1 to Pi2 (ssh -p 22 brian@10.40.40.14 from your Pi1?
I was not. Something didn't create/copy correctly when it installed so I had to manually add the RSA key of Pi1 to Pi2 authorized_keys

**Comment by gravufo** [comment]
I also have this issue. The SSH key seems to be added properly. Any other ideas? :(

**Comment by gravufo** [comment]
Fixed it, turns out the sudo setup was not passwordless on the other end, so it was probably blocking on that.
Once I was able to sudo on both machines without password, it worked perfectly.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
