### ISSUE TITLE
Add option to disable sync of group assignments.

### ISSUE THREAD

**Issue by weisrc** [vmstan/gravity-sync#344]
It will be great if there was an option to disable the syncing of user IP and hostname along with anything user related such as comments and group assignments because in some situations, identical IPs are not the same user, at least in the project I am working on.

Is it possible edit the code such that it does not sync the user information?
It will also be great if this becomes something configurable in the config file of Gravity Sync.

Thank you!

**Comment by vmstan** [comment]
Unfortunately not possible with the way it replicates the database. It's an all or nothing thing.

**Comment by weisrc** [comment]
Do you think it is possible to make a copy of the gravity.db, then perform the syncing, and move the group assignments back using SQLite cli? I am asking this because I am not very familiar with the mechanics of PiHole.

Thank you!

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
