### ISSUE TITLE
detect_remote_pihole does not respect REMOTE_DOCKER_BINARY

### ISSUE THREAD

**Issue by timatlee** [vmstan/gravity-sync#349]
**Issue Description**
Testing for the type of remote Pihole installation, I find that 
`REMOTE_DETECT_DOCKER=$(${OS_SSH_CMD} -p ${GS_SSH_PORT} -i "${GS_SSH_PKIF}" ${REMOTE_USER}@${REMOTE_HOST} "sudo docker container ls | grep 'pihole/pihole'" 2>/dev/null)` fails because the command cannot be found. Replacing the line with 

`REMOTE_DETECT_DOCKER=$(${OS_SSH_CMD} -p ${GS_SSH_PORT} -i "${GS_SSH_PKIF}" ${REMOTE_USER}@${REMOTE_HOST} "sudo ${REMOTE_DOCKER_BINARY} container ls | grep 'pihole/pihole'" 2>/dev/null)` yields success, because for whatever unholy reason, Synology installs docker to `/usr/local/bin/docker` instead of the assumed `/usr/bin/docker`.

**Configuration Details**
```
# Pi-hole Docker/Podman container name - Docker will pattern match anything set below
LOCAL_DOCKER_CONTAINER='pihole'
REMOTE_DOCKER_CONTAINER='pihole'                                # Remote Pi-hole container name


REMOTE_PIHOLE_DIRECTORY='/volume1/docker/pihole/pihole'
REMOTE_DNSMASQ_DIRECTORY='/volume1/docker/pihole/dnsmasq.d'
REMOTE_DOCKER_BINARY='/usr/local/bin/docker'
```

**Comment by vmstan** [comment]
Good catch. I'll get this fixed.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
