### ISSUE TITLE
Please add an auto update feature for gravity-sync itself

### ISSUE THREAD

**Issue by ezek1el** [vmstan/gravity-sync#35]
**Is your feature request related to a problem? Please describe.**
It's not.

**Describe the solution you'd like**
Please add an auto update for gravity-sync itself.  Like the auto pull funktion just for new verssions of gravity-sync.

**Describe alternatives you've considered**
make it so that gravity-sync can be run from anywhere not just the installation directory

**Comment by vmstan** [comment]
`./gravity-sync.sh update` is there already.

**Comment by vmstan** [comment]
Were you looking for a different functionality?
