### ISSUE TITLE
Add Option to bypass sudo group check.

### ISSUE THREAD

**Issue by SeeJayEmm** [vmstan/gravity-sync#350]
Please add a configuration option to bypass checking group memberships as part of the root capability check.  Group membership is not required if a proper entry in /etc/sudoers.d/ is provided.

**Comment by brhahlen** [comment]
Agreed.
I had to specifically add a `sudo` group for the check to pass, to be able to use Gravity Sync.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
