### ISSUE TITLE
gravity-sync auto does not add crontab entry

### ISSUE THREAD

**Issue by aram535** [vmstan/gravity-sync#351]
Gravity Sync (4.0.4)

**Issue Description**
Installed gravity-sync on a Ubuntu 20.04.4 LTS VM (192.168.1.3)
Primary PiHole is on a RP (192.168.1.2)
Installed per instructions 
pull and smart both work. 

$ ./gravity-sync auto 
∞ Initializing Gravity Sync (4.0.4)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: AUTOMATE
✓ Customizing service file username
✓ Customizing service file executable path
✓ Randomizing service timers
✓ Stopping existing systemd service
✓ Moving systemd timer into place
✓ Moving systemd service into place
✓ Reloading systemd daemon
✓ Enabling Gravity Sync timer
✓ Starting Gravity Sync service
∞ Gravity Sync AUTOMATE completed after 2 seconds

However no crontab entry is added to user, root, or added to /etc/cron.d

**Configuration Details**
VMWare VM - Ubuntu 20.04.4 LTS
PiHole 3B

Both are running the same version of PiHole:

$ pihole version 
  Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.12)
  FTL version is v5.15 (Latest: v5.15)

**Comment by vmstan** [comment]
4.X doesn't use crontab. Systemd timers are set instead.

**Comment by aram535** [comment]
Ah, didn't think of checking there.  Thank you.

```
# systemctl show gravity-sync.timer 
...
```
