### ISSUE TITLE
What sudo options does gravity-sync need access to?

### ISSUE THREAD

**Issue by accessiblepixel** [vmstan/gravity-sync#353]
I don't know if I've asked this question in the right place, but...

I'm wondering, what commands does gravity-sync need to access via sudo, so that it could be set that it could only access those commands password-less, which would improve security (especially if the password-less SSH key somehow got compromised)

I know you can tell sudo to only allow passwordless access to certain commands and think this might be a sensible way to set it up, just to constrain it's permissions a bit.

I look forward to hearing your thoughts :)

Kind regards,
Jessica

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
