### ISSUE TITLE
Sync does not work on Alpine

### ISSUE THREAD

**Issue by gravufo** [vmstan/gravity-sync#355]
I tried running a gravity sync pull from Alpine and here is what I get:
```
✓ Performing backup of local Gravity Database
∞ Performing backup of remote Gravity Databasetimeout: unrecognized option: preserve-status
BusyBox v1.35.0 (2022-08-01 15:14:44 UTC) multi-call binary.

Usage: timeout [-s SIG] [-k KILL_SECS] SECS PROG ARGS

Run PROG. Send SIG to it if it is not gone in SECS seconds.
Default SIG: TERM.If it still exists in KILL_SECS seconds, send KILL.

✗ Performing backup of remote Gravity Database
```

Is it possible to modify the parameters sent to timeout to support busybox's version? Or is there a workaround I could do on my side to make it work?

Thanks!

**Comment by gravufo** [comment]
Interesting thing, I did a push from the other machine and it worked. Either only the pull is broken, or my setup is not exactly the same on both machines, but they're both on Alpine 3.16...

**Comment by gravufo** [comment]
New info: gravity-sync auto does not work either since it is expecting to have systemd.

**Comment by appuchias** [comment]
Found this too when trying to install it today:
```
∞ Gravity Sync Installation Script
» Validating User Permissions
✓ Sudo utility detected
[sudo] password for <user>:
✓ appu has sudo powers
» Validating Install of Required Components
✓ SSH has been detected
✓ GIT has been detected
✓ RSYNC has been detected
✗ Systemctl not detected on this system
! This is required to automate and monitor Pi-hole replication
» Performing Warp Core Diagnostics
✓ Docker installation has been detected
✓ Docker container of Pi-hole has been detected
» Status Report
✗ 1 critical issue(s) prevent successful deployment
  Please manually compensate for the failures and re-execute
» Exiting Gravity Sync Installer
```

I had previous versions working well a few months ago.
I'm using Alpine Linux 3.15.6 with Pi-Hole running on docker.

As it seems related to timers and automating replications, could cron be an alternative for systems without systemd?

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
