### ISSUE TITLE
Ping a healthcheck URL

### ISSUE THREAD

**Issue by karan** [vmstan/gravity-sync#356]
Be nice to ping a healthcheck URL like healthchecks.io when gravity-sync runs with automation. Specifically for healthchecks.io, it can ping `$BASE_URL/start` and `$BASE_URL/finish` at the start and end of sync respectively.

**Comment by vondruska** [comment]
I ended up creating https://github.com/vondruska/healthcheck-wrapper to solve this problem. Though I'm not sure how nicely it will play with v4, I haven't upgraded from v3 yet.

With the script, my crontab looks like this with v3:

```
*/15 * * * * /usr/scripts/healthcheck-wrapper/wrapper.sh 65c975ff-0000-0000-0000-cac4e6b5657a /bin/bash /path/to/gravity-sync/gravity-sync.sh
```

Uses `/start` and `/finish` along with reporting exit codes so it can record non-successes. The event results in a log that looks like this:

![image](https://user-images.githubusercontent.com/109995/188287959-8d089514-2f0f-465a-b33c-6d9c326a2e0b.png)

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
