### ISSUE TITLE
Performing backup of remote Gravity DatabaseError: No such container: pihole-FTL

### ISSUE THREAD

**Issue by mentalsoup** [vmstan/gravity-sync#357]
**Issue Description**
Pulling or pushing from either of the two instances exhibits the following output:

gravity-sync push
∞ Initializing Gravity Sync (4.0.4)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PUSH
» Remote target user@###.###.#.##
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
✓ Hashing the remote DNS Records
✓ Comparing to the local DNS Records
! Differences detected in the DNS Records
! DNS CNAMEs not detected on the local Pi-hole
! Static DHCP Addresses not detected on the local Pi-hole
! Replication of Pi-hole settings is required
∞ Performing backup of remote Gravity DatabaseError: No such container: pihole-FTL
✗ Performing backup of remote Gravity Database

**Configuration Details**
Both pihole instances are running containerized on docker swarm. The compare command runs without any problem.

**Comment by zenzip** [comment]
same here...

**Comment by hamlynt** [comment]
This error occurs when the pi-hole container name(s) have changed. This can arise due to changes in your pi-hole hostname, or changes in your docker-compose file. 

Re-run the config command on each pi-hole to pick up any new/changed container names on local and remote:
```
gravity-sync config
```

The message `Error: No such container:` should specify the missing container by name, instead of the generic `pihole-FTL`.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
