### ISSUE TITLE
compare and push commands result in access denied and multiple password entries

### ISSUE THREAD

**Issue by EnigmaRaptor** [vmstan/gravity-sync#359]
Having the pi user set up with the same password on both piholes, I try to perform the compare or push actions, and during the entire process I have to type in the password for the OTHER pi user for pretty much every step.  I feel like this is not expected behavior.

**Comment by vmstan** [comment]
If you're getting password prompts by anything when the script runs (after initial installation) then you do not have passwordless sudo configured as required.

**Comment by vmstan** [comment]
https://linuxize.com/post/how-to-run-sudo-command-without-password/

**Comment by EnigmaRaptor** [comment]
Looks like this was due to this issue with the key files: https://github.com/vmstan/gravity-sync/issues/318
