### ISSUE TITLE
Gravity Sync with Synology NAS

### ISSUE THREAD

**Issue by thespica93** [vmstan/gravity-sync#361]
I have 2 pihole docker containers running on 1 synology NAS. Is the NAS the only host? Does that mean I can't run gravity sync?

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
