### ISSUE TITLE
Perform Version Checks On Sync

### ISSUE THREAD

**Issue by My-Random-Thoughts** [vmstan/gravity-sync#363]
Feature Request:  Check the both sides are running the same version (or close enough)

---

I have just spent an hour diagnosing a disk space issue and failing syncs because I am an idiot.

One of my PiHole died and need a rebuild so I installed the latest version of gravity-sync onto it.  I thought I had also installed the latest version on my other PiHole too, but apparently not - it was running v3.something.

The v3 sync was creating massive backup files every 15 minutes (or so) and I woke up this morning with almost no disk space left.
Once I had completely removed v3 and replaced it with the latest v4, it all seems stable for now.  I was also getting the same error message as #219.

Thanks

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
