### ISSUE TITLE
Automating pulls

### ISSUE THREAD

**Issue by Nojwe** [vmstan/gravity-sync#365]
I am running 3 PiHoles and would like 2 of them to automatically pull from the master. I tried `gravity-sync pull quad`, which immediately ran a sync, but has not run again after 30 minutes. Is it possible to automate pulls? Happy to supply any logs that may be useful.

**Comment by vmstan** [comment]
https://github.com/vmstan/gravity-sync/wiki/Automation

**Comment by nilsee1** [comment]
Have the same question (only with 2 piholes).
When running "gravity-sync auto", does it use the Smart/Push or Pull feature? I only want to Pull Nothing more, but changing the command just runes the "pull" immediately. 
How often does the "gravity-sync auto" command does its thing?
Are there longer Intervals then "gravity-sync auto hour"

**Comment by Nojwe** [comment]
@vmstan I've read through that page several times, but it seems to only apply to the command `gravity-sync auto [time]` and doesn't work with push or pull. Can you clarify the intended behavior?

**Comment by Nojwe** [comment]
Here's a workaround: https://github.com/vmstan/gravity-sync/issues/334

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
