### ISSUE TITLE
Sync doesn't work between container and service

### ISSUE THREAD

**Issue by daviddanko** [vmstan/gravity-sync#367]
Hey,

I cannot get the synchronization to work. My setup is an rpi zero with raspberry pi os lite (32bit) running as a service (secondary pihole) and a virtual machine with the latest debian runnnig in a docker container (primary pihole). 

The error I'm getting: Performing backup of local Gravity DatabaseOCI runtime exec failed: exec failed: unable to start container process: exec: "7c327553c14f": executable file not found in $PATH: unknown

**Issuing the push command from the master:**

> network_user@network:~/docker/docker_pihole$ gravity-sync push
> 
> ∞ Initializing Gravity Sync (4.0.4)
> ✓ Loading gravity-sync.conf
> ✓ Detecting local Pi-hole installation
> ✓ Detecting remote Pi-hole installation
> ✓ Gravity Sync remote peer is configured
> ✓ Evaluating arguments: PUSH
> » Remote target pizero@192.168.0.111
> ✓ Validating pathways to Pi-hole
> ✓ Validating pathways to DNSMASQ
> ✓ Hashing the remote Gravity Database
> ✓ Comparing to the local Gravity Database
> ! Differences detected in the Gravity Database
> ✓ Hashing the remote DNS Records
> ✓ Comparing to the local DNS Records
> ! Differences detected in the DNS Records
> ! DNS CNAMEs not detected on the remote Pi-hole
> ! Static DHCP Addresses not detected on the local Pi-hole
> ! Replication of Pi-hole settings is required
> ✓ Performing backup of remote Gravity Database
> ∞ Performing backup of local Gravity DatabaseOCI runtime exec failed: exec failed: unable to start container process: exec: "7c327553c14f": executable file not found in $PATH: unknown
> ✗ Performing backup of local Gravity Database

**Push from the peer (rpi)**

> root@rpi-01:/home/pizero# gravity-sync pull
> ∞ Initializing Gravity Sync (4.0.4)
> ✓ Loading gravity-sync.conf
> ✓ Detecting local Pi-hole installation
> ✓ Detecting remote Pi-hole installation
> ✓ Gravity Sync remote peer is configured
> ✓ Evaluating arguments: PULL
> » Remote target network_user@192.168.0.103
> ✓ Validating pathways to Pi-hole
> ✓ Validating pathways to DNSMASQ
> ✓ Hashing the remote Gravity Database
> ✓ Comparing to the local Gravity Database
> ! Differences detected in the Gravity Database
> ✓ Hashing the remote DNS Records
> ✓ Comparing to the local DNS Records
> ! Differences detected in the DNS Records
> ! DNS CNAMEs has been detected on the remote Pi-hole
> ! DNS CNAMEs not detected on the local Pi-hole
> ! Static DHCP Addresses not detected on the local Pi-hole
> ! Replication of Pi-hole settings is required
> ✓ Performing backup of local Gravity Database
> ∞ Performing backup of remote Gravity DatabaseOCI runtime exec failed: exec failed: unable to start container process: exec: "7c327553c14f": executable file not found in $PATH: unknown
> ✗ Performing backup of remote Gravity Database

The config should be fine, I've checked it several times. 

Attached below: 
[config.txt](https://github.com/vmstan/gravity-sync/files/10058006/config.txt)

Thanks in advance.

**Comment by devzwf** [comment]
check https://github.com/vmstan/gravity-sync/issues/345

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
