### ISSUE TITLE
Issue when upgrading from 3.X to 4.X

### ISSUE THREAD

**Issue by ALittleOfEverything88** [vmstan/gravity-sync#369]
**Issue Description**
Upgraded both my gravity-sync from 3.x to 4.x. On the system running DietPi, when I try to run **any** gravity-sync commands I get the following error:

`∞ Gravity Sync 3.x to 4.0 Migration Utility
`
`
✗ Checking for 3.x Configuration File
`
This then dumps me back to a prompt. How do I get past this issue?
**Configuration Details**

DietPi v8.11.2
Pi 3b

**Comment by MrMittensTheCat** [comment]
I'm having the same issue. 
I tried removing /etc/gravity-sync and reinstalling but to no avail.

**Comment by ALittleOfEverything88** [comment]
I can't remove gravity-sync using the commands; any command I run against gravity-sync (just on this one device) produces the error message above.

I've tried reinstalling over the top (which seems to complete successfully) and then have the same issue.

**Comment by gramsaran** [comment]
I just had this issue today, try to run the following
gravity-sync purge
reboot

then try again

**Comment by ALittleOfEverything88** [comment]
> I just had this issue today, try to run the following gravity-sync purge reboot
> 
> then try again

This worked. Thanks!
