### ISSUE TITLE
Could not resolve host: gravity.vmstan.com

### ISSUE THREAD

**Issue by askthedads** [vmstan/gravity-sync#370]
**Issue Description**

curl -sSL https://gravity.vmstan.com | bash
curl: (6) Could not resolve host: gravity.vmstan.com

**Configuration Details**

**Comment by emanuelsantos2** [comment]
having same issue here
The domain is not returning any records

Tested against multiple upstreams

**Comment by vmstan** [comment]
Sorry about that, I moved DNS providers yesterday and this one didn't come along for the ride. Will have it sorted out soon.

**Comment by vmstan** [comment]
I've updated the installer instructions to just use the file as it's hosted on GitHub

```
curl -sSL https://raw.githubusercontent.com/vmstan/gs-install/main/gs-install.sh | bash
```

I was using a Cloudflare rewrite for that, and need proper time to find a replacement. This should work for now.

**Comment by nickd70s** [comment]
Thanks @vmstan!
