### ISSUE TITLE
Performing backup of remote Gravity Database Fails

### ISSUE THREAD

**Issue by the1wolf** [vmstan/gravity-sync#371]
I've just done an install of gravity-sync on two pi-holes, one is primary, one is secondary.  I've installed gravity-sync with no issues, I ran  gravity-sync compare on PH1,which tells me there are differences in the compared databases.  I then run gravity-sync push from PH1, and then I see there there are differences detected in the gravity database.  I then see performing backup of remote gravity database, and after a few minutes, the first character before "performing backup of remote gravity database" turns red and the operation stops.

I'm new at this and I'm not sure how to fix this error.  I'd sure appreciate any help.

**Comment by the1wolf** [comment]
This can be removed.  Issue resolved.  If anyone reads it, that is.................................

**Comment by adamgreenberg07** [comment]
I am having this exact issue. Did you do anything in particular to resolve it?

**Comment by the1wolf** [comment]
When I tried it originally, I had dietpi installed, with pi-hole and unbound.  After attempting to fix the issue, I found some forums that suggested being on raspbian was a better choice.  I then setup my two pi's with raspbain, pi-hole and unbound.  I ran this command, apt update && apt install sqlite3 sudo git cron rsync ssh, then this, sudo EDITOR=nano visudo, then in this file, I commented out the sudo line and added a line that looks like this, ##%sudo  ALL=(ALL:ALL) ALL, added this, %sudo   ALL=(ALL:ALL) NOPASSWD:ALL.  After this was done a did, sudo reboot now.

Once that was done, I just followed the gravity-sync install guide and it worked.  Hope this will help!!

**Comment by adamgreenberg07** [comment]
thanks for responding. I am on dietpi too with pihoel and unbound. The primary is on a RPi, the other is on a virtual machine. I'd like to avoid redoing both on my piholes. I will try see if a second pihole on a VM not using dietpi will work.

**Comment by the1wolf** [comment]
It's a pain to switch, took me less than a hour total.  I'd like to tell you it will work if you make the switch, but I have no idea.  Keep me posted on your progress.

**Comment by sanegaming** [comment]
I am also having a failed remote backup, I am running this as root in a container and it also keeps prompting me for a password.

**Comment by cesarlaforet** [comment]
> 

same problem

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
