### ISSUE TITLE
Blacklist and Whitelist get not synced 

### ISSUE THREAD

**Issue by GoProAndy** [vmstan/gravity-sync#372]
Hi,
my black- and whitelist get not sync.

how can i fix this?

thanks
Andy

∞ Initializing Gravity Sync (4.0.4)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
∞ Detecting remote Pi-hole installationagent key RSA SHA256:iSUPfpdHLhjjbxX22FB0kLfo1YEIXny52FjzDKCTQYg returned incorrect signature type
✓ Detecting remote Pi-hole installation
∞ Checking on peeragent key RSA SHA256:iSUPfpdHLhjjbxX22FB0kLfo1YEIXny52FjzDKCTQYg returned incorrect signature type
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: SMART
» Remote target root@192.168.96.10
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
» Starting SMART Analysis
∞ Hashing the remote Gravity Databaseagent key RSA SHA256:iSUPfpdHLhjjbxX22FB0kLfo1YEIXny52FjzDKCTQYg returned incorrect signature type
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
agent key RSA SHA256:iSUPfpdHLhjjbxX22FB0kLfo1YEIXny52FjzDKCTQYg returned incorrect signature type
∞ Hashing the remote DNS Recordsagent key RSA SHA256:iSUPfpdHLhjjbxX22FB0kLfo1YEIXny52FjzDKCTQYg returned incorrect signature type
✓ Hashing the remote DNS Records
✓ Comparing to the local DNS Records
agent key RSA SHA256:iSUPfpdHLhjjbxX22FB0kLfo1YEIXny52FjzDKCTQYg returned incorrect signature type
! DNS CNAMEs not detected on the local Pi-hole
agent key RSA SHA256:iSUPfpdHLhjjbxX22FB0kLfo1YEIXny52FjzDKCTQYg returned incorrect signature type
! Static DHCP Addresses not detected on the local Pi-hole
! Replication of Pi-hole settings is required
! Both Gravity Database have changed
agent key RSA SHA256:iSUPfpdHLhjjbxX22FB0kLfo1YEIXny52FjzDKCTQYg returned incorrect signature type
! Local Gravity Database was last changed
∞ Performing backup of remote Gravity Databaseagent key RSA SHA256:iSUPfpdHLhjjbxX22FB0kLfo1YEIXny52FjzDKCTQYg returned incorrect signature type
✓ Performing backup of remote Gravity Database
∞ Performing backup of local Gravity Database
✓ Performing backup of local Gravity Database
✓ Checking Gravity Database copy integrity
✓ Pushing the local Gravity Database
∞ Setting file ownership on Gravity Databaseagent key RSA SHA256:iSUPfpdHLhjjbxX22FB0kLfo1YEIXny52FjzDKCTQYg returned incorrect signature type

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
