### ISSUE TITLE
Gravity sync fails on new install with one host on backup step?

### ISSUE THREAD

**Issue by jmpage2** [vmstan/gravity-sync#373]
I'm not sure if this is a bug or not, but I'm a bit perplexed on what is causing the failure.

Installed & performed configuration of gravity-sync on two recently updated pi-holes.

pi-hole1 
uname -a
Linux pihole1 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

pi-hole2
uname -a
Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

When I do gravity sync-compare it is shown that there are differences in the two (which makes sense as I have been running these two separately for years).

When I try to do push from the one that I want to be the primary the script fails with the following error;
∞ Performing backup of remote Gravity Databasepihole-FTL: invalid option -- 'sql'
Try '/usr/bin/pihole-FTL --help' for more information
✗ Performing backup of remote Gravity Database

When I try to do pull from the one that I want to be the secondary the script fails with the following error;
∞ Performing backup of local Gravity Databasepihole-FTL: invalid option -- 'sql'
Try '/usr/bin/pihole-FTL --help' for more information
✗ Performing backup of local Gravity Database

I have looked at gravity-sync script and can see where it checks the version of pi-hole and modifies the backup script (function backup_local_gravity), but I can't see where I should make the change to resolve the issue, which I assume is related to this pi-hole running on raspberry pi.

Any help would be appreciated.

**Comment by jmpage2** [comment]
Anyone?

**Comment by BinaryPatrick** [comment]
I would try updating your pihole instances to the latest. It looks like in 5.9

**Comment by jmpage2** [comment]
Thanks @BinaryPatrick I can give that a try. I had updated the pi-holes before attempting this, not sure why my revision is older.

**Comment by jmpage2** [comment]
@BinaryPatrick I checked and both of my pi-holes are running 5.14.2 so I don't think this is the issue.

**Comment by jmpage2** [comment]
@BinaryPatrick I was already running 5.14 actually but I did update both pi-holes to the latest version and now it's working, go figure.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
