### ISSUE TITLE
CNAME initial sync

### ISSUE THREAD

**Issue by z3r0d1g1t** [vmstan/gravity-sync#377]
First of all, you are truly a God sent, this was exactly what I have needed for months and months...

I just installed the scritps on two vm's. It seems CNAME's are not synced automatically out of the box. I had to manually write them in on the "slave" server too. After that the sync identified a mismatch, synced and became in sync (before that when using compare on the slave it only said no CNAME records were found on the "slave" server and that a sync was needed).

It might be that it is necessary to only write in one entry for it to trigger correctly, I have not tested this.

Best regards,
Jonas

**Comment by juahan** [comment]
For me it helped if I just created "something" to the slave list, then on next push it did syncronize the full list correctly.

**Comment by systemofapwne** [comment]
I can confirm this.
The fix is rather easy: Instead of just testing, if "05-pihole-custom-cname.conf" exists on the remote end, on could have created that file via "touch" on the remote end in the first place.
