### ISSUE TITLE
on reinstall of pihole, empty new config synced to existing partner

### ISSUE THREAD

**Issue by JYewdall** [vmstan/gravity-sync#379]
Following issues updating a pihole installation, I uninstalled it and reinstalled it. 
After confirmed it was working, I went to its parner and did a gravity-sync push. Thinking it did not work as there was no change on the reinstalled pihole, I did a gravity-sync pull on the new installation. Still blank. I went back to the partner to find it  had a blank config as if pihole had been reinstalled!
I can not find any gravity-sync backups. Where are they

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
