### ISSUE TITLE
Failing to push/pull Gravity Databases

### ISSUE THREAD

**Issue by YamiYukiSenpai** [vmstan/gravity-sync#380]
**Issue Description**
I'm having issues pulling or pushing 2 gravity databases

**Configuration Details**
```
$ gravity-sync push
∞ Initializing Gravity Sync (4.0.4)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PUSH
» Remote target piholeGravitySync@192.168.100.5
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
✓ Hashing the remote DNS Records
✓ Comparing to the local DNS Records
! Differences detected in the DNS Records
! DNS CNAMEs not detected on the local Pi-hole
! Static DHCP Addresses not detected on the local Pi-hole
! Replication of Pi-hole settings is required
∞ Performing backup of remote Gravity Databasesudo: unable to resolve host phole2-Pi3B: Name or service not known
✓ Performing backup of remote Gravity Database
∞ Performing backup of local Gravity Databasesudo: unable to resolve host phole3-Pi3B: Name or service not known
✓ Performing backup of local Gravity Database
✓ Checking Gravity Database copy integrity
✗ Pushing the local Gravity Database
```

Not sure what I could be doing wrong.

The only other thing I did is ensure that the user I added a visudo entry for  "piholeGravitySync":

```
piholeGravitySync       ALL=(ALL)       NOPASSWD:/usr/local/bin/gravity-sync,/usr/local/bin/pihole,/usr/bin/pihole-FTL
```

**Comment by llamalump** [comment]
I think these two lines are your problem:

> ```
> ∞ Performing backup of remote Gravity Databasesudo: unable to resolve host phole2-Pi3B: Name or service not known
> ```

> ```
> ∞ Performing backup of local Gravity Databasesudo: unable to resolve host phole3-Pi3B: Name or service not known
> ```

Seems like DNS resolution isn't working properly. What happens if you run `ping phole3-Pi3B`? Is there a typo in your configuration where you missed the letter 'i', and the hostname should really be `pihole3-Pi3B`?

**Comment by YamiYukiSenpai** [comment]
> Seems like DNS resolution isn't working properly. What happens if you run `ping phole3-Pi3B`? Is there a typo in your configuration where you missed the letter 'i', and the hostname should really be `pihole3-Pi3B`?

Fixed that when I added 127.0.1.1

```
$ sudo -u piholeGravitySync gravity-sync push
∞ Initializing Gravity Sync (4.0.4)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PUSH
» Remote target piholeGravitySync@192.168.100.5
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
✓ Hashing the remote DNS Records
✓ Comparing to the local DNS Records
! Differences detected in the DNS Records
! DNS CNAMEs not detected on the local Pi-hole
! Static DHCP Addresses not detected on the local Pi-hole
! Replication of Pi-hole settings is required
✓ Performing backup of remote Gravity Database
∞ Performing backup of local Gravity Database[sudo] password for piholeGravitySync: 
✓ Performing backup of local Gravity Database
✓ Checking Gravity Database copy integrity
✗ Pushing the local Gravity Database
```

Still doesn't work

**Comment by rst-ack** [comment]
Not sure why it's still asking for a sudo password in spite of your sudo rule, which looks fine to me. I'm guessing you have, but to cover all bases: have you configured that same sudo rule on both pihole machines?

**Comment by YamiYukiSenpai** [comment]
I fixed that part by re-arranging the order of my sudo rules.

Other than that, same issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YamiYukiSenpai** [comment]
Figured out why.

I only found out about `gravity-sync sudo` which I didn't use when I set it up.

My issue with it is that it does ALL commands, which I'm not comfortable with.

I'll work on making it more restricted in sudoers.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
