### ISSUE TITLE
Issue Connecting to Remote Docker PiHole instance from Secondary DietPi Install

### ISSUE THREAD

**Issue by ALittleOfEverything88** [vmstan/gravity-sync#381]
**Issue Description**
When configuring gravity-sync on my DietPi install, eveything seems to run smoothly until near the end. The script connects to the remote host, lists the docker containers, and then craps out with the following error:

`∞ Examining remote container configurationbash: line 1: /tmp/local_container_pihole_etc.log: Permission denied
bash: line 1: /tmp/local_container_dnsmasq_etc.log: Permission denied
✗ Examining remote container configuration`

**Configuration Details**

Host1: Ubuntu 20.04 running latest PiHole docker
Host2: DietPi 8.14.2 running PiHole directly (no docker)

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
