### ISSUE TITLE
Feature Request? Can Gravity-Sync restart DNS resolver so domain whitelist/blocklist/adlist takes effect immediately?

### ISSUE THREAD

**Issue by northportio** [vmstan/gravity-sync#382]
I've tested gravity sync by blocking example.com and it seems to take forever for the domain to stop resolving. For any change to take effect, you have to restart the dns resolver see [here](https://discourse.pi-hole.net/t/how-do-i-flush-my-pi-hole-cache/3020). Can gravity sync restart the dns resolver automatically after any push/pull/sync? Thanks.

**Comment by vmstan** [comment]
It should be reloading the list into the cache, but if your local system has already resolved it it might need to expire there?

I used to do a full restart but that flushed the cache and people complained that it would result in more outbound queries.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
