### ISSUE TITLE
It writes garbage into syslog and so syslog locks up.

### ISSUE THREAD

**Issue by rayvt** [vmstan/gravity-sync#383]
Evidently what gets logged includes color codes(??) as part of the text.  Attached is a tail of syslog.  At this point it locks up and nothing further can be seen.  Doing a tail -f /var/log/syslog, nothing else every shows up.

--------------------------------
Here's what I get:
Sluggo>tail /var/log/syslog                                                                                                                                                                   /etc/gravity-sync
Feb 22 16:59:10 Sluggo gravity-sync[1335]: #033[0;93mÂ»#033[0m #033[0;93mStarting SMART Analysis#033[0m
Feb 22 16:59:11 Sluggo gravity-sync[1335]: #033[0;96mâ#033[0m Hashing the remote Gravity Database
Feb 22 16:59:12 Sluggo gravity-sync[1335]: #033[0;96mâ#033[0m Comparing to the local Gravity Database
Feb 22 16:59:14 Sluggo gravity-sync[1335]: #033[0;96mâ#033[0m Hashing the remote DNS Records
Feb 22 16:59:14 Sluggo gravity-sync[1335]: #033[0;96mâ#033[0m Comparing to the local DNS Records
Feb 22 16:59:15 Sluggo gravity-sync[1335]: #033[0;95m!#033[0m #033[0;95mDNS CNAMEs not detected on the local Pi-hole#033[0m
Feb 22 16:59:16 Sluggo gravity-sync[1335]: #033[0;95m!#033[0m #033[0;95mStatic DHCP Addresses not detected on the local Pi-hole#033[0m
Feb 22 16:59:16 Sluggo gravity-sync[1335]: #033[0;95m!#033[0m #033[0;95mNo replication is required at this time#033[0m
Feb 22 16:59:16 Sluggo gravity-sync[1335]: #033[0;95mâ%

----------
Doing od -a on syslog reveals that text is there, but both cat and tail lock up.

```
0034173   F   e   b  sp   2   2  sp   1   6   :   5   9   :   1   6  sp
0034213   S   l   u   g   g   o  sp   g   r   a   v   i   t   y   -   s
0034233   y   n   c   [   1   3   3   5   ]   :  sp   #   0   3   3   [
0034253   0   ;   9   5   m   !   #   0   3   3   [   0   m  sp   #   0
0034273   3   3   [   0   ;   9   5   m   S   t   a   t   i   c  sp   D
0034313   H   C   P  sp   A   d   d   r   e   s   s   e   s  sp   n   o
0034333   t  sp   d   e   t   e   c   t   e   d  sp   o   n  sp   t   h
0034353   e  sp   l   o   c   a   l  sp   P   i   -   h   o   l   e   #
0034373   0   3   3   [   0   m  nl   F   e   b  sp   2   2  sp   1   6

```

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
