### ISSUE TITLE
Speed Settings

### ISSUE THREAD

**Issue by mulcade** [vmstan/gravity-sync#387]
Looking at the speed settings, I see there are options for quarter, half, and whole hour sync speed.  I don't have a need for that much syncing in my environment (home network for mostly just ad blocking).  Is there a way to set or add the option to only sync once a day or every x hours?  I have both pihole instances on Pis and would like to limit the traffic on the SD cards.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
