### ISSUE TITLE
Select Sync Request

### ISSUE THREAD

**Issue by dcmarimba** [vmstan/gravity-sync#391]
Hi,

Can I make a change request? I'd like to sync all my adlist entries, white and blacklists but not my DNS entries/clients/groups.

Is that possible? Or would that involve modifying the database in transit?

I have two instances, but have split DNS and different client logic on my second instance..

Thanks

Daniel

**Comment by IonCaza** [comment]
+1 here. Is there any way to NOT sync local DNS? Running pihole in 2 separate locations, but want the whitelists syncd.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
