### ISSUE TITLE
How to sync Pihole MacVlan container with no :port?

### ISSUE THREAD

**Issue by janaxhell** [vmstan/gravity-sync#393]
I have 2 Piholes, primary in a Docker container using a MacVlan IP with no port, secondary on bare metal with standard :port 22.
While I can connect primary to secondary, I cannot do the other way around because "Hashing the remote Gravity Database ssh: connect to host 192.168.1.2 port 22: Connection refused" 
I have tried gravity-sync config with no argument, with 5335 (I use unbound on both Piholes), and trying both host and MacVlan IPs.
How can I do this?
Primary Pihole = 192.168.1.2 (MacVlan inside 192.168.1.168 host)
Secondary Pihole = 192.168.1.158 (bare metal)

**Comment by wblew** [comment]
I have two Pi-holes, each on a different Raspi. They are both docker containers that are using MacVlan. I have gravity-sync running on the host Ubunt OS. Similar to your setup it would seem. How did I do it?

Use gravity-sync on the docker container's HOST operating system. This will require bind mounts for the container's` /etc/dnsmasq.d`, `/etc/pihole`, and maybe `/var/logs/pihole`, directories.

As an example, here are relevant bits of my `/etc/gravity-sync.conf` file. **NOTE! Your setup will likely NEED changes from my settings!**

```
# CUSTOM VARIABLES ###########################

# Pi-hole Folder/File Customization - Only need to be customized when using containers
LOCAL_PIHOLE_DIRECTORY='/docker/pihole/etc-pihole'
REMOTE_PIHOLE_DIRECTORY='/docker/pihole/etc-pihole'
LOCAL_DNSMASQ_DIRECTORY='/docker/pihole/etc-dnsmasq.d'
REMOTE_DNSMASQ_DIRECTORY='/docker/pihole/etc-dnsmasq.d'
LOCAL_FILE_OWNER='999:999'
REMOTE_FILE_OWNER='999:999'
```

I recommend the [System Requirements ](https://github.com/vmstan/gravity-sync/wiki/System-Requirements)  page.

Best of luck!

**Comment by janaxhell** [comment]
Hi, thanks for your reply. May I ask you a few more hints? Since only one of my Piholes is on MacVlan, I assume I have to set this configuration only on the other one. 
My current gravity-sync.conf on **MacVlan Pihole** looks like this:

```
# CUSTOM VARIABLES ###########################

# Pi-hole Folder/File Customization - Only need to be customized when using containers
LOCAL_PIHOLE_DIRECTORY='/srv/dev-disk-by-uuid-aeae213f-8ce4-405c-9d96-db90e69c28f8/Config/pihole/etc-pihole'
# REMOTE_PIHOLE_DIRECTORY=''                        # Remote Pi-hole data directory
LOCAL_DNSMASQ_DIRECTORY='/srv/dev-disk-by-uuid-aeae213f-8ce4-405c-9d96-db90e69c28f8/Config/pihole/etc-dnsmasq.d'
# REMOTE_DNSMASQ_DIRECTORY=''               # Remote DNSMASQ/FTL data directory
LOCAL_FILE_OWNER='999:999'
# REMOTE_FILE_OWNER=''                      # Remote file owner for Pi-hole
```
My gravity-sync.conf on **bare metal Pihole** looks like this:

```
# CUSTOM VARIABLES ###########################

# Pi-hole Folder/File Customization - Only need to be customized when using containers
# LOCAL_PIHOLE_DIRECTORY=''                         # Local Pi-hole data directory
# REMOTE_PIHOLE_DIRECTORY=''                        # Remote Pi-hole data directory
# LOCAL_DNSMASQ_DIRECTORY=''                # Local DNSMASQ/FTL data directory
# REMOTE_DNSMASQ_DIRECTORY=''               # Remote DNSMASQ/FTL data directory
# LOCAL_FILE_OWNER=''                       # Local file owner for Pi-hole
# REMOTE_FILE_OWNER=''                      # Remote file owner for Pi-hole

# Pi-hole Docker/Podman container name - Docker will pattern match anything set below
# LOCAL_DOCKER_CONTAINER=''                                 # Local Pi-hole container name
# REMOTE_DOCKER_CONTAINER=''                            # Remote Pi-hole container name

# HIDDEN FIGURES #############################
# See https://github.com/vmstan/gravity-sync/wiki/Hidden-Figures
GS_SSH_PORT='5335'
```

Should I just copy the MacVlan Volumes as REMOTE_PIHOLE_DIRECTORY= in bare metal gravity-sync.conf?

Also, my user id in both Hosts is 1000:1000, should I use that, or the already present LOCAL_FILE_OWNER='999:999'? 
Is that a special user id?

Finally, I use Unbound on both, is bare metal gravity-sync.conf showing GS_SSH_PORT='5335' only because it's not inside a container? The MacVlan one doesn't have that line.

**Comment by janaxhell** [comment]
_It is the container host's UID and GID under which the Container's Pi-hole processes are running. They are the PIHOLE_UID, and PIHOLE_GID environment variable values that you pass into Pi-hole's container. (They are in a docker-compose.yml file in my case)._

I haven't set any PUID/PGID for Pihole in container and I cannot find any in the Portainer page of Pihole. Anyway when I deploy a stack that wants an explicit PUID:PGID I use the admin one, which is 996:100. But in this case the user that I've set for gravity-sync is 'janx' which id is 1000:1000 so I'm not sure what to set. 'janx' is a sudo user that can ssh to both machines, I have created it just for the purpose.

_An SSH port of 5335 is weird to me._

It comes from the Unbound settings, in the Upstream DNS Server settings I have 127.0.0.1#5335 on both Piholes. I was asking about it because it seems strange to me that having the same exact configuration, one gravity-sync.conf shows it and the other not, but as a matter of fact, I still haven't connected the two Piholes, so maybe it will be added as soon as they see each other.

**Comment by wblew** [comment]
_which id is 1000:1000 so I'm not sure what to set..._

The idea is to set the gravity-sync PUID and PGID settings correctly, given the Pi-hole container's settings (it does have defaults...). Setting them correctly ensures the container Pi-hole can still access its files after any gravity-sync updates.

You can `ls -l` the Pi-hole container's `/etc/pihole/gravity.db` file within its host filesystem. Use that file's UID and GID values for the gravity-sync PUID and PGID values.

The UID is the 2nd field, the GID is the 3rd field of the `ls -l` command's file listings.

_minimal CLI Armbian distro_

No idea, as I am not familiar with Armbian. However when I googled _armbian distro static ip_ this was the first hit:

[How to set a Static IP on Armbian](https://www.albertogonzalez.net/how-to-set-a-static-ip-on-armbian/)

_Where do I write that? I have cd to /etc/systemd , but I see several .conf files.._

Once you have things working... just execute the `gravity-sync auto` command. It will do the `systemd` fiddling and such to automate things for you.

**Comment by wblew** [comment]
_Is that warning an actual problem?_

In my opinion? no. So long as the Pi-hole servers' IP address remain unchanged, all is good. After all, the clients would lose DNS service were they to change, right? It just makes the Pi-hole servers' IP addresses dependent on the DHCP server.

Some purists might squak some... meh.

**Comment by janaxhell** [comment]
Thanks you for all the help wblew!

**Comment by wblew** [comment]
You are most welcome!

**Comment by Leethal1977** [comment]
Trying to resolve a very similar issue (I have pihole running on bare metal RPi and on docker container within Synology NAS).  The above makes really good sense - but despite hours of trying, I keep hitting the error that GIT has not been detected on the docker instance.  I have tried everything to install GIT (I think I can work the rest of the config out once GIT, and then gravity-sync is installed on the host of the NAS pihole container), but I have hit a brick wall - any suggestions please?
