### ISSUE TITLE
curl: (6) Could not resolve host: gravity.vmstan.com

### ISSUE THREAD

**Issue by notmynormalusername** [vmstan/gravity-sync#394]
Hello while I am trying to install the gravity sync for my pi holes I run the command

export GS_INSTALL=primary && curl -sSL https://gravity.vmstan.com | bash

However I get the following error

curl: (6) Could not resolve host: gravity.vmstan.com

**Comment by notmynormalusername** [comment]
Ignore this, I cant read I was using an older guide it appears.

**Comment by ayoahha** [comment]
...Sorry for this question, but i am following a 2021 guide (which i think is not really old)... and of course i have the same error as you...
How did you do exactly ?

**Comment by Tam-Lin** [comment]
No, it's still a problem; it's referenced on the "How to upgrade gravity-sync pages", for example (https://github.com/vmstan/gravity-sync/wiki/Updating)

**Comment by vmstan** [comment]
> No, it's still a problem; it's referenced on the "How to upgrade gravity-sync pages", for example (https://github.com/vmstan/gravity-sync/wiki/Updating)

Fixed.
