### ISSUE TITLE
Gravity-sync config failing to detect Pihole container on peer

### ISSUE THREAD

**Issue by ghost** [vmstan/gravity-sync#395]
Hey folks, Was hoping to get some help with Gravity Sync, having some strange issues with setup..

Here's a quick run down of my setup, I'm running two latest Pihole Instances in Docker Containers.

My main Instance is running on a DietPi 4 (8GB), and my second Instance is running on a OMV Debian Based Server.

All required software is installed to my knowledge.

Gravity-sync installs successfully on both peers, however when I start the configuration and attempt to connect to a peer via ssh, it will either connect aokay on one peer but not the other stating permission denied apon SSH connect.

When I tried purging both installs, The same thing happened but issue flipped.

Eventually it connected but couldn't detect the pihole instance on the second Peer.. only synced adlists...

Any ideas? Am I having public key issues, or perhaps I've misconfigured my users?

**Comment by gjunkie** [comment]
I'm having similar issues. Unable to detect peers on either instance. Running both Piholes on docker on identical Ubuntu machines. Did you figure it out?

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
