### ISSUE TITLE
Backup of remote OR local database fails, when another container with "pihole" in the name is present.

### ISSUE THREAD

**Issue by Scaredycrow** [vmstan/gravity-sync#397]
Hypothesis: The logic used to detect the pihole container ID is incorrectly matching on containers containing, or at maybe beginning with the string entered in the setup process, which is incorrectly catching the pihole-exporter container rather than the expected pihole container. 

Setup: 
2 Hosts - Ubuntu Server 22.04 
2 Pi-hole instances, both official docker container versions. 
In both instances containers are named "pihole" 
On host 2, another container is running pihole-exporter for grafana / prometheus in a container named "pihole-exporter" 

Deploy install script - no issues.
Run Compare - no issues
Run push - Fails on backup of remote. 

Switching to remote
Run Pull - Fails on local backup. 
Error message indicates a contaner ID which matches a container named "pihole-exporter" on my host. Stopping that container immediately resolves the Push / Pull failures and all works as expected. 

Error message: `∞ Performing backup of local Gravity DatabaseOCI runtime exec failed: exec failed: unable to start container process: exec: "15c68d9249db": executable file not found in $PATH: unknown`

**Comment by wblew** [comment]
Have you verified this issue is present on the https://github.com/vmstan/gravity-sync/tree/4.0.5 branch? I am asking because it sounds similar to an issue that is already fixed by #390 on that branch.

**Comment by Scaredycrow** [comment]
> Have you verified this issue is present on the https://github.com/vmstan/gravity-sync/tree/4.0.5 branch? I am asking because it sounds similar to an issue that has been fixed by PR #390 on that branch.

I installed based on the curl command in the wiki ~4 hours ago and it's showing version 4.0.4. 

Reading the linked PR, it indeed sounds like that should solve this issue.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
