### ISSUE TITLE
Script fails when Docker containers have similar names (pihole, pihole_exporter, etc.)

### ISSUE THREAD

**Issue by mauronogueira** [vmstan/gravity-sync#398]
**Issue Description**
When you have docker containers using similar names, the script will fail to perform the sync. The issue happens when the gravity database backup is running.

```
OCI runtime exec failed: exec failed: unable to start container process: exec: "e296056806d0": executable file not found in $PATH: unknown
✗ Performing backup of remote Gravity Database
```

**Configuration Details**
- `pihole` which runs my pihole instance
- `pihole_exporter` which runs analytics export for Grafana.

Once I changed my container name from `pihole_exporter` to `pi-hole_exporter` the script worked perfectly.

**Comment by wblew** [comment]
Fixed in https://github.com/vmstan/gravity-sync/pull/390. It's in the next release (4.0.5)

You can test the 4.0.5 beta using the `gravity-sync dev` command. Select the `origin/4.0.5` branch.
