### ISSUE TITLE
Docker Snap install

### ISSUE THREAD

**Issue by static09** [vmstan/gravity-sync#399]
**Issue Description**
Docker executable on Ubuntu now located in `/snap/bin/docker` instead of `/usr/bin/docker`. 

Attempting to run `gravity-sync push` on Ubuntu 22.04.2 LTS results in error `/usr/bin/docker: command not found` when backing up Gravity database. Output of `which docker` results in `/snap/bin/docker`.

Editing Line 40 in `/usr/local/bin/gravity-sync`

From: ``LOCAL_DOCKER_BINARY=`/usr/bin/docker` ``
To: ``LOCAL_DOCKER_BINARY='/snap/bin/docker` ``

has resolved issues with backing up the local Gravity database.

**Configuration Details**
lsb_release -a
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```
docker version
```
Client:
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.20.4
 Git commit:        297e128
 Built:             Wed May 24 23:30:52 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       5d6db84
  Built:            Wed May 24 23:31:22 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Two PiHoles running in Docker containers on separate hosts. Version info for both:
 ```
Pi-hole v5.17.1 
 FTL v5.23 
```

**Comment by static09** [comment]
I didn't see the other variables could be placed in gravity-sync.conf until just now.

Adding `LOCAL_DOCKER_BINARY='/snap/bin/docker'` to `/etc/gravity-sync/gravity-sync.conf` is a viable correction.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
