### ISSUE TITLE
Using gravity-sync with Pi-Hole-for-WSL1

### ISSUE THREAD

**Issue by cristacheda** [vmstan/gravity-sync#401]
Hello! I am running [[Pi-Hole-for-WSL1](https://github.com/DesktopECHO/Pi-Hole-for-WSL1)] on a Windows PC and another instance of Pi-hole on a Raspberry Pi. Is there any way to use gravity-sync between the two?

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
