### ISSUE TITLE
QUESTION - how to upgrade minor versions

### ISSUE THREAD

**Issue by chupacabra71** [vmstan/gravity-sync#402]
Currently running 4.0.3, looks like 4.0.5 is the latest.  I can't find upgrade instructions for minor versions.  is it just re-install and recreate the config?

**Comment by My-Random-Thoughts** [comment]
[`gravity-sync update`](https://github.com/vmstan/gravity-sync/wiki/Updating)

**Comment by chupacabra71** [comment]
Thank you!
