### ISSUE TITLE
Support syncing dhcp.leases 

### ISSUE THREAD

**Issue by edalquist** [vmstan/gravity-sync#405]
I'm using split-scope DHCP but I make fairly heavy use of `dhcp-host` entries to provide static IPs and concrete host names. Unfortunately that means DNSMasq only resolves those local host names if they are in its dhcp.leases file.

Including dhcp.leases in the set of synchronized files would ensure that either pihole is able to resolve local names for dynamically named hosts

**Comment by edalquist** [comment]
For people doing split-scope DHCP like me the sync would need to be a merge where the files from both pi's are combined with some basic logic to avoid duplicate entries for the same MAC

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
