### ISSUE TITLE
Syncing "Disable Blocking" status

### ISSUE THREAD

**Issue by ggitthub** [vmstan/gravity-sync#406]
Syncing the whitelist etc. is a very nice feature, but what I actually desire even more, is syncing the "Disable Blocking" status between two instances. I "frequently" (maybe once a week or less) use a bookmark, that disables Pi-hole for 30 seconds (either because I want a tracking site to work for cashback, or I suspect Pi-hole has broken a website, so I want to test without it). But having two Pi-holes means, I have to disable both of them (with separate bookmarks) to be sure I get the result I want.

Now that gravity-sync is normally checking the config every 5 minutes, this would not be sufficent for the disable status, But maybe you have an idea how it could be implemented (or have a different suggestion how to disable two intances with "one click"), that would be great.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
