### ISSUE TITLE
auto sync

### ISSUE THREAD

**Issue by hrolofs** [vmstan/gravity-sync#409]
Hello,

i have installed gravity-sync on both pihole system, and it works. :-)

One question to the auto mode. 

Do i have to activate the auto mode on only one of the piholes or on both?

This was not clear for me on the wiki.

Regards, Henry

**Comment by mk-in** [comment]
Both. 

From Wiki 
`Automation of sync is accomplished by adding an execution of the script to **each** host's systemd configuration.`

**Comment by hrolofs** [comment]
Thanks for the clarification.
