### ISSUE TITLE
Could not resolve host: raw.githubusercontent.com

### ISSUE THREAD

**Issue by alexnt85** [vmstan/gravity-sync#414]
Installed gravity sync normally on 1st pihole but I have trouble installing on 2nd.
I'm getting 
`curl -sSL https://raw.githubusercontent.com/vmstan/gs-install/main/gs-install.sh | bash
curl: (6) Could not resolve host: raw.githubusercontent.com
`
Am I doing something wrong?

**Comment by vmstan** [comment]
At first glance it looks like DNS isn't working on the second. What is the result of just `ping raw.githubusercontent.com`

**Comment by alexnt85** [comment]
Same. Even pinging. It's a fresh installation and it could resolve and install pihole package before this problem. I can't undersetand why it has topped resolving names.

**Comment by alexnt85** [comment]
> At first glance it looks like DNS isn't working on the second. What is the result of just `ping raw.githubusercontent.com`

Same. Even pinging. It's a fresh installation and it could resolve and install pihole package before this problem. I can't undersetand why it has topped resolving names.

**Comment by vmstan** [comment]
It's likely that the Pi-hole configuration is set in a way that isn't able to resolve addresses, and the local system is trying to use that it for DNS lookups.

**Comment by alexnt85** [comment]
> It's likely that the Pi-hole configuration is set in a way that isn't able to resolve addresses, and the local system is trying to use that it for DNS lookups.

Does unbound affect gravity sync? I suppose it doesn't.

**Comment by vmstan** [comment]
> > It's likely that the Pi-hole configuration is set in a way that isn't able to resolve addresses, and the local system is trying to use that it for DNS lookups.
> 
> 
> 
> Does unbound affect gravity sync? I suppose it doesn't.

No. Gravity Sync doesn't care what your resolvers look like so long as they're functional.

**Comment by alexnt85** [comment]
> > > It's likely that the Pi-hole configuration is set in a way that isn't able to resolve addresses, and the local system is trying to use that it for DNS lookups.
> > 
> > 
> > Does unbound affect gravity sync? I suppose it doesn't.
> 
> No. Gravity Sync doesn't care what your resolvers look like so long as they're functional.

It was my mistake and I leave it here for future referance. It was `sudo systemctl disable --now unbound-resolvconf.service`.
I had accidentally run the command above and then it could not resolve anything.
