### ISSUE TITLE
Support for Pi-hole v6

### ISSUE THREAD

**Issue by dbobak** [vmstan/gravity-sync#415]
As Pi-hole [announced start of beta testing of new v6 version](https://pi-hole.net/blog/2023/10/09/pi-hole-v6-beta-testing/#page-content), are you planning Gravity-sync to support this version?

best,
Darek

**Comment by vmstan** [comment]
I'll have to take a look and see what's changed under the covers. They don't mention anything that would impact how it works, unless the data for antigravity is stored somewhere new.

**Comment by Ramalama2** [comment]
Thanks stan for still supporting and updating gravity-sync!
i had already fears that you wont continue with v6 :-)

**Comment by CryPt00n** [comment]
Hey, any update on this?

**Comment by vmstan** [comment]
Have there been issues?

**Comment by CryPt00n** [comment]
> Have there been issues?

Oh, no. Just wanted to asks if it's tested or ready for current v6 state. But if there is nothing bad or breaking known then I'll give it a try and update two testing instances to v6

**Comment by CryPt00n** [comment]
@vmstan Running into some problems on v6. When trying to sync, it does not include DNS and CNAME. Just upgraded my v5 environment to v6, and no further changes were made.

![grafik](https://github.com/vmstan/gravity-sync/assets/38314677/ffe6689e-0167-4fea-8bb6-de2b329b175a)

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
