### ISSUE TITLE
Quick question because i'm not sure 

### ISSUE THREAD

**Issue by Spleenftw** [vmstan/gravity-sync#416]
i have two piholes : 
the main, .53 and the secondary, .54 : do i have to run the gravity-sinc auto on BOTH of them if i want like a "master - slave" synchronization ? I only want to make changes on the .53 and that it automatically replicate on the slave .54

**Comment by vmstan** [comment]
No. Just run it on one of them.

**Comment by vmstan** [comment]
Just make sure the first time you run it that you do a push or a pull depending on where it is installed and what is the authority.

Example: install on primary, push to secondary.

**Comment by Spleenftw** [comment]
Oh so i don't have to install it on the secondary pi-hole at all

**Comment by vmstan** [comment]
You don't have to, it would work like it did prior to 4.0, I would only so you have it if you wanted to manually run it there.

https://github.com/vmstan/gravity-sync/wiki/4.0#rearchitected-deployment

I refer to it as "peerless mode"

**Comment by Spleenftw** [comment]
Okay so i did a gravity-sync auto on the .53, and simply an install on the .54, seems like it's working like a charm
