### ISSUE TITLE
Docker Pi Hole User and Group UID

### ISSUE THREAD

**Issue by sudo-kraken** [vmstan/gravity-sync#417]
I cant update my UID and GID to use for each pi hole instance as they run as non standard ID's i.e primary = 1000 and 988 and Secondary runs on 1000 and 997

Is there a way to update this ?

**Comment by sudo-kraken** [comment]
I have to exec in and manually alter it with chmod commands for the pihole user, it may be better to alter gravity sync to use names for users and not ID's ?

**Comment by vmstan** [comment]
https://github.com/vmstan/gravity-sync/wiki/Hidden-Figures

LOCAL_FILE_OWNER and REMOTE_FILE_OWNER are probably what you're looking for.

**Comment by sudo-kraken** [comment]
how do you set these though? do i need to run config again on both or just one

**Comment by sudo-kraken** [comment]
Sorry to reopen this but even with these set it is setting the user to 33 on dnsmasq.d folder and the files within to 0 (root) where is it getting 33 from this is also the case on /etc/pihole with it being 33 and only 1 or two files set to 999.

**Comment by vmstan** [comment]
This is using the stock Pi-hole Docker containers?

**Comment by Jarsky** [comment]
I also just noticed that my Pi-Hole database is getting Read-Only now too 
I also use the standard docker container and i have a user "pihole:pihole" (1003:1003)

I updated gravity-sync
`gravity-sync update`

Edited the conf (/etc/gravity-sync/gravity-sync.conf) with these variables

> LOCAL_FILE_OWNER='1003:1003'
> REMOTE_FILE_OWNER='1003:1003'

Changed the ownership on my PiHoles

`sudo chown -R pihole:pihole /opt/pihole`

Restarted both the Pi-Holes

Added a Domain successfully through the UI and ran a  manual sync

> gravity-sync push

```
dns1:~$ gravity-sync push
∞ Initializing Gravity Sync (4.0.5)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PUSH
» Remote target ubuntu@192.168.1.xxx
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
✓ Hashing the remote DNS Records
✓ Comparing to the local DNS Records
✓ Comparing to the local DNS Records
✓ Hashing the remote DNS CNAMEs
✓ Comparing to the local DNS CNAMEs
! Static DHCP Addresses not detected on the local Pi-hole
! Replication of Pi-hole settings is required
✓ Performing backup of remote Gravity Database
✓ Performing backup of local Gravity Database
✓ Checking Gravity Database copy integrity
✓ Pushing the local Gravity Database
✓ Setting file ownership on Gravity Database
✓ Setting file permissions on Gravity Database
✓ Performing backup of remote DNS Records
✓ Performing backup of local DNS Records
✓ Pushing the local DNS Records
✓ Setting file ownership on DNS Records
✓ Setting file permissions on DNS Records
✓ Performing backup of remote DNS CNAMEs
✓ Performing backup of local DNS CNAMEs
✓ Pushing the local DNS CNAMEs
✓ Setting file ownership on DNS CNAMEs
✓ Setting file permissions on DNS CNAMEs
✓ Updating remote FTLDNS configuration
✓ Reloading remote FTLDNS services
› Performing replicator diagnostics
✓ Rehashing the remote Gravity Database
✓ Recomparing to local Gravity Database
✓ Rehashing the remote DNS Records
✓ Recomparing to local DNS Records
✓ Recomparing to local DNS Records
✓ Rehashing the remote DNS CNAMEs
✓ Recomparing to local DNS CNAMEs
! Static DHCP Addresses not detected on the local Pi-hole
✓ Saving updated data hashes
✓ Sending hashes to Gravity Sync peer
✓ Setting permissions on remote hashing files
✓ Logging successful PUSH
∞ Gravity Sync PUSH completed after 137 seconds

```


The ownership on my database files has changed again..but its working now; so not really sure whats going on

> -rw-rw-r-- 1 systemd-coredump ubuntu  96100352 Dec 23 11:50 pihole-FTL.db

**Comment by Jarsky** [comment]
Overnight it went back to Read-Only. A Straight reboot helped, so not sure if this is more of a PiHole Docker issue, more than a gravity-sync one...

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
