### ISSUE TITLE
Multiple Password Requests

### ISSUE THREAD

**Issue by ash34** [vmstan/gravity-sync#418]
Do I really have enter the remote password 5 or 6 times during a compare or push operation?

Or is this a bug?

Using 2 pi’s. Master is a docker container, slave is bare metal.

**Comment by vmstan** [comment]
Do you have a passphrase applied on your SSH key?

**Comment by JYewdall** [comment]
https://linuxize.com/post/how-to-run-sudo-command-without-password/  worked for me

**Comment by ash34** [comment]
Thanks. I solved it by adding the user to sudoers on both machines and reinstalling on both machines.

**Comment by ash34** [comment]
Can close now.
