### ISSUE TITLE
More than two/2 Pihole servers?

### ISSUE THREAD

**Issue by Panja0** [vmstan/gravity-sync#42]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm running four/4 Pihole servers in my network and would like to sync them all instead of 2.

**Describe alternatives you've considered**
There aren't any

**Comment by Panja0** [comment]
Awesome work on the script though!

**Comment by vmstan** [comment]
You just need to install GS on 3/4 of the Piholes, and have them all pull from a primary. Or you could have one pull from the primary, and the rest pull from that one. That's basically how I have my development environment setup, to keep load off of main one.

**Comment by Panja0** [comment]
True... That could be an option.
But for me that doesn't work (fully). I'll explain.

I have 4 Pihole servers running.
DNS-01  (192.168.101)
DNS-02  (192.168.102)
DNS-03  (192.168.103)
DNS-04  (192.168.104)

DNS-01 + DNS-02 are in failover (with keepalived) and share a virtual IP  (192.168.111) besides their own IP.
DNS-03 + DNS-04 are in failover (with keepalived) and share a virtual IP  (192.168.112 )besides their own IP.

So in my example and your usecase I would install GS on DNS-02, 03 and 04 and pull from 01.
But if DNS-01 would go down they can't pull anything.

**Comment by vmstan** [comment]
That's true, however, if you did 01 > 02 and then 02 > 03 & 04, then if 01 goes down, you can keep making changes to 02 which would still propagate out to the rest. Once 01 is back online you could then use the `push` function from 02 to force the changes back to 01.

**Comment by Panja0** [comment]
I get what you mean. Could be a workaround for now yes. Thx

**Comment by vmstan** [comment]
I built this out, and also published some reference architectures relevant to this topic:
https://github.com/vmstan/gravity-sync/blob/master/ADVANCED.md#reference-architectures

**Comment by Panja0** [comment]
Will have a look! Thanks.
To be honest it's working great so far.
Pihole1 = master
Pihole 2. 3 & 4 pull their config from 1 every 15 mins.

I only make changes on Pihole1. 
If Pihole1 is down and keepalived kicked in to change Pihole server I just don't make any changes untill Pihole1 is back up.
