### ISSUE TITLE
Sync problem between Raspberry Pi container and Synology container

### ISSUE THREAD

**Issue by glyntr** [vmstan/gravity-sync#420]
**Issue Description**
gravity-sync push fails as follows:
∞ Initializing Gravity Sync (4.0.5)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✗ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PUSH
» Remote target Glyn@192.168.86.233
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
∞ Hashing the remote Gravity Databasemd5sum: /etc/pihole/gravity.db: No such file or directory
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
! DNS Records not detected on the remote Pi-hole
! DNS CNAMEs not detected on the local Pi-hole
! Static DHCP Addresses not detected on the local Pi-hole
! Replication of Pi-hole settings is required
✓ Performing backup of local Gravity Databasee∞ Performing backup of local Gravity Database
✓ Checking Gravity Database copy integrity
✗ Pushing the local Gravity Database
**Configuration Details**
Have run gravity-sync config on both sides. On Synology have ensured that rsync is enabled etc.
I do note that when I run gravity-sync config on Synology side that it prompts for the Pi password multiple times (5-6x), which makes me think that the passwordless SSH from synology side is not completing correctly. It completes successfully however...and presumably if I am doing gravity-sync push from the Raspberry Pi side, it shouldn't matter (as passwordless ssh to Synology is working). Thoughts?

Config details as follows:
∞ Initializing Gravity Sync (4.0.5)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✗ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: INFO
Local Software Versions
Pi-hole
  Pi-hole version is v5.17.2 (Latest: v5.17.2)
  web version is v5.20.2 (Latest: v5.21)
  FTL version is v5.23 (Latest: v5.23)
Ubuntu 23.10
Linux 6.5.0-1008-raspi aarch64
bash 5.2.15(1)-release
OpenSSH_9.3p1 Ubuntu-1ubuntu3.1, OpenSSL 3.0.10 1 Aug 2023
rsync  version 3.2.7  protocol version 31
Sudo version 1.9.14p2
git version 2.40.1
Docker version 24.0.7, build afdd53b

Global Instance Settings
SSH Port: 22 (default)
SSH Key: /etc/gravity-sync/gravity-sync.rsa
Automated Replication: Disabled

Local Instance Settings
Local Hostname: piserver
Local Pi-hole Type: docker
Local Pi-hole Config Directory: /home/pi/dockercompose/etc-pihole
Local DNSMASQ Config Directory: /home/pi/dockercompose/etc-dnsmasq.d
Local Gravity Sync Binary: /usr/local/bin/gravity-sync
Local Gravity Sync Config Directory: /etc/gravity-sync
Local Pi-hole Container Name: pihole
Local Docker Binary Directory: /usr/bin/docker
Local File Owner Settings: 999:999

Remote Instance Settings
Remote Hostname/IP: 192.168.86.233
Remote Username: Glyn
Remote Pi-hole Type: none
Remote Pi-hole Config Directory: /etc/pihole
Remote DNSMASQ Config Directory: /etc/dnsmasq.d
Remote File Owner Settings: pihole:pihole
ubuntu-logo Gravity Sync INFO exited after 1 seconds

**Comment by glyntr** [comment]
I also note the following error on the Synology:
/usr/local/bin/gravity-sync: line 1353: ssh-copy-id: command not found
I copied my ssh-copy-id script from Ubuntu - didn't seem to be a great idea, but it solved this error message...but still not working
Getting multiple errors on Synology side of the following:
- sudo: /usr/bin/docker: command not found

**Comment by glyntr** [comment]
Which I tried fixing with a symlink
ln -s /usr/local/bin/docker ./docker

Reducing number of error messages, but still failing. Error as follows:
∞ Hashing the remote Gravity Databasemd5sum: /etc/pihole/gravity.db: No such file or directory

Maybe my Synology image is non-standard? it is /etc-pihole/gravity.db

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
