### ISSUE TITLE
Initial sync fails on a fresh install of Ubuntu 22.04.x + pi-hole + gravity-sync

### ISSUE THREAD

**Issue by gcs8** [vmstan/gravity-sync#421]
**Issue Description**
Initial sync fails on a fresh install of Ubuntu 22.04.x + pi-hole + gravity-sync

Ubuntu version(s): 22.04.3 LTS
Pi-Hole Version(s): v5.17.2
Gravity-Sync Version(s): 4.0.5

`gcs8@pi-hole-primary:~$ gravity-sync compare
∞ Initializing Gravity Sync (4.0.5)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: COMPARE
» Remote target gcs8@10.13.37.42
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
∞ Hashing the remote DNS RecordsConnection reset by 10.13.37.42 port 22
✗ Hashing the remote DNS Records`

**Configuration Details**
pi-hole-primary: 192.168.127.151
IP-Sec tunnel
pi-hole-replica: 10.13.37.42
Full Ubuntu 22.04 LTS VMs on ESXi

10 packets transmitted, 10 received, 0% packet loss, time 9013ms
rtt min/avg/max/mdev = 21.356/23.599/27.454/1.972 ms

traceroute to 192.168.127.151 (192.168.127.151), 64 hops max
  1   10.13.37.1  0.114ms  0.072ms  0.085ms
  2   192.168.1.1  21.544ms  21.680ms  20.965ms
  3   192.168.127.151  20.718ms  23.726ms  20.955ms

Connection to 192.168.127.151 22 port [tcp/ssh] succeeded!

pi-hole-primary (192.168.127.151) -> 10.13.37.42 (10.13.37.42)                                                                                                                                     2023-12-30T00:30:17+0000
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                                                                                                                                                   Packets               Pings
 Host                                                                                                                                                                            Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 192.168.127.1                                                                                                                                                                 0.0%   201    0.2   0.2   0.2   0.4   0.0
 2. (waiting for reply)
 3. 10.13.37.42                                                                                                                                                                   0.0%   201   22.4  23.2  20.2  32.9   2.6

`gcs8@pi-hole-primary:~$ curl -sSL https://raw.githubusercontent.com/vmstan/gs-install/main/gs-install.sh | bash
∞ Gravity Sync Installation Script
» Validating User Permissions
✓ Sudo utility detected
[sudo] password for gcs8:
✓ gcs8 has sudo powers
» Validating Install of Required Components
✓ SSH has been detected
✓ GIT has been detected
✓ RSYNC has been detected
✓ Systemctl has been detected
» Performing Warp Core Diagnostics
✓ Local installation of Pi-hole has been detected
» Executing Gravity Sync Deployment
∞ Creating sudoers.d permissions file
∞ Cleaning up bash.bashrc
  You may need to exit your terminal or reboot before running 'gravity-sync' commands
∞ Creating Gravity Sync Directories
Cloning into '/etc/gravity-sync/.gs'...
remote: Enumerating objects: 2791, done.
remote: Counting objects: 100% (231/231), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 2791 (delta 170), reused 101 (delta 87), pack-reused 2560
Receiving objects: 100% (2791/2791), 613.69 KiB | 5.25 MiB/s, done.
Resolving deltas: 100% (1779/1779), done.
∞ Starting Gravity Sync Configuration
∞ Initializing Gravity Sync (4.0.5)
✓ Evaluating arguments: CONFIGURE
✓ Creating new gravity-sync.conf

  Welcome to the Gravity Sync Configuration Wizard
  Please read through https://github.com/vmstan/gravity-sync/wiki before you continue
  Make sure that Pi-hole is running on this system before your configure Gravity Sync

» Gravity Sync Remote Host Settings
› Remote Pi-hole host address
? IP: 10.13.37.42
✓ Saving 10.13.37.42 host to gravity-sync.conf
› Remote Pi-hole host username
? User: gcs8
✓ Saving gcs8@10.13.37.42 to gravity-sync.conf
» Gravity Sync SSH Key Settings
✓ Generating new SSH key
✓ Moving private key to /etc/gravity-sync/gravity-sync.rsa
✓ Moving public key to /etc/gravity-sync/gravity-sync.rsa.pub
✓ Loading gravity-sync.conf
› Registering SSH key to 10.13.37.42
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/etc/gravity-sync/gravity-sync.rsa.pub"
gcs8@10.13.37.42's password:

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh -p '22' 'gcs8@10.13.37.42'"
and check to make sure that only the key(s) you wanted were added.

✓ SSH key registered to 10.13.37.42
» Pi-hole Installation Settings
✓ Detecting local Pi-hole installation
✓ Default install of Pi-hole detected
✓ Detecting remote Pi-hole installation
✓ Remote install of Pi-hole detected

  Configuration has been completed successfully, once Gravity Sync has been installed your other
  node, your next step is to push all of the of data from the currently authoritative
  Pi-hole instance to the other.
  ex: gravity-sync push

  If that completes successfully you can automate future sync jobs to run at a regular interval on
  both of your Gravity Sync peers.
  ex: gravity-sync auto

∞ Gravity Sync CONFIGURE completed after 42 seconds`

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
