### ISSUE TITLE
gravity-sync auto requires systemd -- pihole docker container uses s6

### ISSUE THREAD

**Issue by letizido** [vmstan/gravity-sync#422]
I have installed gravity-sync v4 on my pihole container and on my pihole on Raspberry Pi. Install is working. manual sync is working flawlessly. gravity-sync auto works fine when I run it on the Pi, but errors out when I run it on the pihole container. Here are the errors:

root@pihole-nas:~# gravity-sync auto
∞ Initializing Gravity Sync (4.0.5)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: AUTOMATE
✓ Customizing service file username
✓ Customizing service file executable path
✓ Randomizing service timers
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
✓ Moving systemd timer into place
✓ Moving systemd service into place
∞ Reloading systemd daemonSystem has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
✗ Reloading systemd daemon

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
