### ISSUE TITLE
Detecting remote Pi-hole installationLoad key - Permission denied

### ISSUE THREAD

**Issue by newbieraf** [vmstan/gravity-sync#425]
Hi there

Linux Newbie here - please bare with me

- I have a pihole running on my proxmox as a docker container (10.1.1.3)
- I have a second pihole running on a RPi also as a docker container (10.1.1.4)
- I want to use Gravity Sync to sync from 10.1.1.3 to 10.1.1.4

Things I've done:

- Created a dedicated Gravity Sync with sudoless permissions on each of the piholes
- I ran the Gravity sync install script on each pihole initially with a different sudo account (don't ask why)
- doing a pull from 10.1.1.4 to 10.1.1.3 works
- doing a push from 10.1.1.3 to 10.1.1.4 always gives me "Detecting remote Pi-hole installationLoad key "/etc/gravity-sync/gravity-sync.rsa": Permission denied"
- It also asks me for a remote password which I have tripled checked I have entered correctly however it doesn't recognise it and keeps prompting for a password
- To verify the password I have logged in with the dedicated gravity account successfully plus I made the it has sudo without having to enter the password

I must be doing something wrong but I don't know what it is.  Can you please help?

Thanks

**Comment by traxeon** [comment]
Run the command recommended on the install page.   Also make sure you clear out any configurations you performed (e.g. remove /etc/gravity-sync and /usr/local/bin/gravity-sync before running the install script.  I ran into this when I originally ran the install under root, it failed, then decided to run it under my non-root account.  The files remaining did not have permissions to be written/overwritten since they were originally run as root.

**Comment by newbieraf** [comment]
Thanks so much @traxeon and sorry about the late reply.  I removed Gravity Sync completely and used the standard script on the site to reinstall.  When I now do a compare from 10.1.1.3 (primary) it works, however when I do the same from 10.1.1.4 (secondary) I get “ unable to validate configuration folder for Pi-hole” on the primary.  Im doing both compares as the non-root account.  What am I missing?

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
