### ISSUE TITLE
Raspberry Pi access timed out after upgrading to 4.0.6

### ISSUE THREAD

**Issue by markladage** [vmstan/gravity-sync#426]
Hi, after updating to version 4.0.6 both my Raspberry Pi's are no longer accessible but I can ping them. Recently I changed my network addressing from 192.168._0_.# to 192.168._1_.#, could this have something to do with it. Thank you in advance for your response.

Grtz. Mark

**Comment by vmstan** [comment]
Nothing in 4.0.6 should have changed your ability to access the Pi's themselves.

**Comment by markladage** [comment]
Ok thanks, will reboot the system later and will see if that helps. I'll let you know.

**Comment by markladage** [comment]
Somehow I was able to reach the Pi's again later, but they gave the message as if they were being contacted for the 1st time. So something definitely has happened, but I can't figure out what, but at least everything is working again. Thanks for the response.
