### ISSUE TITLE
Sync after change

### ISSUE THREAD

**Issue by Panja0** [vmstan/gravity-sync#43]
**Describe the solution you'd like**
At the moment we use Cron to do a regular sync between the Pihole servers.
It would be great to have an auto sync after something (local DNS record, whitelist, blacklist, or anything gravity.db related) has been changed on the primary Pihole.

**Comment by vmstan** [comment]
It would be great, but I think that I'll leave that up to the Pi-hole development team. 😄

**Comment by Panja0** [comment]
Hahaha I can imagine. To be honest your script (or scripts) is **AWESOME** as is.
Would be great if stuff would kick in after changes but working with Cron is ok.
What Cron interval are you using personally?

**Comment by vmstan** [comment]
15 minutes.

**Comment by Panja0** [comment]
Ok, thanks. Sounds like a reasonable timeframe. I noticed the script is very fast.
On my 2 Debian VM's (1vCPU and 1GB ram) the scripts is done in 4 seconds. So I think the load on the servers is pretty easy going.
