### ISSUE TITLE
Use my own ssh keys

### ISSUE THREAD

**Issue by Kornelius777** [vmstan/gravity-sync#432]
Dear Michael,

my piholes already "know and trust" each other's ssh keys (ED25519).
I would rather use my own keys instead of those ecdsa-sha2-nistp256 keys created by gravity-sync.
Please add an option to select an alternative ssh key than the one produced by gravity-sync.
Thank you!
Regards!

**Comment by vmstan** [comment]
I think you could probably just create symlinks from the current key locations to the ones that you want to use.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
