### ISSUE TITLE
Running gravity-sync in a container on its own?

### ISSUE THREAD

**Issue by benze** [vmstan/gravity-sync#434]
I recently ran across gravity-sync and really like the premise.  I run my piholes in containers on 2 different docker engine hosts. 
 However, I am not fond of the idea of installing any applications on the host other than the base system binaries required to run my containers.

I looked at different options and building containers to isolate gravity-sync in its own docker container (along with requisite sshd) in order to limit ssh exposure between processes.  However, looking through the gravity-sync script I am noticing that GS needs to access the individual pihole processes to trigger refreshes/reloads/etc.

Is there any way that I can run GS in an isolated container, or is that something that is completely out-of-scope and too difficult to manage?

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
