### ISSUE TITLE
Config Stuck on Registering SSH

### ISSUE THREAD

**Issue by kewtz** [vmstan/gravity-sync#436]
Have 2 fresh pi-hole installs via Proxmox containers, service is running on both, gravity-sync installed on both. 

```
» Gravity Sync Remote Host Settings

› Remote Pi-hole host address

? IP: 192.168.0.211

✓ Saving 192.168.0.211 host to gravity-sync.conf

› Remote Pi-hole host username

? User: root

✓ Saving root@192.168.0.211 to gravity-sync.conf

» Gravity Sync SSH Key Settings

✓ Generating new SSH key

✓ Moving private key to /etc/gravity-sync/gravity-sync.rsa

✓ Moving public key to /etc/gravity-sync/gravity-sync.rsa.pub

✓ Loading gravity-sync.conf

› Registering SSH key to 192.168.0.211

/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/etc/gravity-sync/gravity-sync.rsa.pub"

root@192.168.0.211's password: 

Permission denied, please try again.
```

I'm stuck here, I know the root password...but the config seems to be expecting something else? Is it looking for the public key of the other machine?

**Comment by kevinreck** [comment]
Kewtz - Did you check that your second node's (192.168.0.211) /etc/ssh/sshd_config has both of these settings to allow the root user to log in?

PasswordAuthentication yes
PermitRootLogin yes

Reminder to restart the ssh daemon.  You can remove the PasswordAuthentication afterwards

**Comment by kewtz** [comment]
I did verify this on the .211 node. 
I also reset the root password on both to ensure that wasn't the problem, I continue to get permission denied.

**Comment by dualm66** [comment]
Maybe related? When I did a fresh install I got the output below. This was resolved by using ssh one on the remote machine (ie this creates the default .ssh folder in the users home folder)

✓ Loading gravity-sync.conf
› Registering SSH key to 192.168.1.7
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/etc/gravity-sync/gravity-sync.rsa.pub"
mktemp: failed to create directory via template ‘/home/gravsync/.ssh/ssh-copy-id.XXXXXXXXXX’: No such file or directory
/usr/bin/ssh-copy-id: ERROR: failed to create required temporary directory under ~/.ssh

**Comment by janaxhell** [comment]
Has this been addressed? I've just spin a new install of Pihole on an Orange Pi Zero 2 with Armbian_24.5.3_Orangepizero2_bookworm_current_6.6.31_minimal
and gravity-sync on the other Pihole keeps asking me the user password when I try gravyty-sync push

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
