### ISSUE TITLE
https://vmstan.com/gravity-sync/ is a 404

### ISSUE THREAD

**Issue by sergeifilippov** [vmstan/gravity-sync#437]
Project description has a 404 for the link https://vmstan.com/gravity-sync/

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
