### ISSUE TITLE
Unable to complete garvity-sync config between pi-hole containers on Synology NAS and Raspberry PI 3B+

### ISSUE THREAD

**Issue by hamah99** [vmstan/gravity-sync#439]
Running pi-hole in a container on a Syno NAS running DSM 7.2 and in a container on my rpi 3B+. pi-hole is up and running in both containers and I believe the installation of gravity-sync went well on both as well but I can't successfully run gravity-sync config on either end.

DSM 7.2:

∞ Starting Gravity Sync Configuration

bash: line 278: /usr/local/bin/gravity-sync: Permission denied

rpi 3B+

∞ Detecting remote Pi-hole installationssh: connect to host [192.168.0.200](https://192.168.0.200/) port 22: Connection refused

✗ Detecting remote Pi-hole installation

! No remote Pi-hole installed detected

Configuration could not be completed successfully, as no instances of Pi-hole could be detected

on one or more of your systems. Please make sure they are running on both peers and try again.

I'm pretty green at this so any assistance would be appreciated.

**Comment by Leethal1977** [comment]
Having the same issue. Managed to get it down to ssh service not running in the pihole container on my NAS. After lots of mucking about, managed to manually install and run ssh, but it obviously needs re doing whenever the container is restarted. Need to explore how to add that to the container start up and I'm pretty green too so any help welcome 😀

**Comment by hamah99** [comment]
I ended up switching to [pihole-cloudsync](https://github.com/stevejenkins/pihole-cloudsync). Encountered problems with my gravity db getting corrupted and then saw [this closed issue](https://github.com/stevejenkins/pihole-cloudsync/issues/47). That mentioned a fork found [here](https://github.com/theobjectivedad/pihole-cloudsync). I'm now trying to manually merge the 2 scripts. Pihole-cloudsync works well otherwise but if I can't fix I'll just rip up any plans to automagically sync 2 pihole instances.

**Comment by vmstan** [comment]
> I ended up switching to [pihole-cloudsync](https://github.com/stevejenkins/pihole-cloudsync). I encountered problems with my gravity db getting corrupted and then saw [this closed issue](https://github.com/stevejenkins/pihole-cloudsync/issues/47) that mentioned a fork found [here](https://github.com/theobjectivedad/pihole-cloudsync). I'm now trying to manually merge the 2 scripts. Pihole-cloudsync works well otherwise but if I can't fix I'll just rip up any plans to automagically sync 2 pihole instances.

That issue is one reason why I've resisted ever modifying the SQLite database itself.

**Comment by hamah99** [comment]
I ended up finding that the [pihole-cloudsync](https://github.com/stevejenkins/pihole-cloudsync) script was possibly (probably?) corrupting the Gravity db as mentioned in this [thread](https://github.com/stevejenkins/pihole-cloudsync/issues/47). I swapped the script for [this fork](https://github.com/theobjectivedad/pihole-cloudsync) that resolved the corruption issue. I then simply performed a Update Gravity from the tools in pihole. All seems good now.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
