### ISSUE TITLE
Pi-Hole v6 Compatibility

### ISSUE THREAD

**Issue by Jarsky** [vmstan/gravity-sync#443]
The latest version of Pi-Hole has been in development for a while. The branch can be found here:
https://github.com/pi-hole/pi-hole/tree/development-v6

Theres some notable changes which are mainly:
Configuration is now handled in a pihole.toml file
Conditional Forwarding etc..are now added to dnsmasq.conf in the main directory (no longer dnsmasq.d dir)
pihole-FTL.db now has pihole-FTL.db-shm & pihole-FTL.db-wal files

There are probably some other sync changes too. 
I did attempt to run a sync with v4.0.7, it cant find dnsmasq.d but when I added it and ran a gravity-sync pull on the new v6 server, practically everything broke. 

I ended up using Teleporter from my Primary to my Secondary; but would love to get gravity-sync working again.

**Comment by FurkanVG** [comment]
Is this project dead?

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
