### ISSUE TITLE
Failed logins on partner pihole server

### ISSUE THREAD

**Issue by tamorgen** [vmstan/gravity-sync#446]
I had to rebuild my rpi4 due to a failed SD card, so I had to reinstall pihole and gravity-sync.  I started seeing a bunch of failed logins when I was logging into my primary server, and I traced it back to the rpi4.  This has to be the gravity-sync trying to login.  How do I reset the password, so it's using the correct credentials on gravity-sync?

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
