### ISSUE TITLE
Gravity-Sync Hang at "Performing backup of remote Gravity Database" 

### ISSUE THREAD

**Issue by ECLAYA4188** [vmstan/gravity-sync#448]
My issue is first the 'gravity-sync pull' and 'gravity-sync push' command require a password at every step soulution #442 did not work.  I have checked the /etc/sudoers.d/gs-nopasswd file and it is correctly configured.  My second issue is it hangs at "✗ Performing backup of remote Gravity Database" and eventually exits.  I have looked at every issue posted but no solution seems to help with problem.

I am running this on 2 raspberry pi4's.  I am not running it using docker. I had the older version setup and running smoothly but this new version 4.0.7 seems to be having permission/credential issues. 

user@pi:~ $ sudo gravity-sync pull
∞ Initializing Gravity Sync (4.0.7)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
user1@xxx.xxx.xxx.xxx's password:
✓ Detecting remote Pi-hole installation
user1@xxx.xxx.xxx.xxx's password:
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PULL
» Remote target user1@xxx.xxx.xxx.xxx
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
user1@xxx.xxx.xxx.xxx's password: 
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
user1@xxx.xxx.xxx.xxx's password:
user1@xxx.xxx.xxx.xxx's password:
✓ Hashing the remote DNS Records
✓ Comparing to the local DNS Records
! Differences detected in the DNS Records
user1@xxx.xxx.xxx.xxx's password:
! DNS CNAMEs not detected on the local Pi-hole
user1@xxx.xxx.xxx.xxx's password:
! Static DHCP Addresses not detected on the local Pi-hole
! Replication of Pi-hole settings is required
✓ Performing backup of local Gravity Database
✗ Performing backup of remote Gravity Database
user1@pi4-3:~ $

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
