### ISSUE TITLE
No DHCP Sync

### ISSUE THREAD

**Issue by projektug24** [vmstan/gravity-sync#449]
Hi,

I have a VPN between two locations.
IP range of location A (Pi.Hole Master): 10.10.10.0/24
IP range of location B (Pi.Hole Slave): 10.10.30.0/24

I am currently synchronizing all settings via Gravity Sync, but I would like to leave the "DHCP" tab unsynchronized. 
If a device is logged in today from location A and tomorrow at location B, there are problems with the IP address reservations.

Is there a solution for this?

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
