### ISSUE TITLE
/etc/hosts

### ISSUE THREAD

**Issue by jmarkel176** [vmstan/gravity-sync#45]
Sync /etc/hosts file from primary to secondary? Know I could do this via bash and cron, but be nice to have in one place. Great job on this!

**Comment by vmstan** [comment]
What would you put in /etc/hosts that isn't covered by the Custom Local DNS option in Pi-hole 5?

**Comment by jmarkel176** [comment]
Wow, didn't even see that was an option in version 5, that's great, sorry about that

**Comment by vmstan** [comment]
Yeah no worries, honest question to make sure I wasn't missing something, but I think they duplicated the functionality there and made it a lot easier to manage. It's what comes along in `custom.list` during Gravity Sync replication.

**Comment by jmarkel176** [comment]
Thanks again!
