### ISSUE TITLE
Where is the systemd config file located?

### ISSUE THREAD

**Issue by kosymodo** [vmstan/gravity-sync#450]
I've today installed and configured gravity-sync.  All working well so far.  However, I now wish to set up automation.  I can't work out where I should be looking for the systemd config file.

I'm running 2 Pis, both running latest Debian Bookworm.

Thanks in advance for any assistance!

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
