### ISSUE TITLE
Sync Between Primary and Secondary Not Happening

### ISSUE THREAD

**Issue by FastWReX** [vmstan/gravity-sync#453]
Installed on both Primary and Secondary Raspberry Pi Zero 2 W's. Ran the exact same commands, setup the same, etc. 

Using "gravity-sync push" from Primary, it says nothing to change. Using "gravity-sync pull" from Secondary says there are no updated to make. How do I get these two to talk to one another?

**Configuration Details**

**Primary - 192.168.0.113 (25 Ad Lists)**

gravity-sync push
∞ Initializing Gravity Sync (4.0.7)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PUSH
» Remote target pi@192.168.0.113
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
✓ Hashing the remote DNS Records
✓ Comparing to the local DNS Records
! DNS CNAMEs not detected on the local Pi-hole
! Static DHCP Addresses not detected on the local Pi-hole
! No replication is required at this time
∞ Gravity Sync PUSH exited after 11 seconds

**Secondary - 192.168.0.114 (22 Ad Lists)**

gravity-sync compare
∞ Initializing Gravity Sync (4.0.7)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: COMPARE
» Remote target pi@192.168.0.114
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
✓ Hashing the remote DNS Records
✓ Comparing to the local DNS Records
! DNS CNAMEs not detected on the local Pi-hole
! Static DHCP Addresses not detected on the local Pi-hole
! No replication is required at this time
∞ Gravity Sync COMPARE exited after 12 seconds

**Comment by FastWReX** [comment]
Primary
![Uploading Screenshot 2024-07-22 at 5.06.59 PM.png…]()


Secondary
![Uploading Screenshot 2024-07-22 at 5.07.12 PM.png…]()

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
