### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by HarvsG** [vmstan/gravity-sync#46]
**Is your feature request related to a problem? Please describe.**
I would like to have a reddundant PiHole, but I dont want to dedicate a second device to it, particularly when it should only be used some of the time. Running the 'spare' in a docker container would be great.

But gravity sync doesn't support this

**Describe the solution you'd like**
Gravity Sync to support Docker as the primary or secondary or both

**Describe alternatives you've considered**
PiHole can run with it's userspace volume bound to an actual directory on the host machine. If the script knows the location of that directory (and has the necessary permissions) it has access to all the information it needs.

```bash
pi@raspberrypi:~/docker-files/pihole $ tree
.
├── dnsmasq.d
│   └── 01-pihole.conf
└── pihole
    ├── adlists.list
    ├── auditlog.list
    ├── black.list
    ├── custom.list
    ├── dns-servers.conf
    ├── GitHubVersions
    ├── gravity.db
    ├── gravity.list
    ├── list.0.raw.githubusercontent.com.domains
    ├── list.1.mirror1.malwaredomains.com.domains
    ├── list.2.sysctl.org.domains
    ├── list.3.s3.amazonaws.com.domains
    ├── list.4.s3.amazonaws.com.domains
    ├── list.preEventHorizon
    ├── localbranches
    ├── local.list
    ├── localversions
    ├── migration_backup
    │   ├── adlists.list
    │   ├── blacklist.txt
    │   ├── regex.list
    │   └── whitelist.txt
    ├── pihole-FTL.conf
    ├── pihole-FTL.db
    ├── setupVars.conf
    └── setupVars.conf.update.bak

```
The bindings look like:

| Hos                                | Path in container |
|----------------------------------------|-------------------|
| /home/pi/docker-files/pihole/pihole    | /etc/pihole       |
| /home/pi/docker-files/pihole/dnsmasq.d | /etc/dnsmasq.d    |

So if the script knows the host bindings then it knows where to look.

**Comment by vmstan** [comment]
So finding the files is part of the problem, the other is executing all the necessary commands inside of both containers to do things like restarting services.

**Comment by HarvsG** [comment]
I see, is there any command that prepending `docker exec [container name]` would work for?

**Comment by vmstan** [comment]
@fbourqui just committed some changes to help facilitate container support, and says he has it running through an automation pipeline. Perhaps he'd have some insights.

**Comment by fbourqui** [comment]
Hello,

in case of your docker deployment of the second pihole, with your statement:
PiHole can run with it's userspace volume bound to an actual directory on the host machine. If the script knows the location of that directory (and has the necessary permissions) it has access to all the information it needs.

Assuming your second pihole is in docker, you would need to run gravity-sync on the docker host, not the pi-hole docker.

gravity-sync is expecting the files to be compared, sync in :
PIHOLE_DIR='/etc/pihole' 			# default Pi-hole data directory

so you would have to adapt that path to the mapping you do on your docker host.

By the way I did my deployment using lxd on ubuntu (20.04), both master and backup.
lxd1 host is on a vmware esxi vm backed by ssd, lxd2 is an old pysical atom machine backed by regular hdd.

**Comment by scyto** [comment]
Rather than running gravity sync on the docker hosts, why not a modified container where it is running inside the say the primary pihole container? 

It doesn't look like gravity sync is HA - aka there is only one instance of gravity sync right?

**Comment by dpraul** [comment]
I got this working with some small tweaks in #94, although I imagine for proper "Docker support" the `PIHOLE_DIR` setting should be broken out to support different directories on the local and remote side.

**Comment by Cartache** [comment]
Hi, I also managed to make it run based on comment from @dpraul. Thanks for that. Though I thought the new version would implement the FILE_OWNER='999:999' and REMOTE_FILE_OWNER='999:999' variable which apparently is not the case.
I also had to install sqlite which is not mentioned as a requirement. Finally, it is a pity I had to move the docker mount to the same location on both instance.

**Comment by vmstan** [comment]
As of 2.2.3 which will publish shortly, I call out SQLite as a requirement. I thought it was part of the Pihole install, but container deployments probably don't have that.

The FILE_OWNER should be the name:group of the users. Is 999 a container generated user?

**Comment by dpraul** [comment]
`999` is the ID that corresponds to the `pihole` user ID (and also the `pihole` group ID) on the Docker image. `chown`, and subsequently `FILE_OWNER` work with either the user/group names or the user/group IDs

**Comment by vmstan** [comment]
Yeah, gotcha. I need to get a proper Docker install of Pi-hole going and test this myself. I know the demand is there but I've yet to engage.

**Comment by Cartache** [comment]
Hi @vmstan, I installed the latest version but now get a prompt for password for my user. This was not the case before. Any reason/change that could cause this new behaviour?

**Comment by vmstan** [comment]
Just released version 3.0, Docker users please test 🙏

**Comment by vmstan** [comment]
I've been playing with the official Pi-hole docker image for the last few days, and I'm now fleshing out initial support for Docker in Gravity Sync. If you want to track progress I would suggest just refreshing the dev copy of the [3.1-dev changelog](https://github.com/vmstan/gravity-sync/blob/3.1.0/docs/CHANGELOG.md).

Inital thoughts:
- Need more flexibility to differentiate between configuration differences in primary and secondary instances:
> - `REMOTE_FILE_OWNER` variable renamed `RILE_OWNER` for consistency.
> - `RIHOLE_DIR` variable added to set different Pi-hole directory for remote host than local.
> - `DOCKER_CON` and `ROCKER_CON` variables added to specify different names for local and remote Pi-hole Docker containers.
- Need more flexibility to allow Gravity Sync to be run from any directory, and not just in a user's home folder.
- Need more flexibility around sudo/root requirements. (Should probably just detect if it's a user with sudo ability, vs running as the root user.)
- Need to make sure any detection of the Pi-hole instance accommodates for either "regular" install or detecting the Docker container, with flexibility to have differences at each site.

I'm open to additional thoughts and feedback.

**Comment by Extarys** [comment]
@vmstan Primary installed normally, secondary in docker. Your script work flawlessly from what I can tell. (Had some headache with the SSH key but I manage)

Thank you very much for this :heart:
