### ISSUE TITLE
DietPi Incompatability

### ISSUE THREAD

**Issue by ALittleOfEverything88** [vmstan/gravity-sync#54]
Downloaded the script on DietPi running the latest version. Had to switch user to DietPi as the root logon runs everything as root. Had to then manually download/install SSH client.

Configuration is now failing at `[ EXEC ] Validating Connection to PiHolePRLoad key "/home/dietpi/.ssh/id_rsa": invalid format
`. I have no idea what this means or how to fix it.

Let me know if I can be of any help.

**Comment by vmstan** [comment]
Are you using Dropbear or OpenSSH as the key provider?

**Comment by ALittleOfEverything88** [comment]
Dropbear; I'm guessing I need to switch to OpenSSH?

**Comment by vmstan** [comment]
Yeah, honestly I did so much work to get Dropbear functional but it's just such a pain, I may remove support for it. I would switch to OpenSSH and then delete the id_rsa and id_rsa.pub files under ~/.ssh and restart the configuration.

**Comment by ALittleOfEverything88** [comment]
Switching to OpenSSH worked. Was a bit of a process to remove dropbear from a headless system but it worked. 

It would be helpful (if possible) if the installer checked for these things first (not running as a root user / correct SSH installed / etc) and yelled at me first. I suspect that I won't be the only one trying to install/run/use this script on a Pi running DietPi.

Thanks for the assistance!
