### ISSUE TITLE
Request SSH port when using /gravity-sync.sh config

### ISSUE THREAD

**Issue by phzang** [vmstan/gravity-sync#61]
**Is your feature request related to a problem? Please describe.**
My PI-Holes have non standard SSH ports (not 22).  Have to manually edit gravity-sync.sh after realizing it defaults to 22.  FIRE THE TORPEDOS gets old after going through the config a few times to not see an option to change ports.

**Describe the solution you'd like**
Between "IP or DNS of Primary Pi-hole" and "SSH User with SUDO rights", insert "SSH Port of Primary Pi-hole (Default is 22)".

**Describe alternatives you've considered**
Just leaving as is?

**Additional context**
Pretty much it.  Based on no information at all I'd think I'm not the only one with weird SSH ports.

**Comment by vmstan** [comment]
I totally see that it’s a chicken and egg type thing. My original thinking was anyone needing that wouldn’t use the automatic configuration tool, because at first it was very limited. I’ve added it to the todo list to expand more of the options into setup.

**Comment by vmstan** [comment]
@phzang I have added a step to the `config` function in the 2.1.6 beta that allows you to set a custom port as well as disable the ping check during setup. Would you be willing to test this in your environment by using the beta branch? (Instructions to do so at https://github.com/vmstan/gravity-sync/issues/63)

**Comment by phzang** [comment]
@vmstan I changed to the beta branch as instructed "Running Version: 2.1.6 beta".  Primary and Secondary are on v5.1.1, Primary on Raspbian Buster (PI Zero W), Secondary on Raspian Buster (Pi 4 B 4Gb).  The first time I ran ./gravity-sync.sh after going to the beta branch it seemingly worked fine (10.0.0.109 is primary, raspberrypi4 is secondary:

`./gravity-sync.sh
[ INFO ] Gravity Sync 2.1.6 Executing

[  OK  ] Evaluating Arguments: SMART Requested
[  OK  ] Importing gravity-sync.conf Settings
[ INFO ] Targeting joe@10.0.0.109
[  OK  ] Validating SSH Client on raspberrypi4 (OpenSSH)
[  OK  ] Validating RSYNC Installed on raspberrypi4
[  OK  ] Validating Gravity Sync Folders on raspberrypi4
[  OK  ] Validating Pi-hole Configuration on raspberrypi4
[ INFO ] Using SSH Key-Pair Authentication
[  OK  ] Validating Connection to 10.0.0.109
[  OK  ] Analyzing gravity.db on 10.0.0.109
[  OK  ] Analyzing gravity.db on raspberrypi4
[ WARN ] Differenced gravity.db Detected
[  OK  ] Analyzing custom.list on 10.0.0.109
[  OK  ] Analyzing custom.list on raspberrypi4
[ WARN ] Differenced custom.list Detected
[ WARN ] Replication Required
[ WARN ] Both gravity.db Changed
[ INFO ] Primary gravity.db Last Changed
[  OK  ] Performing Backup of Local gravity.db
[  OK  ] Performing Backup of Remote gravity.db
[  OK  ] Pulling gravity.db from 10.0.0.109
[  OK  ] Replacing gravity.db on raspberrypi4
[  OK  ] Validating Settings of gravity.db
[ WARN ] Both custom.list Changed
[ INFO ] Secondary custom.list Last Changed
[  OK  ] Performing Backup of Remote custom.list
[  OK  ] Performing Backup Up Local custom.list
[  OK  ] Copying custom.list from 10.0.0.109
[  OK  ] Pushing custom.list to 10.0.0.109
[  OK  ] Setting Permissions on custom.list
[  OK  ] Setting Ownership on custom.list
[ INFO ] Isolating Regeneration Pathways
[  OK  ] Updating FTLDNS Configuration
[  OK  ] Reloading FTLDNS Services
[ INFO ] Inverting Tachyon Pulses
[  OK  ] Updating Remote FTLDNS Configuration
[  OK  ] Reloading Remote FTLDNS Services
[ INFO ] Performing Replicator Diagnostics
[  OK  ] Reanalyzing gravity.db on 10.0.0.109
[  OK  ] Reanalyzing gravity.db on raspberrypi4
[  OK  ] Reanalyzing custom.list on 10.0.0.109
[  OK  ] Reanalyzing custom.list on raspberrypi4
[  OK  ] Saving File Hashes
[  OK  ] Logging Successful SMART
[ INFO ] Gravity Sync SMART Completed (166 seconds)
`
For some reason the secondary didn't have any block lists. Domains on Blocklists on admin page showed -2 (maybe -1).  Tried clearing cache, refreshing browser, etc.  Did "ls -al" on pihole folder and gravity.db were different sizes.  Odd.  I found the "gravity-sync.sh restore" option.  It restored the gravity.db perfectly.  Ran gravity-sync.sh again to test if it broke again.  It worked fine.  Maybe I did something out of order?  I'm going to remove gravity-sync folder and redownload to try again.  Wanted to write this down first.

**Comment by vmstan** [comment]
Whoa, yeah I've not seen that before, let me know. The way backups are handled is totally new in this 2.1.x train. Might have been something gone wild with the sqlite3 command, but I'd want to track it down.

Glad to know the new restore feature worked for you 👍

**Comment by vmstan** [comment]
Also, is 166 seconds normal execution time for a sync for you? How big is your database?

**Comment by phzang** [comment]
I re-downloaded gravity-sync, updated, went to beta branch, updated.  The script worked great this time.  Not sure what happened before.  Yes, 166s is normal.  It's at 3.1M domains.  I put a ...really... bit blocklist in there.  Going to trim it down SoonTM.  Thanks for your work!
