### ISSUE TITLE
Error when performing backup

### ISSUE THREAD

**Issue by nnleaf** [vmstan/gravity-sync#66]
**Describe the Issue**

Hi, when performing ./gravity-sync.sh smart I get this error 

`[ WARN ] Replication Required
[  OK  ] Performing Backup of Local gravity.db`
`[ EXEC ] Performing Backup of Remote gravity.dbsudo: no tty present and no askpass program specified`
`[ FAIL ] Performing Backup of Remote gravity.db`

**Configuration:**
 - OS for Primary/Secondary: Debian
 - Platform for Primary/Secondary: [e.g. VMware ESXi/Raspberry Pi 4]
 - SSH Server/Client: OpenSSH
 - SSH Authentication: Keypair
 - Gravity Sync Version: 2.1.5
 - Pi-hole Versions: 5.1

**Comment by vmstan** [comment]
Do you have passwordless SUDO configured on the primary Pihole?

**Comment by nnleaf** [comment]
I did try adding `username ALL=(ALL) NOPASSWD: ALL`, but I felt it was insecure to allow my user to run sudo without a password. Is there another solution, or is it the only way for your script to work?

**Comment by vmstan** [comment]
That's the only way I've been able to accomplish it with bash scripting. Not ideal from a security perspective, but it's how most of the Raspberry Pi distros come out of the box, so it gets the job done.

**Comment by nnleaf** [comment]
Ah gotcha, I'll just have to be a bit more careful running commands on the primary PiHole then. Thanks for working on this script btw, works great!
