### ISSUE TITLE
Delete old gravity.db.backups

### ISSUE THREAD

**Issue by mr-bobdobalina** [vmstan/gravity-sync#74]
**Is your feature request related to a problem? Please describe.**
Currently a single sync of Gravity on my setup generates a 115MB backup file.  As I run sync every few minutes, it was only a matter of time before my Raspberry Pi's SD card filled up.

**Describe the solution you'd like**
Allow setting to only keep X amount of backups

**Describe alternatives you've considered**
Could be done with some scripting and cron, but built into Gravity Sync would be nice!

**Additional context**
I recently noticed my pihole acting strange. Turns out the pi ran out of space, found out the Gravity Sync backup folder full of backup files.

**Comment by vmstan** [comment]
By default it saves 7 days worth of backups. You can reduce this by modifying your gravity-sync.conf file setting to a lower number. https://github.com/vmstan/gravity-sync/blob/master/ADVANCED.md#backup_retain 

How often is is creating backups? It should only do it if something actually needs to sync.

**Comment by mr-bobdobalina** [comment]
Mine is generating for every attempted sync. Regardless if I made a change to pihole or not.  I will add the BACKUP_RETAIN='' setting.

**Comment by vmstan** [comment]
What version are you on?

Michael Stanclift
mstanclift@vmware.com
________________________________

**Comment by vmstan** [comment]
What version are you on?

**Comment by mr-bobdobalina** [comment]
2.1.7

**Comment by vmstan** [comment]
Can you post the output of your 'crontab -l'

**Comment by mr-bobdobalina** [comment]
*/2 * * * * /bin/bash /home/pi/gravity-sync/gravity-sync.sh pull > /home/pi/gravity-sync/gravity-sync.cron

**Comment by mr-bobdobalina** [comment]
ah i see now, should it be automate instead of pull now?

**Comment by vmstan** [comment]
You can run automate to generate new settings, but can you also delete your gravity-sync.md5 file and then a couple of sync jobs again. The first one will kick off because there is no md5 file, but then it should create a new one with new values.

**Comment by nnleaf** [comment]
I was just going to create a new issue, but found this. 

I installed gravity-sync yesterday but it fully filled up my VM in a day. I only allocated 10GB to the VM, which is usually more than sufficient for PiHole. 

Here is my crontab -l
*/5 * * * * /bin/bash /home/nn/gravity-sync/gravity-sync.sh smart > /home/nn/gravity-sync/gravity-sync.cron
0 1 * * * /bin/bash /home/nn/gravity-sync/gravity-sync.sh backup >/dev/null 2>&1

I've set BACKUP_RETAIN='1' to see if things work out, but it's odd that I have so many backups just for one day. I've already deleted them, but it seems it created a backup every 5 minutes.

**Comment by mr-bobdobalina** [comment]
Looks like we are good now.  I did not see the md5 get generated however.  So I guess pull was just generating backups regardless if things changed.  Looks like smart is the way to go. Thank you for your work on this script!

**Comment by vmstan** [comment]
Pull or smart they share the same backup routine. There has to be a loop somewhere that’s causing the old md5 file to trigger a sync but then not writing out the new values.

**Comment by mr-bobdobalina** [comment]
Actually hold a sec.. I just added a domain to the whitelist on the main pihole and it didn't propagate to the secondary (that has Gravity).

**Comment by mr-bobdobalina** [comment]
[ WARN ] Replication Required
[ WARN ] Both gravity.db Changed
[ INFO ] Primary gravity.db Last Changed
[  OK  ] Performing Backup of Local gravity.db
[ EXEC ] Performing Backup of Remote gravity.dbsudo: no tty present and no askpass program specified
[ FAIL ] Performing Backup of Remote gravity.db

**Comment by mr-bobdobalina** [comment]
oof and the space eating backups have returned!

**Comment by vmstan** [comment]
You said you don't see the md5 file getting created?

**Comment by mr-bobdobalina** [comment]
Just tried removing the backup folder but get the same EXEC error

Correct I don't see the md5 getting created.

**Comment by vmstan** [comment]
OOOH, now that I see "no tty present and no askpass program specified" -- you have to configure passwordless SUDO on the remote host.

**Comment by vmstan** [comment]
https://github.com/vmstan/gravity-sync#requirements link here

**Comment by vmstan** [comment]
If you were only ever running pull with the older version of the code, it never actually ran anything on the remote host, it only connected to do a copy. With the newer code it generates a backup file on the remote host, and pulls that, which requires it to run a command and it's failing because it doesn't have sudo permissions in that directory.

**Comment by mr-bobdobalina** [comment]
Got it, yup that was the issue.  Secondary pulled the updated whitelist.

**Comment by mr-bobdobalina** [comment]
Also, I blame today's cloudflare outage for this problem because that's what made me look in the first place! 😆
