### ISSUE TITLE
Remote Backup timeout is too short

### ISSUE THREAD

**Issue by Sungray** [vmstan/gravity-sync#75]
I'm getting [ FAIL ] Performing Backup of Remote gravity.db
The timeout of 15 seconds is too short. On my environment the backup takes around 35 seconds. Updating the value to 60 fixes the problem.

Thanks for this great tool, it's awesome.

**Comment by Sungray** [comment]
See PR #76

**Comment by vmstan** [comment]
Indeed. I will merge this change soon.

**Comment by Sungray** [comment]
Fixed #76
