### ISSUE TITLE
Add option to include invididual files

### ISSUE THREAD

**Issue by station7** [vmstan/gravity-sync#82]
It would be great if gravity sync could be configured to sync additional individual files, just as it does with custom.list.

I have some additional pihole/dnsmasq-config files in /etc/dnsmasq.d/ (e.g. to listen on interface tun0 for openvpn as well or for pxe-booting) which need to be synced to secondary pi-hole as well. Even though those config files are not changed as frequent as gravity.db and/or custom.list, it would be nice to have the entire pihole-configuration synced between two instances.

Thank you so much for gravity sync!

**Comment by vmstan** [comment]
Syncing more is on the todo list. Not sure if it'll be an open list but more of the configuration and the custom DNS config for sure.

**Comment by dockerpirate** [comment]
I think the easy way is to sync individual files and run "pihole reconfigure", if some changes are made

**Comment by vmstan** [comment]
Tracking in #211
