### ISSUE TITLE
No Custom List on secondary pi

### ISSUE THREAD

**Issue by markladage** [vmstan/gravity-sync#83]
Hi vmstan,
great script and seems to be working for me, two questions (please remember i'm a noob):

1.	When i run the command *./gravity-sync.sh compare* on my secondary pi i get the response **No custom.list Detected on secondary pi** (see picture). Is this normal? Everything seems to work fine.
 ![image](https://user-images.githubusercontent.com/57064262/89193088-bfa80080-d5a5-11ea-8740-003d6ea06139.png)

2.	In your tutorial under the section configuration it says create a configuration file with *./gravity-sync.sh config*. This must be run from the home directory **/home/pi/gravity-sync** as all of the gravity-sync.sh commands either they will not run, correct?

Thanks, Mark

**Comment by vmstan** [comment]
So on #1, if you're not using the "Local DNS Records" section in Pi-hole for anything, you'll have never created the custom.list file. The Local DNS Records function would be if you wanted to overwrite the DNS lookups for a domain or set a static IP for an internal address (host.domain.local > 192.168.1.7) -- the file only exists once data gets generated within the Pi-hole interface.

You are correct on #2, it must be run from that folder. You **could** setup an alias in your bash profile to do something like reference "gs" to be "sh /home/pi/gravity-sync/gravity-sync.sh" and then be able to run "gs config" from any location.

Maybe I should add that to the script as an option. 🤔

**Comment by markladage** [comment]
Thanks!
