### ISSUE TITLE
Help: sudo: a terminal is required to read the password

### ISSUE THREAD

**Issue by aidenmitchell** [vmstan/gravity-sync#84]
The script fails on the ``` [ EXEC ] Performing Backup of Remote gravity.db ``` stage with an error ```sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper```.

I don't understand what it's asking for.

**Comment by vmstan** [comment]
Hey @aidenmitchell, sorry for the delay, were you able to get this working for you or it still an issue?

**Comment by aidenmitchell** [comment]
@vmstan It's still an issue.

**Comment by vmstan** [comment]
Do you have passwordless sudo enabled?

https://linuxize.com/post/how-to-run-sudo-command-without-password/

**Comment by andrema2** [comment]
> Do you have passwordless sudo enabled?
> 
> https://linuxize.com/post/how-to-run-sudo-command-without-password/

It worked after it. Thanks

**Comment by papalozarou** [comment]
Apologies for resurrecting this, however I'm having the same issue. Have added a user specific sudoers file in `/etc/sudoers.d` but it's not working.

`NOPASSWD: ALL` works
`NOPASSWS: /path/to/script` does not

It's on a Synology, which may or may not be the problem – searching around the Synology community suggests that the second option _should_ work.
