### ISSUE TITLE
SD Card Filling on Pi Zero

### ISSUE THREAD

**Issue by BrianAMartin221** [vmstan/gravity-sync#85]
**Describe the Issue**
I Am running Gravity-Sync on both a Rasberry Pi 4 with PiHole and a Rasberry Pi Zero. After about a week my 32GB SD card on my PiZero fills up, if i remove Gravity-Sync all of the space is free. PiHole and Gravity-Sync are the only things running on my Pi Zero. 

I am not seeing this issue on my Pi4 which also only has PiHole & Gravity Sync. I am sure its a configuration issue on my end but I can't figure out what is configured differently. 

**Screenshots**

**Configuration:**
 - SSH Server/Client: Open SSH
 - SSH Authentication: Keypair
 - Gravity Sync Version: 2.0
 - Pi-hole Versions: v5.1

**Comment by vmstan** [comment]
How often is your sync script set to run, and how often are you making DB changes? It creates a backup in the gravity-sync/backup folder anytime it's replicating. By default it will keep 7 days worth of backups, but this is adjustable.

![CleanShot 2020-08-10 at 08 48 33@2x](https://user-images.githubusercontent.com/3002053/89789502-4ac55100-dae6-11ea-905b-8a9829ea86a7.png)

**Comment by BrianAMartin221** [comment]
I did make a pretty high number of database changes last week, and the Pi4 runs on an SSD with 64GB. I don't anticipate making that many database changes in the next few months so that's good to know. 


I am going to reconfigure Gravity Sync on the Zero Pi and since that's on a smaller SD Card I think I'll go with the least amount of backups to avoid this.

**Comment by vmstan** [comment]
Yeah, if it doesn't detect any changes it doesn't run the sync or backup anything, but if it sees a change each time then it could fill up quick. You can co in and delete any of the .backup files you want at anytime. There's no tracking of them outside of when the restore function runs but it'll check to see what's in that folder when it does.

**Comment by vmstan** [comment]
The other thing you could do would be after you run the config function to setup the script, manually edit your gravity-sync.conf to adjust the retention policy.

https://github.com/vmstan/gravity-sync/blob/master/ADVANCED.md#backup_retain

**Comment by BrianAMartin221** [comment]
That is perfect thank you for your help!
