### ISSUE TITLE
service command not found

### ISSUE THREAD

**Issue by mabs67** [vmstan/gravity-sync#87]
**Describe the Issue**
while running ./gravity-sync.sh smart command service was not found, but it is available as that user.
"Kommando nicht gefunden" means "command not found"

**Screenshots**
[ INFO ] Isolating Regeneration Pathways
[  OK  ] Updating FTLDNS Configuration
[  OK  ] Reloading FTLDNS Services
[ INFO ] Inverting Tachyon Pulses
[  OK  ] Updating Remote FTLDNS Configuration
[ EXEC ] Reloading Remote FTLDNS Services  [✗] /usr/local/bin/pihole: Zeile 127: service: Kommando nicht gefunden.
[ FAIL ] Reloading Remote FTLDNS Services
osmc@osmc-rpi3:~/gravity-sync$ 

**Configuration:**
 - OS for Primary/Secondary: Debian 9.3 (OSMC)
 - Platform for Primary/Secondary: Raspberry Pi 2 and 3 but same OS installation
 - SSH Server/Client: OpenSSH
 - SSH Authentication: Keypair
 - Gravity Sync Version: 2.2.0 (just installed)
 - Pi-hole Versions: v5.1.2 (just installed)

**Additional Context**
I'm not sure whether the service is actually needed from gravity-sync or from the pihole script

**Comment by vmstan** [comment]
It looks like it cannot find the pihole binary on the remote host, in the directory /usr/local/bin/. Does that file exist on the remote host?

**Comment by mabs67** [comment]
Yes the pihole file is in /usr/local/bin in both pi-hole servers. I was also running the gravity-sync using bash -x but could not really see where the service command is called there

**Comment by mabs67** [comment]
I found the (partly) the issue, I needed to change service in line 120 in /usr/local/bin/pihole to /usr/sbin/service, no idea why it does not takes the $PATH settings, since /usr/sbin is in for the user and root.
So for sure it is not a gravity-sync issue as such.

**Comment by vmstan** [comment]
That's super strange, are both the Pihole's recently installs, or just the secondary?

**Comment by mabs67** [comment]
Both.

Before I had also two piholes with keepalived in docker on rockpro64 boxes, but since 5.X (not 100%sure). The web interface is not really working, even without docker on rockpro64. Then I decided to install the two on my OSMC based raspberry Pi2 and and Pi3 ones. There is works now nicely. Except for this issue.

**Comment by vmstan** [comment]
Would it be helpful if you could specify the binary location of the primary Pihole as part of the advanced configuration?

**Comment by vmstan** [comment]
Fixed in 2.2.1
