### ISSUE TITLE
Merged Stats

### ISSUE THREAD

**Issue by old-square-eyes** [vmstan/gravity-sync#88]
Great app/service thanks, and excellent easy to follow instructions.

I didn't see anywhere (instructions or open/closed issues) discussion on synchronising stats.

I'm not 100% on what's possible, or even what my requirements would be. Likely it would involve the Pihole devs too.

But a MVP solution might be one of the following...

1. Master shows stats for both master and slave
2. Master has a dashboard/widget showing tally of certain metrics (master + slave)
3. Some CLI aggregate of data

**Comment by vmstan** [comment]
Honestly that would be a whole other application. I think there are a few community solutions out there at do something similar. The Pihole team has added a ton of new APIs to 5.x recently. _Pihole Remote_ on iOS comes to mind as someone who is doing a lot of this. But it's not something I'm interested in maintaining as part of Gravity Sync.

Glad it does what it does for you well, though 😄
