### ISSUE TITLE
Backups not deleting

### ISSUE THREAD

**Issue by ALittleOfEverything88** [vmstan/gravity-sync#89]
Ran through the installation as outlined on the page (on DietPi). Using SSH and not DropBear (that was a trip). Everything seems to run fine, however, the backups folder fills up until there is no free space left on the SD card.

How do I have the script delete backups older than X amount of Y?

**Comment by vmstan** [comment]
The script will automatically delete backups older than 7 days, and you can adjust how often. A few questions:
- How big is your database?
- How often do you make DB changes?
- How often are you syncing?

**Comment by ALittleOfEverything88** [comment]
1. Not sure - how do I find this out?

2. Rarely

3. Here's the output of crontab -l:
`crontab -l
*/10 * * * * /bin/bash /home/dietpi/gravity-sync/gravity-sync.sh > /home/dietpi/gravity-sync/gravity-sync.cron`

**Comment by vmstan** [comment]
@ALittleOfEverything88 Any luck?

**Comment by SalkinDK** [comment]
I have the same problem. installed on a fresh raspberry pi os (32bit). i installed version 2.2.1 of your script.
i have set BACKUP_RETAIN='1' in the gravity-sync.conf, but i still have backups from 6 days ago. and as a result of the many backups a full sd card, so pihole stopped working.
it is like the setting in the conf file isnt respected, and it still goes for seven days.

Let me know if you miss some info.
And thanks ALOT for you work!

**Comment by vmstan** [comment]
Please update your install to 2.2.2 and test again.

`./gravity-sync.sh update`
