### ISSUE TITLE
Not possible to config as root

### ISSUE THREAD

**Issue by n3roGit** [vmstan/gravity-sync#90]
when installing gravity as root you got the following error:

./gravity-sync.sh config
[ INFO ] Gravity Sync 2.2.1 Executing
[  OK  ] Importing gravity-sync.conf Settings
[ FAIL ] Evaluating Arguments ROOT
[ WARN ] Gravity Sync Must Not Run as Root
[ INFO ] Gravity Sync ROOT Aborting (0 seconds)

running as user pi is working.

**Comment by vmstan** [comment]
This is by design.
