### ISSUE TITLE
Configure sudoer.d file to only allow required permissions

### ISSUE THREAD

**Issue by bstlaurentnz** [vmstan/gravity-sync#92]
**Is your feature request related to a problem? Please describe.**
Right now the instructions call for a user that has unlimited root access to both pis. 

**Describe the solution you'd like**
Given the commands are known in advance, it should be possible to have gravity-sync config output a sudoers.d file that is tailored to only give permissions needed by the script. 

**Describe alternatives you've considered**
Alternately, the permissions on the files that need to be updated on either pi could be modified to allow the pihole-sync user to modify / overwrite, but this would get clobbered on each pihole update. 

**Additional context**
The challenge here is that giving chown / chmod permissions along with cp / rsync is risky as it allows someone to copy a root shell.

**Comment by vmstan** [comment]
Very interesting, and not something I was even aware would be possible until now. I will have to investigate more but agree this would be a lot cleaner and more secure.

**Comment by bstlaurentnz** [comment]
I think if the sudo is moved out of the shell script and then the shell script itself is run using sudo, you can specify that particular file as the only command the gravity-sync is allowed to do. I'll fork the repo and have a play this week and let you know how it goes.
