### ISSUE TITLE
Fail when running script between raspberry pi 2b and debian 10.5 server

### ISSUE THREAD

**Issue by mcmikev** [vmstan/gravity-sync#93]
When running the script on my raspberry pi pihole (rpi2b) to sync from the primary server (debian 10.5 server).
Everything works up until the moment there needs to be some transfering.

I receive an error then:

[ WARN ] Differenced custom.list Detected
[ WARN ] Replication Required
[ WARN ] Both gravity.db Changed
[ INFO ] Secondary gravity.db Last Changed
[ EXEC ] Performing Backup of Remote gravity.dbsudo: no tty present and no askpass program specified
[ FAIL ] Performing Backup of Remote gravity.db

The last two lines describe the issue but I cannot figure out why.
User has rights on pi and other way around. I log in using key pair and not password, however with password the result is the same.

Any pointers would be welcome to troubleshoot, smash this problem :-)

**Comment by vmstan** [comment]
You need to make sure that passwordless sudo is enabled for the user account on the remote system.

https://linuxize.com/post/how-to-run-sudo-command-without-password/

**Comment by mcmikev** [comment]
Thanks for pointing me to that. I added the user from the debian server to the sudoers file on the debian server wit NOPASSWD:ALL and now it works.
Thanks for great script!!!!!
